### ISSUE TITLE
Active Service List 에 클라이언트IP 항목 추가 요청

### ISSUE THREAD

**Issue by pudak77** [scouter-project/scouter#107]
안녕하세요.
정말 좋은 솔루션을 기분좋게 사용하고 있는 사용자 입니다.
저희 웹사이트에 장난을 치는 사용자들이 있어 WAS 부하를 유발시키는 현상이 종종 발생을 하는데요.
지연되는 트랜잭션을 확인하려 Active Service EQ에서 클릭해서 확인을 해보면 해당 트랜잭션이 종료되기 전까지(xlog에 찍히기 전까지)는 Active Service List에서는 Thread Dump 내용 밖에 확인이 안됩니다.
이에 Active Service List 에 클라이언트IP가 같이 노출될 수 있다면 특정 사용자의 장난질임을 빨리 확인 가능할 것 같습니다.
해당 기능의 긍정적인 반영 검토 부탁드려요~

**Comment by bill23-kim** [comment]
v0.4.6에 추가하였습니다. 좋은 의견 감사합니다.

https://github.com/scouter-project/scouter/releases/tag/v0.4.6
