### ISSUE TITLE
Agent jBoss EAP 5 support.

### ISSUE THREAD

**Issue by elmemis** [scouter-project/scouter#116]
Please, add support for jBoss EAP 5.

Thanks, good project.

**Comment by gunlee01** [comment]
I think scouter support JBoss 6 and wildfly.
Isn't the JBoss EAP 5 compatible with JBoss AS 6 and use tomcat as it's servlet engine?.
Or If you use JBoss AS 7 then try to check the option has 'scouter' package on the JBoss startup script
   -Djboss.modules.system.pkgs=~~~~~,scouter
