### ISSUE TITLE
WebLogic, JEUS 연동 되나요??

### ISSUE THREAD

**Issue by high-high** [scouter-project/scouter#120]
에이전트는 없는거 같은데, OpenSource만 지원가능한건가요???

**Comment by gunlee01** [comment]
Scouter의 Java Agent는 Java로 만들어진 어플리케이션에 사용 가능합니다.
WAS는 Tomcat에 테스트되었으며 Tomcat에 최적화된 기능 및 특화된 기능을 제공합니다.
타 상용 WAS에 대해서는 특별히 테스트하지 않습니다.

**Comment by hkjang** [comment]
JEUS는 테스트 해봤는데 XLog 잘 잡히네요~ 참고해주세요~

**Comment by high-high** [comment]
혹시 JEUS설정을 어떻게 하셨는지 알려 주실수 있나요?

**Comment by wall72** [comment]
1. agent 관련 JAVA_OPTS 설정은 JEUSMain.xml에 command-option 에 기술하시면 됩니다. (제니퍼와 동일)
2. XLog 가 안나오는 이유는 obj_type=java 로 자동설정되어 그렇습니다. agent 설정 conf 파일 하나 만드시고 obj_type=tomcat 이라고 속이시면 됩니다.

**Comment by holdenkim** [comment]
IBM Websphere 설정 할 수 있는 방법이 있을까요?

**Comment by hkjang** [comment]
@high-high 

JEUS 설정 ~
JEUSMain.xml 의 container 설정 command-option 추가하시면 됩니다.

설명 Engine Container의 JVM에 들어가는 옵션을 적어준다. 
예제 <command-option>-Xms64m -Xmx128m -javaagent:/xxx/scouter/agent.java/scouter.agent.jar -Dscouter.config=/xxx/scouter/agent.java/scouter.jeus.conf</command-option> 

scouter.jeus.conf 파일 

obj_name=jeus_container1
obj_type=java
#hook_method_patterns=com.class.*.*
#_trace_auto_service_enabled=true
hook_service_patterns=com.Class
hook_method_access_public_enabled=true
hook_method_access_private_enabled=true
hook_method_ignore_classes=com.log.Class.*.*,com.util.Class
hook_method_patterns=com.Class.method, ....


@holdenkim ibm websphere 도 역시 컨테이너 추가&실행 시 
command 옵션에 아래와 같이 실행하시면 될것 같네요.

-javaagent:/xxx/scouter/agent.java/scouter.agent.jar -Dscouter.config=/xxx/scouter/agent.java/scouter.jeus.conf

**Comment by 23king** [comment]
Weblogic 이상없이 적용되는것 확인했습니다

**Comment by mcwony** [comment]
혹시 JEUS 7 버전에 적용해 보신 분 계실까요?

Filter가 적용된 Web Application을 모니터링 하려고 설정해 봤는데, 
Deploy가 계속 실패하네요.

**Comment by gaiajeon** [comment]
오늘 JEUS7에 적용했습니다.
아직까지는 아무 문제가 없는 상태이구요.

어떤 필터가 적용된 것인지 알 수가 있을까요?

혹시 발생한 에러메시지가 있다면 같이 첨부해주시면 감사하겠습니다.
