### ISSUE TITLE
scouter도 레포트 기능 있나요??

### ISSUE THREAD

**Issue by high-high** [scouter-project/scouter#126]
처리된 서비스 통계자료를 뽑는 레포트 기능있나요??

그리고 DB파일로 저장된다는데, 어떤식으로 저장이 되는건가요??

Log파일로 만들어서 저장되는건가요??

**Comment by bill23-kim** [comment]
현재 Scouter에 레포트 기능은 없습니다. Scouter에서 DB 파일은 자체 정의한 데이터 타입을 바이트 형태로 저장하여 사용하고 있습니다.
