### ISSUE TITLE
2개 이상의 Collector Server가 등록되면 최초 등록된 Collector Server에서 수집된 정보만 표시됩니다.

### ISSUE THREAD

**Issue by nices96** [scouter-project/scouter#127]
로컬 서버에 server 및 agent.host를 구동하고 Scouter App을 실행하여 127.0.0.1:6100으로 접속한 상태에서 데모 서버(demo.scouterapm.com:6100)를 추가하였는데, 데모서버의 성능 모니터링 정보가 표시되지 않습니다.

실행 환경은 다음과 같습니다.

OS : Mac OSX
Java Version : 1.7.0_40
Scouter Server Version : 0.4.0 20151223
Scouter Host Version : 0.4.0 20151223
Scouter Client Version : 0.4.5 20160120

**Comment by bill23-kim** [comment]
추가한 데모서버가 오브젝트뷰에 안나타난다는 말씀이신가요?

**Comment by nices96** [comment]
오브젝트뷰에 데모서버랑 톰캣 인스턴스 정보는 표시가 되지만 데모서버에서 수집되고 있는 모니터링 정보(XLog, TPS, CPU 등)가 표시되지 않습니다.

**Comment by bill23-kim** [comment]
오브젝트뷰에서 추가된 데모서버를 우클릭 하시고 Set as a default server 를 눌러 보시면 전체적으로 차트가 데모서버에 맞게 셋팅 될 것입니다. 서버와 클라이언트의 버전차이로 일부차트가 안나올수는 있습니다.

**Comment by nices96** [comment]
네. 알려주신대로 해보겠습니다. 감사합니다.

**Comment by nices96** [comment]
정상 동작 확인하였습니다. 감사합니다.
