### ISSUE TITLE
jboss-eap-6.3(상용) xlog sql 미출력

### ISSUE THREAD

**Issue by updrye** [scouter-project/scouter#148]
안녕하세요

jboss-eap-6.3 에 Scouter 를 설치해 현재 서버를 모니터링하고 있습니다.

서비스는 Spring + Mybatis + Postgresql 9.4 기반으로 개발되었으며 

XLog SQL 관련 문의사항이 있어 질문드립니다.

JDBC 방식으로 DB Connection 설정하게 되면 XLog 에 SQL 이 정상적으로 잡히고

jboss-eap-6.3 WAS Connection Pool 을 사용하도록 JNDI 방식으로 DB Connection 하게 되면

XLog 에 SQL 이 잡히지 않습니다.

Scouter 가 JDBC 방식만 지원하는지 아니면 JNDI 방식을 지원하는데 제가 놓친 부분이 있는지

답변부탁드립니다.

감사합니다.

**Comment by bill23-kim** [comment]
SQL이 프로파일링 되는것은 커넥션 방식에 상관없이 같은 JDBC 드라이버를 사용한다면 나와야 하는것이 맞습니다. 커넥션 방법 외에 다른 차이점이 어떤게 있는지 다시 검토 부탁드려요.

**Comment by updrye** [comment]
다시 확인해보니 jdbc 방식은 postgresql jar, jndi 방식은 edb jar 파일을 사용하고 있었습니다.

hook_jdbc_pstmt_classes=com.edb.jdbc2.AbstractJdbc2Statement

위 설정을 추가해 해결하였습니다.

감사합니다.
