### ISSUE TITLE
Heap Used 과거 데이터 조회

### ISSUE THREAD

**Issue by ymggt** [scouter-project/scouter#150]
Heap Used 과거 데이터 조회할때 좀 안되는것 같네요.. 마우스로 팝업띄워서 Daily를 선택해서 날짜를 선택하는데.. 나오는 날 있고 안나오는 날이 있네요.... past하면 되는거 같습니다... 하루 단위로 뽑고싶었는데 안되는건가요???

**Comment by gunlee01** [comment]
Daily의 경우는 5분 summary 데이터로 보여주며 Past의 경우는 실제 수집된 초데이터로 보여주는 기능입니다.
원인은 알 수 없으나 해당 data 파일에 손상이 있는 경우 그런 현상이 발행할 수도 있을 것 같습니다.

**Comment by bill23-kim** [comment]
Scouter버전과 Collector의 nohup.out 로그 공유해주시면 이슈해결에 도움이 될것 같습니다.

**Comment by ymggt** [comment]
한 일주일간의 로그가 있는데 nohup에 200메가정도 쌓여있네요..
내용을 보니까 아래와 같이 NullPointerException계속 초반에 나오다가 
java.lang.NullPointerException
	at scouter.server.db.counter.DailyCounterData.writeNew(DailyCounterData.scala:186)
	at scouter.server.db.DailyCounterWR$$anonfun$1.apply$mcV$sp(DailyCounterWR.scala:65)
	at scouter.server.util.ThreadScala$$anon$4.run(ThreadScala.scala:61)

나머지는 아래의 NullPonterException 만 찍히네요 이유도 없이 ㅎㅎ
java.lang.NullPointerException

200메가라 너무 크기도 하고 제가 보니까 단순이 위와 같이 반보적으로 찍혀서 첨부파일은 따로 안 넣었습니다...

일 단위로는 잘 안보이긴하는데 머 사용하는데는 감수하고 쓸 수 있어서 일단 그냥 잘 사용 하고 있습니다.~ (Past 4시간은 되거든요..)

**Comment by ymggt** [comment]
버전은 v0.4.10 Release 입니다.

**Comment by gunlee01** [comment]
그런 에러 발생이 의심되는 부분에 대한 fix가 추가되었습니다.
다음 릴리즈되는 버전을 한번 적용해 보세요.
