### ISSUE TITLE
slack plugin

### ISSUE THREAD

**Issue by 23king** [scouter-project/scouter#160]
slack plugin을 만들었는데
scouter-project 밑에 telegram plugin처럼 repository를 추가하여 push하려고 합니다

어떻게 해야 할까요?

**Comment by gunlee01** [comment]
안녕하세요. 
slack plugin을 개발해 주셔서 감사합니다.
개인 Repository가 아닌 scouter-project에 repository를 생성하여 등록하시기를 원하시면
먼저 개인 repository를 알려주시고 Reviewer가 검토 후 적합하다고 판단되면 CLA(Countributor License Agreement) 경로를 보내드리고 CLA에 서명이 되면
scouter-project내에 repository를 생성하여 해당 repository에 commiter 권한을 부여 드립니다.
검토를 위해 먼저 개인 repository 경로를 알려주세요.
readme.md등으로 사용자를 위한 document page가 있어야하며 License는 Apache 2.0 이어야 합니다.

**Comment by 23king** [comment]
개인 repository는 아래와 같습니다.
https://github.com/23king/scouter-plugin-server-alert-slack

**Comment by gunlee01** [comment]
아래 CLA에 서명 후 알려주시기 바랍니다.
http://goo.gl/forms/xSmYs8qM9J

**Comment by 23king** [comment]
완료했습니다 감사합니다

나의 iPhone에서 보냄

2016. 5. 9. 오후 9:53 Gunhee Lee <notifications@github.com> 작성:

**Comment by gunlee01** [comment]
해당 plugin repository에 commit 권한이 부여되었습니다.
