### ISSUE TITLE
AS400 PreparedStatement 문의

### ISSUE THREAD

**Issue by soyacg** [scouter-project/scouter#161]
scouter 셋팅해서 테스트 중에 있는데요~ 문의사항이 있어서 글 남깁니다.

AS400 DB2를 사용해서 아래와 같이 셋팅을 해봤는데요.

hook_jdbc_stmt_classes=com.ibm.as400.access.AS400JDBCStatement
hook_jdbc_pstmt_classes=com.ibm.as400.access.AS400JDBCPreparedStatement

Statment는 Profile에 잘 남는데
PreparedStatment는 아래처럼 제대로 남지 않더라구요.

16:44:03.559      329      0  PRE> @
                                           [2] 23 ms

혹시 설정이 잘못됐거나 추가해야 할 부분이 있을까요?
아님 AS400 DB2는 불가한건가요~? 

감사합니다.

**Comment by bill23-kim** [comment]
as400 db2 환경을 구성하지 못해서 테스트를 못해봤네요^^;; db2 는 hooking 보다는 wrapping 방식으로 쿼리를 캐치하기 때문에 hook_jdbc_wrapping_driver_patterns 옵션으로 해결해보심이...... scouter.agent.asm.JDBCDriverASM 클래스를 참고하셔서요~

**Comment by soyacg** [comment]
답변 감사드립니다.
hook_jdbc_wrapping_driver_patterns=com.ibm.as400.access.AS400JDBCDriver
이렇게 옵션을 추가하면 되는건가요~?

**Comment by bill23-kim** [comment]
뒤에 메소드 네임도 이어서 붙여주셔야 됩니다. com.ibm.as400.access.AS400JDBCDriver.connect 이런식으로요

**Comment by soyacg** [comment]
알려주신 것처럼 아래와 같이 설정을 추가하였습니다.
hook_jdbc_wrapping_driver_patterns=com.ibm.as400.access.AS400JDBCDriver.connect

페이지를 호출하니 아래와 같이 에러가 발생을 하네요...;
org.apache.jasper.JasperException: javax.servlet.ServletException: java.lang.VerifyError: (class: com/ibm/as400/access/AS400JDBCDriver, method: connect signature: (Lcom/ibm/as400/access/AS400;)Ljava/sql/Connection;) Illegal local variable number
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:549)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:455)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

**Comment by bill23-kim** [comment]
내부적으로 class 변조를 하지 못하도록 막는 무언가가 있나보네요...  그걸 회피 할수 있는 방법은 잘모르겠습니다.. 아시는 분 있으시면 답변좀.. ㅠ

**Comment by sjokim** [comment]
AS400은 워낙에 독특한 유전자를 가지고 있어서요^^
혹시 DB가 AS400인지 아니면 WAS도 AS400에서 돌리고 있는지 
JDK버전 같은 정보가 필요할 것 같습니다.

**Comment by soyacg** [comment]
기존에 톰캣7, JDK 1.6에서 에러가 발생을 해서 
톰캣7, JDK1.7로 변경을 하니 문의 드렸던 에러가 발생을 하지 않았습니다.

그런데 SQL 수행 정보는 여전히 확인이 안되네요...ㅜㅜ
  - hook_jdbc_wrapping_driver_patterns=com.ibm.as400.access.AS400JDBCDriver.connect

그리고 처음 했던 설정도 동일하게 안됩니다.
  - hook_jdbc_stmt_classes=com.ibm.as400.access.AS400JDBCStatement
  - hook_jdbc_pstmt_classes=com.ibm.as400.access.AS400JDBCPreparedStatement
1.6일 땐 처음 작성한 내용처럼 Statment 수행에 대한 SQL Profile은 남았었는데 1.7로 하니 이것도 안되네요.

설정을 안했을 때나 두가지 설정을 각각 해봤을 때나 전부 socket 연결 정보만 표시됩니다.

**Comment by guindous** [comment]
Hi! I'm also trying to make SQL Tracing working with JT400 open driver connecting to AS400 DB2 DBMS. I tried to automatic translate this question, but the result wasn't easy to understand. Somebody achieved it? If some provides an english summary it will be really appreciated. If not, I will be glad to code the automatic detection of this driver if some one kindly gives me the basic guidelines.
Thanks in advance for your support.

**Comment by kukgini** [comment]
시간이 좀 지났지만 이렇게 설정하면 어떤가요?  

hook_jdbc_wrapping_driver_patterns=com.ibm.as400.access.AS400JDBCDriver.connect(Lcom/ibm/as400/access/AS400;)Ljava/sql/Connection;

혹은 jt400-6.4.jar 드라이버 기준으로 했을때 여러개의 connect 메서드가 존재하니 다음 설정을 하나씩 시도해 보세요.

com.ibm.as400.access.AS400JDBCDriver.connect(Lcom/ibm/as400/access/AS400;Ljava/util/Properties;Ljava/lang/String;)Ljava/sql/Connection;
com.ibm.as400.access.AS400JDBCDriver.connect(Lcom/ibm/as400/access/AS400;Ljava/util/Properties;Ljava/lang/String;B)Ljava/sql/Connection;
com.ibm.as400.access.AS400JDBCDriver.connect(Lcom/ibm/as400/access/AS400;B)Ljava/sql/Connection;
com.ibm.as400.access.AS400JDBCDriver.connect(Ljava/util/Properties;Ljava/lang/String;)Ljava/sql/Connection;
