### ISSUE TITLE
How is the overhead of Scouter?

### ISSUE THREAD

**Issue by xiaomutoun123** [scouter-project/scouter#169]
Hi, 

I am in a project of evaluating different APM tools and I find that Scouter is quite good to use. But I didn't find any information about the overhead of this tool. So can anyone tell me about the overhead of Scouter on the monitored web server? Is there any documents explaining about it? Looking forward for your help.

**Comment by gunlee01** [comment]
I guess it increase slightly your web application server's CPU usage commonly less than 1~3% usage.
