### ISSUE TITLE
ppas xlog sql 프로파일링 문의

### ISSUE THREAD

**Issue by jungsookim** [scouter-project/scouter#170]
안녕하세요

spring + myBatis + PPAS 를 사용중인데
SQL 모니터링이 안되네요..

hook_jdbc_pstmt_classes=com.ebd.jdbc4.Jdbc4PreparedStatement
hook_jdbc_stmt_classes=com.ebd.jdbc4.Jdbc4Statement

셋팅해보긴 했습니다.

감사합니다.

**Comment by gunlee01** [comment]
사용하시는 jdbc가 어떻게되나요?

**Comment by jungsookim** [comment]
postgresql 의 상용버전인 Postgresql advanced server 의 JDBC 인 edb-jdbc16.jar
를 사용하고 있습니다.

**Comment by jungsookim** [comment]
오타도 있었네요 ;;
hook_jdbc_pstmt_classes=com.edb.jdbc2.AbstractJdbc2Statement
이렇게 해서 profiling 되는 것을 확인하였습니다.
