### ISSUE TITLE
[load history] 오류 

### ISSUE THREAD

**Issue by cf7802** [scouter-project/scouter#172]
Scouter Server 를 구성하고, 
약 7대의 서버를 모니터링 중입니다. 

설치 한지는 약 2개월 정도 되었는데.. 
언젠가 부터, Xlog 에서 load history 를 하면 데이터 로드가 되지 않습니다 

히스토리를 확인 할 수 있는 방법이 없을가요?

**Comment by 23king** [comment]
collecotr 서버의 log_keep_days 이 데이터를 31일만 가지고있는 옵션이라는 가정하에..
이 옵션 때문에 데이터가 지워진게 아닐까 예측해봅니다.
collector 서버의 database 폴더를 확인해보세요 날짜별로 인덱싱되어있어 데이터가 언제부터 언제까지 있는지 확인 가능합니다.

**Comment by bill23-kim** [comment]
23king님 말씀이 거의 맞는데 log_keep_days 는 log를 보관하는 기간이고 실제 database 에 쌓이는 데이터 기간에 대한 옵션은 mgr_purge_keep_days 입니다. 그리고 mgr_purge_disk_usage_pct 는 디스크에 쌓인 데이터 사용률을 보고 판단하여 과거데이터를 삭제합니다.

**Comment by 23king** [comment]
아 그렇군요 이렇게 또 옵션 몇개를 알아갑니다. 정리 해놔야겠어요 ㅎㅎ

**Comment by cf7802** [comment]
위의 내용 확인 하고, 몇가지 질문 드립니다. 
제가 Scouter 의 자세한 내용을 자 몰라서.. ^^ 

현재, 서버에 당일 Data 만 쌓이고 있습니다. 

어제 5월 19일의 데이터가 있었는데, 금일 확인해 보니 5월 20일의 데이터만 쌓이고 있구요.
 
별다른 설정 변경을 하지 않았는데, 언젠가 부터 이렇게 쌓이고 있습니다. 

그리고 Scouter 의 설정을 변경 하는 부분이 어느 부분인지 문의 드립니다. 

설치 Path : /usr/local/Scouter 입니다.

**Comment by bill23-kim** [comment]
scouter server 가 설치되있는 서버의 디스크 용량을 확인해보세요. 기본설정은 80% 이상이면 과거 데이터를 삭제합니다.

**Comment by cf7802** [comment]
감사합니다. 
관련 내용 확인 완료 하였습니다. 

도움 주셔서 감사합니다.~~~
