### ISSUE TITLE
일반 자바 어플리케이션도 모니터링 가능한가요?

### ISSUE THREAD

**Issue by cromirak** [scouter-project/scouter#175]
제목과 같이 자체적으로 만든 일반 자바 어플리케이션도 모니터링 가능한지 문의 드립니다.
가능하다면 어떤식으로 scouter를 설정하고 실행해야 하는지도 궁금합니다.

**Comment by gunlee01** [comment]
아래 url 참고하세요.
https://github.com/scouter-project/scouter/blob/master/scouter.document/use-case/NON-HTTP-Service-Trace.md

**Comment by myboksi** [comment]
위 방식으로 쓰레드를 모니터링 하고 싶은데 Active Service EQ에 뜨는게 없습니다.
버전은 0.4.14입니다.

설정은 호스트에 했습니다.
_trace_auto_service_enabled=true
_trace_auto_service_backstack_enabled=true

hook_service_patterns=cosse.SendThread.send

hook_method_patterns=
hook_method_access_public_enabled=true
hook_method_access_private_enabled=false
hook_method_access_protected_enabled=false
hook_method_access_none_enabled=false
hook_method_ignore_prefixes=get,set

**Comment by bill23-kim** [comment]
Window -> Preferences 에서 default javeee type 을 java 로 바꿔보세요.

**Comment by myboksi** [comment]
순수자바 데몬도 모니터링이 되는거 맞죠 ? 혹서 서버/클라이언트만 모니터링 되는건가요 ?
