### ISSUE TITLE
서버 목록에서 삭제 

### ISSUE THREAD

**Issue by cowboy93** [scouter-project/scouter#176]
서버 목록에서 잘못 지정한 agent 를 삭제하는 방법이 있는지요 ? 

수집서버를 재시작 하면 되나요 ?

**Comment by bill23-kim** [comment]
오브젝트뷰 위에 드랍다운 메뉴중에 remove inactive 가 있습니다. inactive 된 에이전트 목록을 없애줍니다.

**Comment by cowboy93** [comment]
네 확인 완료했습니다. 

빠른 답변 감사합니다. ^^;

**Comment by passionlim** [comment]
저도 메뉴를 찾을 수 없어서 캡쳐 화면 공유 드립니다.
![scouter - remove inactive](https://cloud.githubusercontent.com/assets/4545649/25716951/ea9a369e-313b-11e7-9956-1311be842f34.png)
