### ISSUE TITLE
Sybase Database는 xLog에 SQL이 나오지 않네요...

### ISSUE THREAD

**Issue by domdomnmadam** [scouter-project/scouter#177]
정말 잘 만들어 주셔서 감사 합니다. 

한가지 질문이 있습니다. 

JBoss EAP6.4에서 jconn4.jar를 이용 Sybase ASE에 접속을 하고 있습니다. 

헌데 Oracle같은 경우 xLog에 SQL이 잘 나오는데 Sybase ASE의 경우 나오지 않는 현상이 있습니다. 

지원을 하지 않는 것인지요?

hook에서 result, stmt등 클래스를 등록해도 나오지 않았습니다. 

최신까지 적용해보았지만 나오지 않더라구요....

jdbc는 JDBC Version 4의 jconn4.jar 입니다. 
hook에서는 com.sybase.jdbc4.해서 들어가는 클래스를 사용하였습니다. 

감사합니다.  질문 안드리려고 했는데.. ㅠ,.ㅠ

**Comment by gunlee01** [comment]
시간될때 한번 해보겠습니다. 처음보는 드라이버라...^^
