### ISSUE TITLE
Listen to 5 hosts

### ISSUE THREAD

**Issue by prakash047** [scouter-project/scouter#179]
Dear Team,

Could you please help me on how to listen to 5 hosts by opening the client from my machine.

Any solution closer to this also highly appreciated.

BTW thanks for the tool.

**Comment by gunlee01** [comment]
Hi. prakash
Have you set options on the conf file of the host agent?
You can configure a collector server ip and ports and the file is on agent.host/conf/scouter.conf by default.
Try to cinfigure the option net_collector_addr=x.x.x.x on that file.

**Comment by prakash047** [comment]
Thank you. 
1. But how do I configure for multiple hosts? comma separated? 
2. I am able to add a collecting server from scouter client GUI  is it same as doing it from the scouter.conf file??

**Comment by gunlee01** [comment]
If you want to monitor multiple hosts using one collecting server, you may **_run host agent on every host  that you want to monitor_** and configure net_collector_ip=[collector server ip] option also of every host.
 - unzip scouter.agent.tar.gz on every host.
 - configure agent/host/conf/scouter.conf.
 - run host.sh for starting host agent.

Or if you have multiple collecting servers aleady, you can add all servers just context menu "add servers" on the object view of scouter client.

![image](https://cloud.githubusercontent.com/assets/6788732/15675656/e07527dc-277d-11e6-93e6-f8d61fe348a0.png)
