### ISSUE TITLE
Is there agents for other modules?

### ISSUE THREAD

**Issue by xiaomutoun123** [scouter-project/scouter#182]
Hi, 

I am interested in Scouter and I want to test it. I noticed that you said in the website there are agents only for Tomcat, and Linux. So is it possible to use Scouter on other application servers like WebLogic? 
If not, is it possible to make some further development to be able to use it? Will this be difficult?
Thanks in advance for your help.

Vladimir

**Comment by gunlee01** [comment]
Hi. Xiaomutoun.

The java agent of scouter is for java application.
So you can use it for any java applications.
Scouter has some special features for a tomcat application server and we almost test scouter on a tomcat server but it does not mean it works on only a tomcat.

**Comment by xiaomutoun123** [comment]
Hi @gunlee01,

Thanks for your answer, I am running an application on WebLogic, and now I can use Scouter on my system.
