### ISSUE TITLE
xLog 상의 socket 의 의미

### ISSUE THREAD

**Issue by yealbae** [scouter-project/scouter#187]
여기서 질문을 해도 되는건지 모르겠네요.

시스템 지연이 발생하는 프로그램의 xLog를 보았더니 
-    [000021] 11:30:35.986    5,719      0  socket: 192.168.11.203:1521 0 ms
  쿼리 중간중간에 위와 같은 로그들이 많이 남아 있네요..
  혹시 어떤 의미 인지 아시는분 있으신지요??

**Comment by bill23-kim** [comment]
Socket connect 가 발생했다는 프로파일링입니다. 물론 DB Connection 도 포함됩니다.

**Comment by gunlee01** [comment]
쿼리마다 계속 나오면  datasource pooling이 되지 않는다는거니 확인해보세요
