### ISSUE TITLE
hook_method_patterns/hook_method_ignore_prefixes 문의

### ISSUE THREAD

**Issue by jungsookim** [scouter-project/scouter#188]
클래스는 특정 패키지 하위 모든 클래스를 프로파일링 하고
메소드는 이런 이름의 메소드를 프로파일링에서 제외 하고 싶은데
get/set/decrypt/encrypt/hashCode 
잘 안되서요

hook_method_patterns=com.healthcare._._
hook_method_ignore_prefixes=get, set. decrypt. encrypt. hashCode

더 셋팅해줘야 할 옵션이 있을까요?

**Comment by 23king** [comment]
set 다음 , 이게 아니라 . 이게 붙어있는데 오타인가요??

**Comment by gunlee01** [comment]
,로 나열하면 되지않나요?
