### ISSUE TITLE
profile에서 cpu time에 대해서 

### ISSUE THREAD

**Issue by 23king** [scouter-project/scouter#189]
![image](https://cloud.githubusercontent.com/assets/5696581/16071169/d5a18be6-3314-11e6-8d76-f75960fa17b5.png)
위 이미지에서보면 cpu time이 계속 0 이였다 end of transaction에서 92라는 수치를 볼수 있습니다.
각 메소드에서 cpu time이 0이 나오는게 맞는건가요??

**Comment by gunlee01** [comment]
step 단위에 나오는 cpu는 해당 java method의 사용 cpu 입니다. 마지막에 나온것이 프로파일 시작점이후 해당 서비스의 cpu 사용량입니다. ㅍ로파일에 기록된 method만 각각의 cpu가 측정됩니다.

**Comment by 23king** [comment]
![image](https://cloud.githubusercontent.com/assets/5696581/16071861/ad47913c-3318-11e6-9771-c1a2b5f3de6e.png)
지금 현재 이렇게 나오고 있는데 말씀하신대로면 프로파일이 기록된 method에는 cpu가 측정되야 된다는 말씀이시죠??

**Comment by gunlee01** [comment]
항상 cpu time이 마지막에만 몰아서 나온다면 profile_thread_cputime_enabled=true 옵션을 안 준 걸수도 있겠네요.
확인해 보세요.

**Comment by 23king** [comment]
앗 그런 옵션이 있었군요 옵션을 줬더니 아래와 같이 나옵니다.
![image](https://cloud.githubusercontent.com/assets/5696581/16073182/b328a5c6-331f-11e6-8e56-55d0fa2151e1.png)
그런데 CPU Time이 마이너스로 나오는건 왜그런것일까요?? 오늘 너무 많이 물어보네요 죄송합니다 ^^;; 낼 모레 설명회라 ㅠㅠ

**Comment by gunlee01** [comment]
더 확인해 봐야 알겠지만 마이너스는 버그일 것 같네요. 일단 무시하시기 바랍니다. 쿼리를 출력하는데 sqlmap의 이름까지 적어주는 부분하고 뭔가 꼬인듯 하네요.
