### ISSUE TITLE
jboss Object Type 이 Tomcat 으로 인식되서 Xlog 가 잡히지 않습니다.

### ISSUE THREAD

**Issue by soo3004** [scouter-project/scouter#190]
구글링중에 

domain.xml 에 scouter 클래스 참조를 위해 <system-properties> 쪽에 <property name="jboss.modules.system.pkgs" value="scouter"/> 를 추가합니다.
나머지는 host.xml 에 모니터링하기 위한 노드 의 <server> 밑에 <jvm-options> 에 -javaagent:~~~~, -Dobj_name=~~~~, -Dscouter.config=~~~~~ 정도 걸어주시면 될것 같아요.

하면 된다는데, 해도 안되네요

**Comment by soo3004** [comment]
Jboss 버전은 Wildfly 8.2 Final 입니다.

**Comment by gunlee01** [comment]
Wildfly 8.2인 경우 tomcat으로 인식되나요? 정보 감사합니다.
tomcat으로 인식되는 경우 collector 메뉴에서 tomcat > XLog 를 선택하면 XLog는 나와야 합니다.
그리고 Jboss 인 경우 module package에 scouter를 추가하여야 합니다.
아래 링크를 한번 참고해 보시기 바랍니다.
https://groups.google.com/forum/#!topic/scouter-project/427QXV88Zds

**Comment by soo3004** [comment]
해결은 했는데 url 처럼
bootClass.put("org/jboss/as/server/Bootstrap", CounterConstants.JBOSS);
추가했는데 안되서

톰캣으로 되있는것들을 다 주석처리 하였습니다.
//bootClass.put("????", CounterConstants.TOMCAT);

**Comment by soo3004** [comment]
Wildfly 8.2 도 jboss 로 대부분 인식 되는데, 특정 놈들만 Tomcat 으로 인식합니다.
