### ISSUE TITLE
Not able to gather profiling data 

### ISSUE THREAD

**Issue by sattishv** [scouter-project/scouter#191]
Hi team,

Would like to know how to gather profiling data through scouter agent. Whenever i click a object from XLog List i could see a message "No xlog profile collected". Noticed a configuration file with contents hook_method_patterns=org.mybatis.jpetstore._._ but not sure where i should place this conf file. Could you please confirm whether it should be placed in agent or server installation folders.

Thanks
Sattish.

**Comment by gunlee01** [comment]
Scouter profiles SQLs only by default. but if you configure the option hook_method_patterns, you may see profiles. In case you can't find the configure file, just try it on your scouter client.
 Object View > Context menu on a tomcat > configure

![image](https://cloud.githubusercontent.com/assets/6788732/16323913/bf039646-39e9-11e6-8d61-c2987bca85b1.png)


And check your scouter client version. on unmatching a client release version with a scouter server version, it' possible not to show profiles.

**Comment by bill23-kim** [comment]
default configure file location : ${scouter.home}/agent.java/conf/scouter.conf
you can set file location by inserting -Dscouter.config when starting server

**Comment by sattishv** [comment]
Hi team,

Thanks for the immediate response. I was able to instrument the classes by
enabling few flags in scouter.conf. But still i am not able to see any
ranges to analyze the stack through Stack Frequency Analyzer .
Have enabled the flag sfa_dump_enabled=true but still don see any list in
stack to analyze.Please suggest

Thanks
Sattish.


.

On Thu, Jun 23, 2016 at 5:54 PM, bill23 <notifications@github.com> wrote:

> default configure file location :
> ${scouter.home}/agent.java/conf/scouter.conf
> you can set file location by inserting -Dscouter.config when starting
> server
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scouter-project/scouter/issues/191#issuecomment-228228335>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHGqmXLLzjN1Zx7LeXCcH-TPyPYmIAwhks5qOyq8gaJpZM4I9VWU>
> .
>



-- 
with regards,

Sattish
9940080070

**Comment by KwonMunsoo** [comment]
Good morning? sattishv.
When you select the Stack Frequency Analyer (SFA) in Tomcat object pop-up menu it has Analyzer menu.
Select this menu and then select the date you collect the stack.
If the Time list shown, collecting a stack has succeded.
Select some of the time list, then calling the SFA may be an error message("no stack") appears if the SFA configuration problems.

SFA analyzes only the thread that is currently running. So there is a configuration that helps to identify the execution thread.
If you select the configuration modification icon of the SFA, you can modify the configuration to identify the executing thread.

-----  the configuration to identify the executing thread -----
  <workingThread status="java.lang.Thread.State:">
	<list>javax.servlet.http.HttpServlet.service(</list>	
	<list>javax.servlet.jsp.jspPage</list>
	<list>javax.servlet.jsp.HttpJspPage</list>
	<list>java.util.concurrent.FutureTask.run</list>		
	<list>TransactionTemplate.execute</list>
	<list>org.springframework.context.support.AbstractApplicationContext.refresh</list>
  </workingThread>
---------------------------------------------------------------

Please add the portion of the contents of the stack can identify that it is a stack running here.
then save a configuration.

And if the java agent is collecting stack of tomcat, yellow dots appear on the Tomcat object right.

I hope this was helpful to you.

**Comment by sattishv** [comment]
Hi Kwon,

Thanks a lot for the response. Still i couldn't any entries in the time
list under stack frequency analyzer . The list is empty. Have attached all
the configurations used for our server.
Could you please review and let us know y we can't see any thread stack
entry,

obj_name=userstage9332
trace_interservice_enabled=true
hook_method_patterns=com.ebay.*
profile_thread_cputime_enabled=true
profile_summary_mode_enabled=true
trace_webserver_enabled=true
trace_rs_leak_enabled=true
profile_socket_open_fullstack_enabled=true
profile_http_parameter_enabled=true
profile_connection_open_enabled=true
profile_connection_open_fullstack_enabled=true
trace_response_gxid_enabled=true
sfa_dump_interval_ms=1000
sfa_dump_enabled=true

Thanks
Sattish.

On Fri, Jun 24, 2016 at 5:40 PM, Kwon Munsoo <notifications@github.com>
wrote:

> Good morning? sattishv.
> When you select the Stack Frequency Analyer (SFA) in Tomcat object pop-up
> menu it has Analyzer menu.
> Select this menu and then select the date you collect the stack.
> If the Time list shown, collecting a stack has succeded.
> Select some of the time list, then calling the SFA may be an error
> message("no stack") appears if the SFA configuration problems.
>
> SFA analyzes only the thread that is currently running. So there is a
> configuration that helps to identify the execution thread.
> If you select the configuration modification icon of the SFA, you can
> modify the configuration to identify the executing thread.
>
> ----- the configuration to identify the executing thread -----
>
> javax.servlet.http.HttpServlet.service( 
> javax.servlet.jsp.jspPage
> javax.servlet.jsp.HttpJspPage
> java.util.concurrent.FutureTask.run 
> TransactionTemplate.execute
> org.springframework.context.support.AbstractApplicationContext.refresh
>
> Please add the portion of the contents of the stack can identify that it
> is a stack running here.
> then save a configuration.
>
> And if the java agent is collecting stack of tomcat, yellow dots appear on
> the Tomcat object right.
>
> I hope this was helpful to you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scouter-project/scouter/issues/191#issuecomment-228496538>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHGqmbcNFaTcY45WM1Zw-ftLAnLpSjjLks5qPHkMgaJpZM4I9VWU>
> .
>



-- 
with regards,

Sattish
9940080070

**Comment by KwonMunsoo** [comment]
hi sattishv
Configuration is correct. It seems likely that related to the Java version. Please inform to me the vendor and the version of Java you are using. I'll check.

have nice day~^^

**Comment by sattishv** [comment]
Hi Kwon,

I have 1.8.0 update 91 for scouter client version and 1.7.0_45 for the agent version.
Let me know for further details

Thanks
Sattish.

**Comment by winnettjohnston** [comment]
I am getting the same issue. No items in the stack analyzer. But i am getting XLog messages. I am thinking it may be a permissions issue? When the option is selected to Turn On Analyzer for 5min, where are these being saved?

I don't see any error messages in the logs, but seems like it could be the issue.

FYI:
Love the application!

-winn

**Comment by gunlee01** [comment]
@sattishv Did you try use SFA menu? not the option sfa_dump_enabled true.
Please try set the option 'sfa_dump_enabled=false' and turn on SFA manually.

![image](https://cloud.githubusercontent.com/assets/6788732/16682399/74bb2886-4535-11e6-81c4-15207bc933d3.png)
wait for a while and select the menu SFA > analysis
then date picker may be poped up.
you should choose **correct date** for dump lists.

And select all lists for analysis.
![image](https://cloud.githubusercontent.com/assets/6788732/16682428/a12d2c34-4535-11e6-9e7a-2c894cc99bc1.png)

![image](https://cloud.githubusercontent.com/assets/6788732/16682454/bc7fa0ac-4535-11e6-870b-00ff0d378e90.png)

**Comment by gunlee01** [comment]
@winnettjohnston I think you may find dump files on the directory [server-location]/database/[data]/[hostname]/[objectname]

**Comment by winnettjohnston** [comment]
I was able to get this to work. Not sure what changed, but when i went to demo the tool to my team, i tried it again and it worked.

Also to note, we would loose the xlog polling after a heavy day of load testing. A restart fixed it.

**Comment by sattishv** [comment]
Hi Lee,

Thanks for the inputs. Tried again by setting the sfa_dump_enabled=false
but still it shows the window as blank no entries to select. On the server
side when i checked the folder structure
[server-location]/database/[data]/[hostname]/[objectname]
we could see the stack.dat file been created.

Sattish.

On Fri, Jul 8, 2016 at 2:14 AM, Gunhee Lee <notifications@github.com> wrote:

> @winnettjohnston <https://github.com/winnettjohnston> I think you may
> find dump files on the directory
> [server-location]/database/[data]/[hostname]/[objectname]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scouter-project/scouter/issues/191#issuecomment-231313096>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHGqmdJ5OazaZqnO_8ce8iG7Jw-h3Pb3ks5qThTYgaJpZM4I9VWU>
> .
>



-- 
with regards,

Sattish
9940080070
