### ISSUE TITLE
Is there an option in scouter to plot graphs using jmx measures

### ISSUE THREAD

**Issue by sattishv** [scouter-project/scouter#194]
Hi team,

Do we have an option in scouter to monitor resources via JMX. We would like to measure metrics like Used Young Gen Space(YGC), YGC count , JIT Code Cache usage F. Usage of file stream read and write etc. Can this measures be configured if so how could we accomplish

Thanks
Sattish

**Comment by bill23-kim** [comment]
Hi @sattishv ,

Unfortunately, not be able to add such metrics by setting. If necessary, you need to add the source directly in [counter task pakage](https://github.com/scouter-project/scouter/tree/master/scouter.agent.java/src/scouter/agent/counter/task)

Thank you for your interest.
