### ISSUE TITLE
Mac client Fatal error log 

### ISSUE THREAD

**Issue by cowboy93** [scouter-project/scouter#196]
안녕하세요 ?

그 동안 Mac 용 클라이언트가 오동작 하는 부분 및 죽어버리는 부분이 있었는데요.
오늘  로그를 뒤지다보니 좀 실마리가 있는 것 같아 공유 드립니다. 

결론 부터 말씀드리면 
첫번째 로그는 Active speed control 하는 부분의 paint에서 문제가 발생
두번째/세번째 로그는 EQ Common View 의 paint  에서 문제가 발생했습니다. 

확인 부탁 드립니다. 

첫번째 로그 
Stack: [0x00007fff5f400000,0x00007fff5fc00000],  sp=0x00007fff5fbf5008,  free space=8148k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [CoreGraphics+0x9c109]  decode_byte_8bpc_3+0x171
C  [CoreGraphics+0x3e3e2]  decode_data+0x3f1e
C  [CoreGraphics+0x39a58]  img_decode_read+0x17a
C  [CoreGraphics+0x397d7]  img_colormatch_read+0x16b
C  [CoreGraphics+0x3771f]  img_data_lock+0x2294
C  [CoreGraphics+0x345af]  CGSImageDataLock+0x97
C  [libRIP.A.dylib+0xf1d4]  ripc_AcquireImage+0x3cc
C  [libRIP.A.dylib+0xdc7e]  ripc_DrawImage+0x3f3
C  [CoreGraphics+0x33b31]  CGContextDrawImageWithOptions+0x23b
C  [CoreGraphics+0x338da]  CGContextDrawImage+0x33
C  [AppKit+0x1b7752]  __74-[NSImageRep drawInRect:fromRect:operation:fraction:respectFlipped:hints:]_block_invoke+0x305
C  [AppKit+0x1b7256]  -[NSImageRep drawInRect:fromRect:operation:fraction:respectFlipped:hints:]+0x456
C  [AppKit+0x1bf199]  __71-[NSImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]_block_invoke1045+0x45f
C  [AppKit+0x17ebb0]  -[NSImage _usingBestRepresentationForRect:context:hints:body:]+0xa4
C  [AppKit+0x1bec58]  -[NSImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]+0x845
C  [AppKit+0x1bf6e0]  -[NSImage drawInRect:fromRect:operation:fraction:]+0x61
C  [libswt-pi-cocoa-4530.jnilib+0x12693]  Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend__JJLorg_eclipse_swt_internal_cocoa_NSRect_2Lorg_eclipse_swt_internal_cocoa_NSRect_2JD+0x112
J 4017  org.eclipse.swt.internal.cocoa.OS.objc_msgSend(JJLorg/eclipse/swt/internal/cocoa/NSRect;Lorg/eclipse/swt/internal/cocoa/NSRect;JD)J (0 bytes) @ 0x00000001095487bc [0x00000001095486c0+0xfc]
J 12550 C2 **scouter.client.views.ActiveSpeedCommonView$1.paintControl(Lorg/eclipse/swt/events/PaintEvent;)V (37 bytes) @ 0x0000000109dbfdbc [0x0000000109dbf6c0+0x6fc]**
J 12497 C2 org.eclipse.swt.widgets.TypedListener.handleEvent(Lorg/eclipse/swt/widgets/Event;)V (1291 bytes) @ 0x000000010aa49b9c [0x000000010aa48dc0+0xddc]
J 6598 C2 org.eclipse.swt.widgets.EventTable.sendEvent(Lorg/eclipse/swt/widgets/Event;)V (532 bytes) @ 0x00000001095e840c [0x00000001095e8240+0x1cc]

두번째 로그
Stack: [0x00007fff5f400000,0x00007fff5fc00000],  sp=0x00007fff5fbf4808,  free space=8146k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [CoreGraphics+0x9c395]  decode_byte_8bpc_3+0x171
C  [CoreGraphics+0x3e4fd]  decode_data+0x3f1e
C  [CoreGraphics+0x39b70]  img_decode_read+0x17a
C  [CoreGraphics+0x398ef]  img_colormatch_read+0x16b
C  [CoreGraphics+0x37837]  img_data_lock+0x2294
C  [CoreGraphics+0x346c7]  CGSImageDataLock+0x97
C  [libRIP.A.dylib+0xf1d4]  ripc_AcquireImage+0x3cc
C  [libRIP.A.dylib+0xdc7e]  ripc_DrawImage+0x3f3
C  [CoreGraphics+0x33c48]  CGContextDrawImageWithOptions+0x23b
C  [CoreGraphics+0x339f1]  CGContextDrawImage+0x33
C  [AppKit+0x1b7856]  __74-[NSImageRep drawInRect:fromRect:operation:fraction:respectFlipped:hints:]_block_invoke+0x305
C  [AppKit+0x1b735a]  -[NSImageRep drawInRect:fromRect:operation:fraction:respectFlipped:hints:]+0x456
C  [AppKit+0x1bf29d]  __71-[NSImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]_block_invoke1045+0x45f
C  [AppKit+0x17ecb4]  -[NSImage _usingBestRepresentationForRect:context:hints:body:]+0xa4
C  [AppKit+0x1bed5c]  -[NSImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]+0x845
C  [AppKit+0x1bf7e4]  -[NSImage drawInRect:fromRect:operation:fraction:]+0x61
C  [libswt-pi-cocoa-4530.jnilib+0x12693]  Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend__JJLorg_eclipse_swt_internal_cocoa_NSRect_2Lorg_eclipse_swt_internal_cocoa_NSRect_2JD+0x112
J 4119  org.eclipse.swt.internal.cocoa.OS.objc_msgSend(JJLorg/eclipse/swt/internal/cocoa/NSRect;Lorg/eclipse/swt/internal/cocoa/NSRect;JD)J (0 bytes) @ 0x0000000109102e7c [0x0000000109102d80+0xfc]
J 11244 C2 scouter.client.views.EQCommonView$1.paintControl(Lorg/eclipse/swt/events/PaintEvent;)V (50 bytes) @ 0x000000010a24b85c [0x000000010a24ab80+0xcdc]

세번째 로그 
Stack: [0x00007fff5f400000,0x00007fff5fc00000],  sp=0x00007fff5fbf73a8,  free space=8156k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libobjc.A.dylib+0x14dd]  objc_msgSend+0x1d
C  [AppKit+0x17ebb0]  -[NSImage _usingBestRepresentationForRect:context:hints:body:]+0xa4
C  [AppKit+0x1bec58]  -[NSImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]+0x845
C  [AppKit+0x1bf6e0]  -[NSImage drawInRect:fromRect:operation:fraction:]+0x61
C  [libswt-pi-cocoa-4530.jnilib+0x12693]  Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend__JJLorg_eclipse_swt_internal_cocoa_NSRect_2Lorg_eclipse_swt_internal_cocoa_NSRect_2JD+0x112
J 4045  org.eclipse.swt.internal.cocoa.OS.objc_msgSend(JJLorg/eclipse/swt/internal/cocoa/NSRect;Lorg/eclipse/swt/internal/cocoa/NSRect;JD)J (0 bytes) @ 0x0000000108b07afc [0x0000000108b07a00+0xfc]
J 7599 C2 scouter.client.views.EQCommonView$1.paintControl(Lorg/eclipse/swt/events/PaintEvent;)V (50 bytes) @ 0x0000000108de9724 [0x0000000108de8ec0+0x864]
J 6126 C2 org.eclipse.swt.widgets.TypedListener.handleEvent(Lorg/eclipse/swt/widgets/Event;)V (1291 bytes) @ 0x000000010966cd20 [0x000000010966c100+0xc20]

**Comment by bill23-kim** [comment]
로그 공유 감사드립니다. libswt-pi-cocoa-4530.jnilib 내에 native 크래시 같은데 원인 찾는게 쉽지 않네요.. (주간에 맥도 못쓰고...) Exception Type 은 EXC_BAD_ACCESS 인가요? 시간이 오래 지나면 발생하는 건가요? (leak 같은 느낌인지) 어플리케이션에서 수정할수 없는 영역이면 우회 할 수 밖에 없을것 같습니다. mac 에서는 redraw interval 을 좀 늘린다든지...

**Comment by cowboy93** [comment]
[hs_err.tar.gz](https://github.com/scouter-project/scouter/files/342978/hs_err.tar.gz)

네 ~ 제가 갖고 있는 모든 scouter 의 Fatal error log 원본 업로드해 드립니다. 
어차피 scouter stack 위에 있는 것들은 우리가 손 댈 수 없는 부분이고,
Paint 를 처리하는 부분이 가장 큰 문제로 보입니다. 

제가 매일 화면을 띄워 놓고 일하는데,
해당 로그는 정확한 주기에 의한 것은 아닙니다. 어쩔때는 10분만에 죽고, 
어쩔때는 안죽고 그러네요. 

제가 보내드린 파일들이 많으니 거기서 뭔가 공통점이 나오지 않을까 생각됩니다. 

제 감 으로는 equalizer의 animation 처리 부분이 문제 ? 
인것 같기도 합니다. 

XLog에 데이터가 적게 보이도록 ignore 개수를 처리했는데도 죽는것은 비슷했어요. 

빨리 이 문제가 잡히면 좋겠어요 ~~~

**Comment by cowboy93** [comment]
추가로 해당 로그는 
`scouter.client.app/Contents/MacOS`
에 쌓입니다. ^^;

**Comment by bill23-kim** [comment]
의심되는 부분이 있어 수정하여 dev 브랜치에 반영했는데 빌드/적용 가능하시면 돌려보시고 진행 상황좀 공유해주세요 ,..^^;;;

**Comment by cowboy93** [comment]
앗~ 
저는 release 본 다운로드해서 사용합니닷 ~~~ !! 
^^;

예전엔 환경이 구축되었었는데 지금은 안되어 있어요.

**Comment by bill23-kim** [comment]
그라믄 제가 테스트 해봐야겟네요~ 알겠습니다~

**Comment by cowboy93** [comment]
그거 맹그시면 여기에 올려주세요. 
담주 월요일 아침부터 돌려서 테스트 해 보겠슴돠 ~

PS: 현재 perspective 설정은 어떻게 복제 할까요 ? 
버전 올리면 다 날라갈텐데요.

**Comment by bill23-kim** [comment]
[scouter-20160702.tar.gz](https://github.com/scouter-project/scouter/releases/download/untagged-0fb5587f5e05f5789756/scouter-20160702.tar.gz)
[scouter.client.product-macosx.cocoa.x86_64.tar.gz](https://github.com/scouter-project/scouter/releases/download/untagged-0fb5587f5e05f5789756/scouter.client.product-macosx.cocoa.x86_64.tar.gz)

클라이언트 로컬 설정들은 scouter.client.app/Contents/MacOS/workspace 디렉토리를 같은 위치에 복사해 놓으시면 복사가 됩니다.

기존에 어떤 버전을 쓰시는지 몰라서 agent 랑 server 도 같이 올려놨습니다. 시간되실때 업데이트 하셔서 이걸로 한번 봐주세요~

**Comment by cowboy93** [comment]
흠 ~ 해당 링크에 제가 권한이 없나봐요. 
cowboy93 지메일로 부탁 드립니다. ^^; 
클라이언트만 보내주시면 될 듯 해요.

**Comment by bill23-kim** [comment]
보냈습니다~ 확인 부탁드려요

**Comment by cowboy93** [comment]
넵 기존 데이터 백업 정상동작까지 잘 되네요. 
혹시라도 죽으면 정보 공유해 드릴께요.

**Comment by cowboy93** [comment]
오늘 하루종일 안죽었습니다. 
계속 지켜보다가 이슈 있으면 말씀드릴께요. ^^;

**Comment by bill23-kim** [comment]
네 감사합니다~ 이정도면 됐다 싶으실때 클로즈 처리 부탁드려요 ㅋㅋ

**Comment by cowboy93** [comment]
네네
다음주초까지 안죽으면 처리할께요.

**Comment by cowboy93** [comment]
1주일간 단 한번도 안죽었습니다. 
Master 로 머지/릴리즈 부탁드려용 ~~~ 
즐거운 주말 되십쇼 ~

**Comment by bill23-kim** [comment]
감사합니다. @cowboy93 님 덕분에 묵혀놓은 이슈가 해결된거 같네요.
