### ISSUE TITLE
DBCP 모니터링 질문입니다.

### ISSUE THREAD

**Issue by thdghgns** [scouter-project/scouter#197]
spring에 DB는 오라클을 쓰고, DBCP는 HikariDataSource 를 사용하고 있습니다.
scouter java agent 설치하고 collect server랑 연결해보니 tomcat이 나오고 8080 port랑 datasource 는 나옵니다.
근데 datasource의 상태 체크가 안나오네요.. 혹시 Tomcat 기본 DBCP 사용하는 경우가 아니라면 agent 에 profile을 더 추가해야 하나요?? 추가해야 한다면 어떤 프로파일 인가요?

**Comment by bill23-kim** [comment]
datasource의 상태 체크라 하심은 used / max 값 말씀하시는건가요? 그거라면 tomcat에서 등록한 jmx 값을 가져와서 보여주는 거기 때문에 다른 dbcp 에 대해서는 보이지 않습니다. 그게 아니고 xlog profile 에 DBC OPEN 프로파일링을 하시는 거라면 hook_connection_open_patterns 설정에 getConnection 메소드를 찾아 등록해주시면 됩니다.

**Comment by thdghgns** [comment]
@bill23-kim 답변 감사합니다.~ 네 맞아요. DBCP에 active/idle 커낵션 수를 보고 싶어서요... 그럼 JMX MBean 등록하면 되는데, class 가 톰캣 datasource만 인식하나요?? hikari 써보니까 JMX로 열어볼때 datasource 클래스가 다르게 되더라구요..

**Comment by bill23-kim** [comment]
톰캣의 BasicDataSource 사용했을 때 등록되는 MBean 값을 보여주고 있습니다.  HikariDataSource 에 대해서는 테스트 해보지 못했습니다. https://github.com/scouter-project/scouter/blob/master/scouter.agent.java/src/scouter/agent/counter/task/TomcatJMXPerf.java 를 참고하셔서 hikari 도 가능하도록 @thdghgns  님께서 contribution 해주셨으면 좋겠네요 ^^;;
