### ISSUE TITLE
서버 & mysql 분리 설치 문의

### ISSUE THREAD

**Issue by defresh** [scouter-project/scouter#198]
안녕하세요.

서버 관리상 서버와 db 를 분리하고 싶은데요~
현재는 임베디드형태로 db가 동작 하는 것 같은데
별도로 설치 및 설정이 가능할까요?

문서에 혹시 제가 놓친게 있다면 알려주시면 감사하겠습니다^^;

감사합니다.

**Comment by bill23-kim** [comment]
Scouter 서버는 별도의 dbms 를 쓰지 않고 자체 file 디비를 사용하고 있고 서버 자체가 db 역할을 하고 있습니다. 서버와 db를 분리한다는 질문이 잘 이해가 안가네요~;;

**Comment by defresh** [comment]
@bill23-kim 님

아 제가 잘못 이해 한 것 같습니다.
(제가 어디서 보고 mysql 을 쓰고 있는걸로 생각했는지^^;)

그럼 file db 와 서버는 같은 장비 안에 있는 형태여야겠군요.
원했던건 데이터 저장소 1대와 콜렉터를 여러대를 사용 하고 싶었던거였거든요^^;

도움 감사드립니다~
