### ISSUE TITLE
How is the deployment on Windows?

### ISSUE THREAD

**Issue by xiaomutoun** [scouter-project/scouter#199]
Hi, 
I want to use Scouter in Windows environment. I found that there is only Linux version for Scouter-server. And it's said that we need to install Apache Ant and Eclipse to deploy it in Windows. Do we really have to do that? Is there a more simple way to use it in Windows? Thanks in advance for your help.

**Comment by gunlee01** [comment]
Hi. @xiaomutoun 
Of course not. You just download scouter release version and just decompress it.
And you can simply start the scouter collector server by executing startup.bat

refer to [the guide](https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Setup.md) and you just use *.bat file not *.sh file for windows.

Gun Lee.

**Comment by xiaomutoun** [comment]
Hi @gunlee01 
Thanks for your answer, I found the right file and succeeded in installing Scouter. 
I've installed the Scouter client, server and agent, and I've added the Java option to my application. In fact, I am using WebLogic server, and in the setEnv file, I added "-javaagent" and "-Dscouter.config". 
When I start the server and Scouter, Scouter can detect the agent and display the server, but there are no data collected and the graphs display nothing. Do you know the possible cause of it? What possible measures could I take to make it works? Thanks in advance for your help.

**Comment by bill23-kim** [comment]
Add -Dobj_type=tomcat with -javaagent.

**Comment by xiaomutoun** [comment]
Hi, 
Thanks all for your help. 
Facing this problem, I've searched the options in Scouter and changed what I can. And fortunately, it works at last. I don't know which option matters. Maybe in the Window-->Preference, I chose the default host to 'windows' and the default javaee to 'java'.
