### ISSUE TITLE
agent v0.4.14의 버그 같습니다.

### ISSUE THREAD

**Issue by 23king** [scouter-project/scouter#207]
V0.4.11에서는 이상없는데 V0.4.14에서는 profile의 time이 이상하게 나오네요
![2016-07-14 2 30 23](https://cloud.githubusercontent.com/assets/5696581/16828958/b5da5244-49cf-11e6-99c4-f9e4a69d1221.png)

**Comment by bill23-kim** [comment]
클라이언트에서 mlliseconds 포맷을 잘못쓴 버그가 있었습니다.  이것만 수정된 버전은 빠르게 릴리즈 할 예정입니다. 버그리포트 감사합니다.!

**Comment by gunlee01** [comment]
fixed at v0.4.16 Release
