### ISSUE TITLE
텔레그램 API를 이용한 알림 메시지 받기

### ISSUE THREAD

**Issue by sohwaje** [scouter-project/scouter#211]
이슈 : 텔레그램 봇으로 Alert이 오지 않습니다. 

 https://github.com/scouter-project/scouter-plugin-server-alert-telegram 여기를 참조하여 아래와 같이 작업했습니다.
1. 소스 파일 다운로드(scouter-plugin-server-alert-telegram-20160424)
   https://github.com/scouter-project/scouter-plugin-server-alert-telegram/releases
2. 압축 해제 
3. scouter/server/conf/scouter.conf 설정
   # Scouter Server IP Address (Default : 127.0.0.1)
   net_collector_ip=10.0.1.212
# Scouter Server Port (Default : 6100)

net_collector_udp_port=6100
net_collector_tcp_port=6100
# Scouter Name(Default : tomcat1)

obj_name=tomcat
trace_interservice_enabled=true
# Log Directory

log_dir=/home/scouter/logs
# Alert to Telegram

ext_plugin_telegram_send_alert=true
ext_plugin_telegram_debug=true
ext_plugin_telegram_level=0
ext_plugin_telegram_bot_token=**My BOT TOKEN**(보안상 삭제)
ext_plugin_telegram_chat_id=**My BOT CHAT_ID**(보안상 삭제)
1. build.xml 실행. <----build.xml을 실행하라는 말이 무슨 말인지 몰라서, 구글에서 찾아보니
   ant를 이용해서 build하는 게 나와 있어서 아래처럼 했습니다.
   ./ant -buildfile build.xml
   Buildfile: /home/scripts/scouter/scouter-plugin-server-alert-telegram-20160424/build.xml
   packaging:
   BUILD SUCCESSFUL
   Total time: 0 seconds
2. out 디렉토리의 lib들(commons-codec-1.9.jar  commons-logging-1.2.jar  gson-2.6.2.jar  httpclient-4.5.2.jar  httpcore-4.4.4.jar  scouter-plugin-server-alert-telegram.jar)을 scouter/server/lib 복사 완료.
3. 텔레그램 봇 API를 이용해서 URL로 테스트 메시지 보내기 성공.
4. Scouter Server restart
5. Scouter 톰캣 연동.(톰캣을 내렸다 올리면 scouter.agent도 함께 내려갔다 올라가는 구조)
6. Alert 테스트는 에이전트를 stop/start 시켜보고, 톰캣에 부하를 주는 식으로 해봤습니다만, Alert이 오지 않았습니다. 제가 한 것은 여기까지입니다.

조언 부탁드립니다. 수고하십시오.

**Comment by nices96** [comment]
스카우터 서버 로그 내용 확인 부탁드립니다.

**Comment by sohwaje** [comment]
말씀하신 Server 로그입니다.

  ____                  _            
 / ___|  ___ ___  _   _| |_ ___ _ __ 
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |   
 |____/ \___\___/ \__,_|\__\___|_|                                      
 Open Source S/W Performance Monitoring  
 Scouter version 0.4.15 20160713
 
20160718 18:45:11 Load Account Group File
20160718 18:45:11 Load Account File
20160718 18:45:11 Load Account Group File
20160718 18:45:11 udp listen 0.0.0.0:6100
20160718 18:45:11       udp_host=0.0.0.0
20160718 18:45:11       udp_port=6100
20160718 18:45:11       udp_buffer=65535
20160718 18:45:11       udp_so_rcvbuf=4194304
20160718 18:45:11 Load Account File
20160718 18:45:11 [S104] New OBJECT  objType=tomcat objHash=x1uq7925 objName=/gaudium/tomcat1 addr=127.0.0.1 0.4.15 20160713 alive 2016-07-18 18:45:11.464
20160718 18:45:11 [S104] New OBJECT  objType=reqproc objHash=x1pdvml4 objName=/gaudium/tomcat1/ajp-bio-8009 alive 2016-07-18 18:45:11.476
20160718 18:45:11 [S104] New OBJECT  objType=reqproc objHash=z16sp785 objName=/gaudium/tomcat1/http-bio-8080 alive 2016-07-18 18:45:11.476
20160718 18:45:11       tcp_port=6100
20160718 18:45:11       cp_agent_so_timeout=60000
20160718 18:45:11       cp_client_so_timeout=8000
20160718 18:45:16 PLUG-IN : scouter.server.plugin.IAlert loaded #x1uh6lg3
20160718 18:45:16 PLUG-IN : scouter.server.plugin.ICounter loaded #xgr0vqe
20160718 18:45:16 PLUG-IN : scouter.server.plugin.IObject loaded #x904hfm
20160718 18:45:16 PLUG-IN : scouter.server.plugin.IXLog loaded #x1qdp8q7
20160718 18:45:16 PLUG-IN : scouter.server.plugin.IXLog loaded #x3c7e2h
20160718 18:45:16 PLUG-IN : scouter.server.plugin.IXLogProfile loaded #x9f3od5
20160718 18:45:16 PLUG-IN : scouter.server.plugin.ISummary loaded #x1dvqsuc
20160718 18:45:41 [S501] Cannot find a tcp agent for /gaudium/tomcat1/ajp-bio-8009
20160718 18:45:41 [S501] Cannot find a tcp agent for /gaudium/tomcat1/http-bio-8080

덧붙이자면, "Cannot find a tcp agent for"라고 나오긴하는데 스카우터 클라이언트에서는 첨부한 그림에서 보이듯이 잘 확인이 되고 있습니다. 
![scouter](https://cloud.githubusercontent.com/assets/19942049/16911232/43b3d89c-4d18-11e6-9d33-e7cb4ad67b9b.JPG)

**Comment by nices96** [comment]
Plugin이 정상적으로 로딩된 경우 아래와 같이 TelegramPlugin이 로딩되는 것을 확인할 수 있습니다.

20160718 19:39:35 Scouter Server Version 0.4.14 20160706
  ____                  _
 / ___|  ___ ___  _   _| |_ ___ _ __
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |
 |____/ \___\___/ \__,_|\__\___|_|
 Open Source S/W Performance Monitoring
 Scouter version 0.4.14 20160706

20160718 19:39:35 Load Account Group File
20160718 19:39:35 Load Account File
20160718 19:39:35 Load Account Group File
20160718 19:39:35 udp listen 0.0.0.0:6100
20160718 19:39:35       udp_host=0.0.0.0
20160718 19:39:35       udp_port=6100
20160718 19:39:35       udp_buffer=65535
20160718 19:39:35       udp_so_rcvbuf=4194304
20160718 19:39:35 Load Account File
20160718 19:39:35       tcp_port=6100
20160718 19:39:35       cp_agent_so_timeout=60000
20160718 19:39:35       cp_client_so_timeout=8000
**20160718 19:39:35 [BuiltInPlugin]scouter.plugin.server.alert.telegram.TelegramPlugin=>object
20160718 19:39:35 [BuiltInPlugin]scouter.plugin.server.alert.telegram.TelegramPlugin=>alert**
20160718 19:39:40 PLUG-IN : scouter.server.plugin.IAlert loaded #xvljhfj
20160718 19:39:40 PLUG-IN : scouter.server.plugin.ICounter loaded #x7jj6ne
20160718 19:39:40 PLUG-IN : scouter.server.plugin.IObject loaded #x1hpmctg
20160718 19:39:40 PLUG-IN : scouter.server.plugin.IXLog loaded #x1n5qrj6
20160718 19:39:40 PLUG-IN : scouter.server.plugin.IXLog loaded #x121aisf
20160718 19:39:40 PLUG-IN : scouter.server.plugin.IXLogProfile loaded #x1arfc72
20160718 19:39:40 PLUG-IN : scouter.server.plugin.ISummary loaded #x1i1a6v4

추측컨데, 빌드하신 Telegram Plugin 패키징 파일에 문제가 있지 않나 싶습니다. 아래 링크에 있는 파일을 다운로드하여 사용해 보시기 바랍니다.

http://bit.ly/29IXmbo

**Comment by sohwaje** [comment]
고맙습니다. 링크하여 주신 파일을 사용했더니 alert이 잘 들어오고 있습니다. 혹시 보내주신 url의 원래 주소를 알 수 있을까요?

**Comment by nices96** [comment]
https://s3.ap-northeast-2.amazonaws.com/scouter-osci/telegram.zip 입니다. 단, 저 경로가 언제까지 유효할지는 장담드릴 수 없습니다. 조만간 telegram-plugin 프로젝트에 릴리즈 파일로 업로드 하겠습니다.

**Comment by sohwaje** [comment]
답변 감사드립니다.
