### ISSUE TITLE
Active Service 리스트 수정한게 안없어지네요

### ISSUE THREAD

**Issue by hotkaho** [scouter-project/scouter#213]
PC에서 모니터링 화면 열어두면
Active service EQ 리스트에 서버 리스트가 보이는데
이전에 A=>B 라는 이름으로 서비스 네임을 변경하면
A는 없어지는게 아니고 그 리스트에 중간에 선그어진 글씨로 보이고
그아래로 B 라는 익네임이 추가되더라고요
A라는 닉네임을 없에 버리고 싶은데 방법을 [모르겠습니다.]

**Comment by bill23-kim** [comment]
Objects 뷰 드롭다운 메뉴에서 Remove Inactive 를 눌러보세요.

**Comment by hotkaho** [comment]
찾기 엄청 힘들었네요 ~~  감사합니다 ^^
