### ISSUE TITLE
Is Scouter able to store a session?

### ISSUE THREAD

**Issue by xiaomutoun** [scouter-project/scouter#214]
Hi, 
I am using Scouter and I have a question. 
Right now, I can use Scouter to monitor the real time data. But I want to know if it is able to store a session of a short running period monitoring. So that we can look at the data later on when we want to analyze them.

**Comment by bill23-kim** [comment]
Not the overall recording function. However, because it is saved for each data, a chart, it is possible to load the previous data. 
thank you.

**Comment by gunlee01** [comment]
Try to use the load past menus.

![image](https://cloud.githubusercontent.com/assets/6788732/17352138/235b9c34-596f-11e6-99a1-98175e627d67.png)

Also you may see old objects although the object does not currently live.
 - the menu is **object daily list** 

![image](https://cloud.githubusercontent.com/assets/6788732/17352051/ad01fe66-596e-11e6-868b-80ab970965a8.png)
