### ISSUE TITLE
Webapp의 'SCOUTER' Cookie가 무엇인가요?

### ISSUE THREAD

**Issue by traeper** [scouter-project/scouter#216]
안녕하세요.

스카우터 요긴하게 이용하고 있습니다~.

개발중인 Webapp을 모니터링하기 위해 톰캣 실행 파라미터에 Scouter를 추가했는데요.

Webapp에 'SCOUTER' 쿠키가 남습니다.

이 쿠키가 남는 이유, 용도가 무엇인지 알 수 있을까요?

**Comment by bill23-kim** [comment]
유니크한 사용자 판별을 위해 랜덤 더미 숫자를 만들어 쿠키를 사용하고 있습니다. 사용자 판별 방식을 바꾸시려면 trace_user_mode  설정을 바꾸시면 됩니다.

**Comment by traeper** [comment]
넵. 답변 감사합니다. 
본 이슈는 종료처리 하겠습니다.
