### ISSUE TITLE
Tracking custom Server side ids in Scouter

### ISSUE THREAD

**Issue by vivekjuneja** [scouter-project/scouter#217]
Hi,

I am in the process of using Scouter for APM needs in our project. We have multiple Java web services that interact over a transaction. We use a unique correlation id that is generated for any request across all the services. This correlation id is used to track requests across services and identify the problems. Currently, we log this correlation id, and use log aggregation to track the id. 

We would like to check if we could use Scouter to track this correlation id. This means, we could look at all correlation ids that have been generated so far in the application across all the services. On a peak scale, we could see how many correlation ids have been generated, and further, can diagnose issues that occur for a particular correlation id. 

Is this something that is possible through the use of Scouter Plugins ?

Ideally, an APM should be able to track custom metrics from any application. Let me know if I am missing something.

**Comment by gunlee01** [comment]
I think a script plugin of java agent can helps you.
You can add a correlation id to profiles as well as XLog columns for extension like login and desc.
 If the HTTP header include the id, use the http-service plugin and if it is created first on some method, use the capture plugin.
[script plugin readme page](https://github.com/scouter-project/scouter/blob/master/scouter.agent.java/plugin/readme.md)

example >
```java
$ctx.login(correlationId); // add the id to XLog login column
$ctx.desc(correlationId); // add the id to XLog desc column
$ctx.profile(correlationId); // add the id to profile 
```

please refer to the page 44-50 on the below link.
[scouter in practice](http://www.slideshare.net/gunheelee923519/opensource-apm-scouter-in-practice)

**Comment by gunlee01** [comment]
Also Scouter has the concepts like a colleration id aleady, we call it gxid.
If you've never tried to use it, set the option ```trace_interservice_enabled=true```

![image](https://cloud.githubusercontent.com/assets/6788732/17385989/4d9e9e58-5a21-11e6-8da3-44492fd9b2a6.png)

![image](https://cloud.githubusercontent.com/assets/6788732/17386005/6c91f2e2-5a21-11e6-97eb-1e2b39decf8c.png)

**Comment by vivekjuneja** [comment]
Thanks @gunlee01 for your response. It was helpful.
