### ISSUE TITLE
collector server가 다수일 때 서버를 변경하면 unknown 발생하는 현상

### ISSUE THREAD

**Issue by handhwang** [scouter-project/scouter#218]
모니터링할 서버의 네트워크가 분리되어 있어서 collector server를 여러개 셋업하여 사용하고 싶은데, scouter client에서 어느 한쪽 네트워크의 collector를 선택하여 모니터링하다 다른 collector의 수집된 정보를 보고 싶으면 어떻게 해야 하나요?
한쪽 collector에서 모니터링 중 다른 collector를 선택하게 되면 차트가 unknown이 되어 버리는 현상이 있습니다.

또 한가지 질문을 드리자면 데스크탑에서 client를 재시작했을 때, 이전에 수집된 정보는 남아있지 않은데
client 실행과 관계 없이 history를 서버에 보관할 수 있는 방법은 없나요?

**Comment by bill23-kim** [comment]
Collector 가 바뀌면 퍼스펙티브를 한번 reset 해주셔야 됩니다. 오른쪽 위에 Service 퍼스펙티브 우클릭 하시고 Reset 해주시면 unknown 뷰가 정신차립니다.

클라이언트 실행과 관계없이 scouter server 는 데이터를 파일로 계속 저장하고 있습니다. 지난 데이터는 각 차트에서 우클릭을 통해 불러 올 수 있습니다.

**Comment by handhwang** [comment]
첫번째 문제는 해결되었습니다. 감사합니다.

server에 별다른 설정을 안해도 데이터가 계속 저장된다는거죠?
Scouter server는 어제부터 계속 돌고 있었고, 오늘 오전 Scouter client를 실행시킨 다음 Heap Used - Tomcat에서 우클릭 후 Today All을 선택하면 Client를 실행시킨 시점부터 지금까지의 그래프만 보이거든요. 즉, 오늘 0시부터 Client 실행 시점까지의 그래프는 나오지 않네요.

**Comment by gunlee01** [comment]
issue #220 과 비슷한 케이스가 아닌가요?

**Comment by handhwang** [comment]
제 착각으로 잘못 판단한 것 같습니다. 다시 확인해보니 잘되는 것 같아요. 감사합니다!
