### ISSUE TITLE
최근 일주일간의 데이터 출력 방법 

### ISSUE THREAD

**Issue by ez2sugul** [scouter-project/scouter#220]
scouter 클라이언트에서 일주일간 혹은 한달간의 데이터를 볼 수 있도록 기능이 있는 것으로 알고 있는데요
이 기능이 동작하지 않는 것 같습니다
scouter가 설치되어 있는 서버에 보면 
database 디렉토리가 있고 여기에 날짜별 디렉토리가 있는데요 
항상 오늘 날짜의 디렉토리만 있습니다
어떻게 설정하면 과거 데이터도 볼 수 있을까요?

database/
    00000000/
        text
    20160805/
        alert
        counter
        object
        sum
        visit
        visit_hourly
        xlog

**Comment by gunlee01** [comment]
일정 수준 이상으로 디스크를 사용하면 데이터를 삭제 합니다.
디스크 용량을 먼저 점검해 보세요.
해당 옵션은 mgr_purge_disk_usage_pct 로 조정할 수 있습니다.
기본값은 80 입니다. (80% 초과시 삭제)

**Comment by ez2sugul** [comment]
감사합니다 해결 됐습니다!!
