### ISSUE TITLE
quick start 구동시 클라이언트 인증 에러.

### ISSUE THREAD

**Issue by devarchi33** [scouter-project/scouter#222]
안녕하세요 :)

scouter 프로젝트 quick-start 를 따라가고 있습니다.

1. scouter-server 를 구동하고
<img width="516" alt="2016-08-11 12 17 03" src="https://cloud.githubusercontent.com/assets/7742818/17577908/09ba822c-5fbe-11e6-8d16-a41472cf047e.png">

2. scouter-host 를 구동하고
<img width="503" alt="2016-08-11 12 17 11" src="https://cloud.githubusercontent.com/assets/7742818/17577910/145cc53c-5fbe-11e6-87a9-4c8cbfc3e49f.png">

3. demo 용 tomcat 을 구동하고
<img width="1688" alt="2016-08-11 12 17 29" src="https://cloud.githubusercontent.com/assets/7742818/17577916/1b9f1c8c-5fbe-11e6-9498-738ca1350620.png">

4. 클라이언트 앱을 구동하였습니다.
<img width="595" alt="2016-08-11 12 18 12" src="https://cloud.githubusercontent.com/assets/7742818/17577919/1ff5d08c-5fbe-11e6-9266-cb84720c7b4e.png">

특별한 log 가 안보이는걸로 보아 정상 작동된것 같은데
클라이언트 앱에서  admin/admin 으로 인증했을 때 fail 이 되네요 ㅠㅠ

무슨 문제가 있는지 감이 안잡혀서 도움요청 드립니다.

**Comment by devarchi33** [comment]
시도 1.
혹시나 하고 demo-env1/scouter/server/conf/account.xml 의 admin password(hash 로 보이는..) 를 직접 세팅 해 봤는데도 실패한 상황입니다.

**Comment by gunlee01** [comment]
v0.4.10 버전 클라이언트를 다운로드 받아서 해보세요.
암호화 방식이 변경되었습니다.

**Comment by devarchi33** [comment]
v0.4.10 버전 클라이언트 다운로드 이후 정상 작동합니다 
감사합니다 :)
