### ISSUE TITLE
CPU 차트에 그래프가 그려지지 않는 현상

### ISSUE THREAD

**Issue by sohwaje** [scouter-project/scouter#224]
안녕하세요, Scouter 클라이언트에서 CPU 차트의 그래프가 나타나지 않아 문의드립니다.

혹시 따로 설정해줘야 할 것이 있는지요.
![cpu](https://cloud.githubusercontent.com/assets/19942049/17608448/80e05382-6067-11e6-85fc-c19af79030f7.JPG)

**Comment by gunlee01** [comment]
Host Agent를 설치하고 기동했는지 확인해 보세요.
그리고 Linux CPU 창이 열려져 있는데 Host가 Linux가 아니라면 거기에 맞는 차트를 열어야 합니다.
Preference에서 기본 윈도우에서 열릴 오브젝트 Type을 설정할 수 있습니다.
(기본 설정값은 Tomcat과 Linux입니다.)
만약 Windows Host라면 위 설정을 Windows로 바꾼후 Perspective를 Reset 하면 될겁니다.
혹은 오브젝트뷰의 수집서버를 선택해 우클릭하고 해당 Object Type의 CPU 차트를 열수도 있습니다.
