### ISSUE TITLE
Login dialog input text were freeze in macOS Sierra

### ISSUE THREAD

**Issue by bill23-kim** [scouter-project/scouter#234]
Login dialog input text were freeze in macOS Sierra

**Comment by kukgini** [comment]
I'm using macOS Sierra (10.12.1) now. but, It is not happen to me. Is there specific steps / environment which is reproducible ?

**Comment by bill23-kim** [comment]
When just launch client, it is happened. It's strange not to happen. Did you try to run it as a release version?

**Comment by kukgini** [comment]
Do you mean as a packaged application (scouter.client.app)? or run on release branch? 
I only try it on dev branch (ff73a57e0d2e92e693e11362bd9284bdd28209b8), Both debug mode on eclipse IDE and on packaged application (scouter.client.app).

If you can reproduce, can you share your heapdump ?

**Comment by bill23-kim** [comment]
this issue seem to be fixed at [this commit](https://github.com/scouter-project/scouter/commit/1adb52c38f97e7582112823284a65433ba6965ae). But not yet released.
