### ISSUE TITLE
Javaagent Plugin doesn't work properly

### ISSUE THREAD

**Issue by MyungChi** [scouter-project/scouter#235]
agent.java/plugin 디렉토리에 git 에 있는 sample 소스를 복사해서 httpservice.plug 를 작성해서 넣고 테스트를 해보았는데 제대로 동작을 하지 않는것 같아요. 아래와 같이 넣어주면  뭐든 찍혀야 하지 않나요 ? 그런데 아무것도 보이지 않아요.

[소스]
[start]
// void start(WrContext $ctx, WrRequest $req, WrResponse $res)
$ctx.profile("### This is test ###");

[end]
// void end(WrContext $ctx, WrRequest $req, WrResponse $res)

[reject]
// boolean reject(WrContext $ctx, WrRequest $req, WrResponse $res)
return false;

기본적인 기능으로도 충분히 쓸만합니다만...  

scouter 많이 응원합니다~

**Comment by bill23-kim** [comment]
0.4.18 로 적용해봣는데 캡쳐화면 처럼 start 로그가 찍히네요~  ~/scouter/agent.java/plugin/httpservice.plug 파일이었습니다.

![2016-10-07 9 39 31](https://cloud.githubusercontent.com/assets/10736555/19175506/254cc51e-8c72-11e6-892e-a4cf8aa00744.png)

**Comment by MyungChi** [comment]
Version 문제 였던듯 합니다. latest version(0.4.18) 으로 테스트 해보니 정상적으로 동작합니다. 감사합니다.
