### ISSUE TITLE
Fail to connect to a collector server using 'admin' account after installation.

### ISSUE THREAD

**Issue by hide1202** [scouter-project/scouter#236]
I tried to connect to a collector server after installation.
But i failed to connect to a collector server using `admin` / `admin`.

If i modified the admin account in `conf/account.xml`, i could connect to a collector server.

**As-Is**

``` xml
<Account 
    id="admin" 
    pass="ae3cf413ccbc56ce97c4dd88d14296c31d6ffc81eabbb04437434cc3221ec47c" 
    group="admin">
```

**To-Be**
- Refenrece to Demo version

``` xml
<Account 
    id="admin" 
    pass="21232f297a57a5a743894a0e4a801fc3" 
    group="admin">
```

Was the initial password is changed?

**Comment by bill23-kim** [comment]
Your collector maybe in the old version. Please try changing to it 0.4.13 and later versions.

**Comment by hide1202** [comment]
@bill23-kim My collector is 0.4.18 version.

**Comment by bill23-kim** [comment]
Ah... Please check your client too.

**Comment by hide1202** [comment]
@bill23-kim Ah... i tried to connect using a client in Demo, this client version is lower 0.4.13. 
Sorry, and thank you.
