### ISSUE TITLE
Do we have an option to correlate the response times with GC pause time in scouter

### ISSUE THREAD

**Issue by sattishv** [scouter-project/scouter#238]
Hi team,

During one of our test engagement we found huge latency in a send request . We did profiling but not sure whether the code path shown in scouter client is the correct because its shows a framework code not the application one, before confirming on the methods involved we would like to know whether any long pause happened at the same time.Is their a way in scouter where we correlate the response times with GC events.

Thanks
Sattish

**Comment by gunlee01** [comment]
No. However you can guess that some external factors have effected the response time via XLog chart and another charts.
