### ISSUE TITLE
Not able to correlate the transactions between the jvms

### ISSUE THREAD

**Issue by sattishv** [scouter-project/scouter#239]
Hi team,

We have enabled trace_interservice_enabled=true on both jvms but still the calls arent traced between them. I could see only the calls measured in Xlog for JVM 1 and nothing has been measured in JVM 2
Is their anything i need to configure

Conf used:
# Scouter Server IP Address (Default : 127.0.0.1)

net_collector_ip=10.244.40.43
# Scouter Server Port (Default : 6100)

net_collector_udp_port=6100
net_collector_tcp_port=6100
# Scouter Name(Default : tomcat1)

obj_name=webservice1serv
trace_interservice_enabled=true
profile_thread_cputime_enabled=true
profile_summary_mode_enabled=false
trace_webserver_enabled=true
trace_rs_leak_enabled=true
profile_socket_open_fullstack_enabled=true
profile_http_parameter_enabled=true
profile_connection_open_enabled=true
profile_connection_open_fullstack_enabled=true
trace_response_gxid_enabled=false
sfa_dump_enabled=false
hook_method_patterns=com.ppal._._,org.apache._._,org.springframework._._,com.ebay._._

xlog_sampling_enabled=false

Thanks
Sattish.

**Comment by gunlee01** [comment]
It does not support every HTTP clients, only support clients library below currently.

sun/net/www/protocol/http/HttpURLConnection
org/apache/commons/httpclient/HttpClient
org/apache/http/impl/client/InternalHttpClient
sun/net/www/http/HttpClient
org/apache/http/impl/client/AbstractHttpClient
com/sap/mw/jco/JCO$Client
io/reactivex/netty/protocol/http/client/HttpClientImpl
