### ISSUE TITLE
latest client version for mac os sierra doesn't work.

### ISSUE THREAD

**Issue by MyungChi** [scouter-project/scouter#246]
I downloaded 0.4.20 and 0.4.19 version client. 
It still doesn't work properly on Mac OS Sierra. 
After launch App, I can't input anything for authentication such as server address, password and etc as below.
![image](https://cloud.githubusercontent.com/assets/15916804/19500598/ae4d0174-95d9-11e6-9401-bc41c49316de.png)

**Comment by gunlee01** [comment]
It is known issue. Thank you.

**Comment by bill23-kim** [comment]
Fixed but not released. Please wait for next release.
