### ISSUE TITLE
임계치 설정에 의한 자동 스레드 덤프 기능 추가

### ISSUE THREAD

**Issue by nices96** [scouter-project/scouter#249]
CPU에 대한 임계치를 설정하고 Java Agent의 process CPU가 임계치를 초과하여 일정 시간 지속될 경우 3~5초 간격으로 3~5회 스레드 덤프를 수행하도록 Java Agent에 요청하는 서버 플러그인을 구현하였습니다. 

기존 소스 변경을 하지 않으려고 서버 플러그인으로 구현을 하였으나, 네트워크 상태 및 서버 상태에 따라 해당 에이전트의 카운터 정보(CPU 등) 수집에 문제가 발생할 가능성도 있어 scouter.agent.java의 기본 기능으로 포함시키는 것이 어떤지 문의 드립니다.

**Comment by gunlee01** [comment]
java agent 기능으로 검토해봄이 좋을 듯 합니다.

**Comment by gunlee01** [comment]
This issue was moved to #271
