### ISSUE TITLE
agent.host 관련 문의

### ISSUE THREAD

**Issue by soyacg** [scouter-project/scouter#250]
Scouter 관련해서 문의 드립니다.

회사 서버에 agent.host 설정 후  회사 PC에 서버를 설치했을 때는 정보(Disk usage, Top 등)가 잘 나타났는데요.

AWS 서버에 Scouter 설치후 회사서버 agent.host 설정을 다시 했는데 정보가 나타나지 않네요.

관련해서 별도 설정이 필요한 부분이 있을까요?  CPU나 Memory 부분은 잘 나옵니다.

**Comment by bill23-kim** [comment]
정확히 질문이 잘 이해가 되지 않는데 Performance Counter 는 잘 나오는데 Object Request 메뉴들이 안나온다는 말씀이신가요? 그렇다면 네트워크 환경 문제일 확률이 있습니다.  Host Agent -> Collector 로 TCP 6100포트 접근이 가능한지 확인해주세요.
