### ISSUE TITLE
geoip 정보를 이용해서 접속 국가별 Summary 정보를 보려면 ?

### ISSUE THREAD

**Issue by go2basic** [scouter-project/scouter#253]
안녕하세요.
geoip 정보를 이용해서 접속 국가 파악이 가능하던데요.
국가별 일 접속 Summary 정보를 count 하고 싶은데 어떻게 할수 있을까요?

**Comment by gunlee01** [comment]
국가별 summary 기능은 없습니다.
국가별 summary 수집이 필요하다면 Collector 서버 확장 plugin 개발을 통해 가능합니다. (xlog plugin)

**Comment by bill23-kim** [comment]
부연설명 드리면 XLog의 국가정보가 들어간 이후 플러그인은  xlogdb.plug 입니다. https://github.com/scouter-project/scouter/tree/master/scouter.server/plugin

**Comment by gunlee01** [comment]
위 안내와 같이 현재 버전에서는 스크립트 방식의 xlogdb plugin 을 사용하면 됩니다.
다만 xlogdb 는 built in 플러그인 방식이 제공되지 않으며 이후 버전에서는 xlog plugin에서도 지역정보가 포함이 되니 built in plugin 방식에서도 지역 정보 접근이 가능합니다.
