### ISSUE TITLE
프로젝트 단위의 .gitignore 파일 등록

### ISSUE THREAD

**Issue by kukgini** [scouter-project/scouter#255]
eclipse 에 git plugin 이 설치된 상태로 프로젝트들을 import 하면 각 프로젝트마다 .gitignore 가 생성됩니다. 
기본적으로는 class  파일 컴파일을 위해 생성하는 디렉토리인 /bin/ 을 버전관리 대상에서 제외하기 위함입니다.
하지만, 버전 관리가 각 프로젝트 단위보다 상위 레벨인 workspace 단위로 관리되고 있기 때문에 의미가 없어 보이긴 합니다.

이 커밋(1adb52c38f97e7582112823284a65433ba6965ae)을 보면 scouter.client 프로젝트에는 이미 이렇게 생성된 .gitignore 파일이 관리 대상에 포함 되었던데 그렇다면 나머지 프로젝트들에서 생긴 .gitignore 파일도 대상에 포함 시켜도 될까요?

이것이 의도한 바가 아니고 관리 대상에 포함시키기 원치 않는다면 최상의 레벨의 .gitignore 파일에서 제외 대상에 .gitignore 를 포함시키면 됩니다.

**Comment by gunlee01** [comment]
모듈별 분리가 될 수도 있으니 모듈별로 .gitignore를 포함해도 될 것 같습니다.

**Comment by kukgini** [comment]
모듈별 .gitignore 파일을 PullRequests 하였습니다. 검토해 주세요.
