### ISSUE TITLE
xlog 에서 쿼리가 두 개로 보여짐

### ISSUE THREAD

**Issue by haks1999** [scouter-project/scouter#259]
다음의 환경에서 xlog 에 쿼리가 두 번씩 보입니다.
원래 한 번만 보였는데 
드라이버를 mysql drive 에서 maria drive 로 바꾼 다음부터 그렇습니다 ㅜㅜ 
고쳐주세요

db : 10.1.14-MariaDB
jdbc drive : mariadb-java-client 1.5.4
datasource : org.apache.tomcat.dbcp.dbcp2

**Comment by Cocopapa** [comment]
안녕하세요. 언제나 scouter를 잘 쓰고 있는 개발자입니다.
저도 비슷한 케이스입니다만, 
이번에 AWS RDS의 Aurora를 쓰게 되어 
드라이버를 Mariadb Connect/J로 바꾸게 되었습니다. 
그 이후로 PreparedStatement실행 직후에 Scouter에서 에러가 납니다. 
에러 메시지는 다음과 같습니다. 

> org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]:-1] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoSuchFieldError: _param_] with root cause

AP환경은 
Spring Boot 1.3.2, 
CentOS 7, 
java 1.8
입니다. 

어떻게 하면 좋을지 고수 여러분들의 도움 요청합니다!
수고하세요!

**Comment by gunlee01** [comment]
resolved
https://github.com/scouter-project/scouter/releases/tag/v0.6.0
