### ISSUE TITLE
Xlog data shows Service as blank / null

### ISSUE THREAD

**Issue by vivekjuneja** [scouter-project/scouter#260]
Hi,

We have encountered an issue wherein the `Service` lists as blank in the Xlog list. Also, if we check the details of the Xlog entry, it shows that the `service = null`.

This is not happening for all trace calls. We found this is happening especially for inbound requests to our services through L4 load balancer. 

Any tips to help debug this situation ? I have added screenshots to help clarify my case. 

Thanks!

> Xlog List:

<img width="736" alt="scouter_snapshot_1" src="https://cloud.githubusercontent.com/assets/122003/20206797/44013eb6-a826-11e6-9a14-57c35db03168.png">

> Xlog detail:

<img width="274" alt="scouter_snapshot_2" src="https://cloud.githubusercontent.com/assets/122003/20206798/44054240-a826-11e6-9370-8fd16cf60bd5.png">

**Comment by gunlee01** [comment]
I tried to reproduce the situation but failed.
I will try to debug if that happens to me someday.

**Comment by gunlee01** [comment]
resolved something in v1.7.0
