### ISSUE TITLE
원도우에서 클라이언트 자동 로그인 사용시 바로 종료

### ISSUE THREAD

**Issue by KwonMunsoo** [scouter-project/scouter#261]
윈도우에서 자동 로그인 기능을 사용하여 클라이언트를 실행하면 본 화면이 나타나지 않고
바로 종료되는 오류가 있습니다.

**Comment by bill23-kim** [comment]
수정했습니다~ 다음 버전에 반영할께요~

**Comment by gunlee01** [comment]
resolved - v0.4.22
https://github.com/scouter-project/scouter/releases/tag/v0.4.22
