### ISSUE TITLE
scouter client memory leak

### ISSUE THREAD

**Issue by cowboy93** [scouter-project/scouter#266]
맥용 클라이언트를 사용할 때 
맥을 닫고 퇴근하고, 
출근해서 열어보면 메모리 부족 현상이 발생하고 있습니다. 

<img width="479" alt="at 6 46 13" src="https://cloud.githubusercontent.com/assets/175918/20287958/2e0b415c-ab13-11e6-86b2-a54bcb495c21.png">

확인 부탁 드리며,
추가로 확인이 필요한 내용이 있으면 말씀해 주세요. 

감사합니다.

**Comment by bill23-kim** [comment]
클라이언트 버전과 가능하면 열려있던 뷰 목록을 알 수 있을까요? 캡쳐화면도 좋구요.

**Comment by cowboy93** [comment]
![image](https://cloud.githubusercontent.com/assets/175918/20289094/1d19bce0-ab1b-11e6-8a45-929bf59094d3.png)

이미지 참고 하셔요. 

version 은 0.4.18.20160815 
네요.

**Comment by bill23-kim** [comment]
저는 재현이 잘안되네요.. 자주 발생하시나요? 가능하시면 메모리릭 조짐이 보일때 힙덤프 한번 빵 떠주시면 매우 감사할것 같습니다..

**Comment by cowboy93** [comment]
힙 메모리가 32 GB 라 ㅠ ㅠ

2016-11-18 19:14 GMT+09:00 bill23 <notifications@github.com>:

**Comment by gunlee01** [comment]
fail on reissue
