### ISSUE TITLE
Mac OS Client error

### ISSUE THREAD

**Issue by 23king** [scouter-project/scouter#274]
OS Sierra 10.12.1 에서
Scouter Client 0.4.21버젼설치하여 실행할때
최초 한번은 잘 실행되나 client를 죽이고 다시 실행시 
실행되다 바로 죽어버리는 오류가 있습니다

제가 아니라 회사 동료인데 저는 맥이 맛이가서 Sierra 로 업글이 안되서 디버깅이 힘드네요 ㅠㅠ

확인 부탁드립니다.

**Comment by bill23-kim** [comment]
혹시 Auto Login 체크하셨었나요? 0.4.21 에 그 버그가 있어 수정된 상태이고 아직 릴리즈는 안되었습니다.
그게 맞다면 /tmp/scouter 디렉토리를 지우신후 다시 시작하시고 이번 버전에 Auto Login 은 사용하지 말아주세요~

**Comment by 23king** [comment]
아 넵 
그 버그가 맞네요 다음 릴리즈가 나오면 바로 적용하겠습니다.
