### ISSUE TITLE
Mysql - AffectedRows 숫자 이상

### ISSUE THREAD

**Issue by bill23-kim** [scouter-project/scouter#277]
MySQL 에 아래와 같은 sql 사용하는 프로파일링에 <Affected Rows : 4>  로 나오고 있음.

Insert into ~ on duplicate key update ~ 

키 중복시 업데이트 이기 때문에 Affected Rows : 1 이여야 할것 같음.

mysql-connector-java : 5.1.34
mybatis : 3.2.8

**Comment by gunlee01** [comment]
실제로는 2가 정상입니다.
