### ISSUE TITLE
XYGraph need to be upgraded

### ISSUE THREAD

**Issue by kukgini** [scouter-project/scouter#281]
I think xygraph project is end of development now and merged into nebula project.
If you don't mind, I can upgrade to nebula version of xygraph.
Please consider this.

내가 보기에 xygraph 는 개발이 중단되었으며 nebula 프로젝트로 이관된 것 같습니다.
괜챦다면 내가 nebula 에 있는 최신의 xygraph 로 업그레이드 할 수 있습니다.
고려해 주세요.

**Comment by bill23-kim** [comment]
xygraph 가 수정되거나 커스터마이징 된 부분이 있어서 그 부분에 대한 고려가 되어야 새로운 버전으로 업그레이드 될 수 있을것 같습니다.
