### ISSUE TITLE
objName 다른 이름이 들어와서 groupping 이 안됩니다.

### ISSUE THREAD

**Issue by leetg83** [scouter-project/scouter#283]
안녕하세요 이번에 scouter를 써보려고 하는 유저입니다. 

scouter.conf에 이런식으로 obj_name 을 api1으로 줬는데도 server log에는 이렇게 찍힙니다.
-------------------------------------
# Scouter Name(Default : tomcat1)
obj_name=api1
trace_interservice_enabled=true
server log----------------------------------------
20170105 06:27:18 [S104] New OBJECT  objType=tomcat objHash=z1kdolc objName=/api1.biz.ap2a.dev/api1 addr=**.**.**.** 0.4.18 20160815 alive 2017-01-05 06:27:18.921
----------------------------------------
그래서 client에서 볼때도 이렇게 host 하위로 안가고 다른 디렉토리로 변하는거같은데요.
![image](https://cloud.githubusercontent.com/assets/24931081/21671173/f16ff612-d35c-11e6-9f41-9ef7e65565f3.png)

 혹시 다른설정이 있을까요?
was는 톰캣을 쓰고 있으며 catalina.sh에 단순히 아래 두줄 추가했습니다.
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/ppmt/scouter/agent.java/scouter.agent.jar"
JAVA_OPTS="$JAVA_OPTS -Dscouter.config=/ppmt/scouter/agent.java/scouter.conf"

답변 기다리겠습니다.

**Comment by bill23-kim** [comment]
톰캣의 Full objName 은 /호스트이름/설정이름  입니다. 
host agent 의 scouter.conf 에 obj_name 을 안주시거나, java agent 의 설정에  obj_host_name=api1 을 추가해주세요.

**Comment by leetg83** [comment]
java agent에 obj_host_name을 추가하여 해결했습니다.
빠른 답변  정말 감사드립니다 ~ ^^
