### ISSUE TITLE
client is silently shutdown on staring with auto-login (v0.4.21 Release) - Windows ver.

### ISSUE THREAD

**Issue by gunlee01** [scouter-project/scouter#284]
client is silently shutdown on staring with auto-login.
When I start scouter's client the first time with autologin option, it's ok but after close the client and restart it, then nothing occurs after splash image of scouter.
(It's only when with auto-login option)

**Comment by bill23-kim** [comment]
[Issue 261](https://github.com/scouter-project/scouter/issues/261) The same issue. It will be fixed next version.

**Comment by gunlee01** [comment]
resolved - v0.4.22
https://github.com/scouter-project/scouter/releases/tag/v0.4.22
