### ISSUE TITLE
비동기 지원여부 문의

### ISSUE THREAD

**Issue by boojongmin** [scouter-project/scouter#289]
비동기 처리를 위해 사용한 Futre 호출 관련 메서드들이 조회가 되지 않아서 문의 드립니다.

**Comment by gunlee01** [comment]
Async Servlet은 아직 지원하지 않으며 곧 지원 예정입니다.
(Spring MVC에서 Future 계열을 리턴하는 Controller 등)

단 사용자가 Thread를 생성하는 방식은 자동으로 추적은 불가능하며
agent plugin과 option 적용을 통해서 가능합니다.

**Comment by gunlee01** [comment]
v0.5.1 에서 일부 적용되었습니다.
