### ISSUE TITLE
When  I start scouter client on OS X, I got an error

### ISSUE THREAD

**Issue by MechanicKim** [scouter-project/scouter#292]
![2017-02-13 1 39 01](https://cloud.githubusercontent.com/assets/12149783/22871203/f4e4df66-f1f1-11e6-9508-66681f26c39e.png)

How can I solve this?

**Comment by bill23-kim** [comment]
1. open  scouter.client.app/Contents/Eclipse/scouter.ini

```
-data
/tmp/scouter
```

2. add these two lines before _-vmargs_

3. restart client

**Comment by MechanicKim** [comment]
So useful solution! Thank you! :-)
