### ISSUE TITLE
jeus6 + tibero6 에서 xlog상 sql이 출력되지 않습니다.

### ISSUE THREAD

**Issue by nice98jh** [scouter-project/scouter#293]
대부분 정상적으로 동작하는데
xlog list에서 선택하고 들어가보면
쿼리만 출력되지 않습니다.
tibero db는 지원하지 않나요?

**Comment by gunlee01** [comment]
현재 지원하지 않습니다.
향후 버전에서 지원을 위하여 사용하시는 tibero jdbc driver 파일을 보내주시면 감사하겠습니다.

2017-02-15 12:10 GMT+09:00 nice98jh <notifications@github.com>:

**Comment by kranian** [comment]
안녕하세요? 우연히 Tibero와 연관된 업무를 하다보니 제가 알고 있는 내용을 공유해 드리고 싶어 
여기에 기록 합니다. 

짐 현재 scouter java agent는 ASM으로 SQL이 실 수행되는 클래스를 조작 하면 프로파일링을 할수 있다는것을 알수 있는데 이와 관련한 Tibero JDBC 드라이버 클래스 정보를 제공해 드립니다. 

실제 확인을 위해 첨부 파일에 tibero jdbc 드라이버를 첨부 합니다. 

1. Dirver 구현체 : com.tmax.tibero.jdbc.TBDriver
2. PrepareStatement 구현체 : com.tmax.tibero.jdbc.TbPreparedStatement
2. Statement 구현체 : com.tmax.tibero.jdbc.TbStatement
4. ResultSet 구현체: com.tmax.tibero.jdbc.TbResultSet

[tibero5-jdbc.zip](https://github.com/scouter-project/scouter/files/949741/tibero5-jdbc.zip)

**Comment by gunlee01** [comment]
@kranian 
이후 버전에 tibero 지원 feature 개발시 참고하도록 하겠습니다.
감사합니다.

**Comment by gunlee01** [comment]
supported on v1.7.0

**Comment by chadolkr** [comment]
아래와 같이 설정했는데 SQL Profile이 되지 않습니다.

--------------------
scouter.conf 
--------------------
#hook jdbc class
hook_jdbc_pstmt_classes=com.tmax.tibero.jdbc.TbPreparedStatement
hook_jdbc_stmt_classes=com.tmax.tibero.jdbc.TbStatement

--------------------
Log
--------------------
20170615 11:22:29 [SCOUTER] Version 1.7.0.1 2017-06-09 11:31 GMT
20170615 11:23:24 [A106] jdbc pstmt found: com/tmax/tibero/jdbc/TbPreparedStatement

**Comment by gaiajeon** [comment]
SQL Profile은 TbPreparedStatement나 TbStatement를 사용하여 프로파일링 합니다.

어플리케이션 코드에서 TbPreparedStatement를 사용하고 있고 로그상에서  TbPreparedStatement를 찾았다는 메시지가 나오는 경우에는 SQL Profile을 위한 후킹코드가 성공적으로 삽입이 되었을겁니다.

로그가 정상적으로 표시된 상황인 경우 

1. scouter 서버와  scouter java agent, scouter 클라이언트 버젼이 동일한지 확인하시고

2. 웹요청을 받아들이는 쓰레드와 Query를 수행되는 쓰레드가 동일한 쓰레드인지 확인을 하셔야 할것 같습니다. Tibero는 아니지만 어제 facebook scouter 사용자 모임에서 Oracle Query 수집 관련해서 비슷한 케이스가 있었습니다.  참고 하시기 바랍니다.

**Comment by gunlee01** [comment]
@chadolkr  
혹시 사용하시는 어플리케이션과 동일한 방식으로 쿼리 1~2개를 호출하는 어플리케이션을 spring boot 등으로 간단하게 만들어서 테스트하시고, 쿼리가 안나온다면 그 어플리케이션을 제공해 주실 수 있으신가요? 
사용하시는 방식이 다를 수 있어 동일하게 재연해서 테스트해보면 해결에 도움이 될 듯 합니다.

**Comment by chadolkr** [comment]
tibero5-jdbc.jar 드라이버는 SQL 프로파일링 잘되지만,
tibero6-jdbc.jar 은 되지 않습니다.

확인해보니  tibero6-jdbc.jar 에서는 com/tmax/tibero/jdbc/TbResultSetBase 이 없습니다.
아래와 같이 변경해야 합니다.
JDBCResultSetASM.java
 target.add("com/tmax/tibero/jdbc/TbResultSetBase");
 -> target.add("com/tmax/tibero/jdbc/TbResultSet");

**Comment by gunlee01** [comment]
It applied to the develop branch. Thanks.
