### ISSUE TITLE
Demo down

### ISSUE THREAD

**Issue by Pablohn26** [scouter-project/scouter#296]
It seems [this live demo](https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Live-Demo.md) is down. 

There is no ping and connection to "demo.scouterapm.com:6100". It seems filtered.

**Comment by gunlee01** [comment]
Hi Pablo.
I'm so sorry for that.
It's been downed now because of the version concurrency problem.
I'll fix it soon.

Thank you

2017-02-28 20:34 GMT+09:00 Pablo Hinojosa <notifications@github.com>:

**Comment by gunlee01** [comment]
now working on
