### ISSUE TITLE
Java Agent not collecting the data

### ISSUE THREAD

**Issue by mathi201028** [scouter-project/scouter#298]
I configured my Java agent and host agent in my tomcat machine, the Host agent displaying all data from my tomcat host for OS metrics, but none of the tomcat metrics are getting generated, I append the java agent jar into my Tomcat catalina.sh and -Dscouter.config=<path of config file>, please suggest why i can not see any tomcat performance metrics.

**Comment by bill23-kim** [comment]
show me appended options in catalina.sh and empty chart screenshot on client.

**Comment by mathi201028** [comment]
My Catalina.sh entries are:

-Dscouter.config=<path>/.scouter.config -javaagent:<path>/scouter.agent.java

scouter.config:
net_collector_ip = 10.41.134.72
_hook_spring_rest_enabled = true
trace_interservice_enabled
obj_name=scouterTomcattest
net_collector_udp_port=6100
net_collector_tcp_port=6100

**Comment by mathi201028** [comment]
In my client i am not even getting the object for JAVA, only linux I am able to get. And i downloaded th ebatch agent and started that, and now seeing batch object, still NO JAVA object.

**Comment by bill23-kim** [comment]
It must be specified the correct options in the catalina.sh. 
In other words, scouter.config and scouter.agent.jar should be written by absolute path.

**Comment by mathi201028** [comment]
![java_agent_issue](https://cloud.githubusercontent.com/assets/24261919/23603716/38c310a4-0291-11e7-927f-e2f668f31d02.png)

Please review, I do mention config file and jar absolute path only. Not using relative path

**Comment by mathi201028** [comment]
I am using JDK1.7 is that any problem with JDK versions?

**Comment by mathi201028** [comment]
Any agent log can be enabled to se why the data not being sent to collector?

**Comment by bill23-kim** [comment]
**/home/clouder/scouter/demo-env1/scouter/agent.java/conf/scouter.conf**  <-- Is this file path accurate?
Then, append obj_type=tomcat in scouter.conf  and Set Window -> Preference -> Default javaee type --> tomcat.
JDK 1.7 is compatible.

**Comment by bill23-kim** [comment]
The agent uses UDP to transmit data, so it does not know whether data is sent.

**Comment by mathi201028** [comment]
Still empty graph. No Xlog data either. In the object list I cant see the JAVA, Only can see Linux & Batch objects.

**Comment by bill23-kim** [comment]
In most  cases, configuration mistake or object type is not correct. Please check them step by step.

**Comment by gunlee01** [comment]
Isn't missing "/demo-env1/" in your -javaagent path?

**Comment by mathi201028** [comment]
@gunlee01 The Agent JAR i kept different location. Let me go through each steps. What will be the minimum parameters that required in scouter.config file?

**Comment by mathi201028** [comment]
I revisit all config. Added bare minimum config file entries as follwos.

net_colector_ip = 10.41.134.72
_hook_spring_rest_enabled = true
trace_interservice_enabled
obj_type=tomcat

Still the java object not able to list in the "objects list and empty graph"

Only customized i see in tomcat is, the JMX management running in 18080 instead 8080. please suggest if that matters?

**Comment by mathi201028** [comment]
The one liner in the config files fixed the issue.

"hook_method_patterns=*.*"

Now i can see java agent, still i need to play with various java agent options and capture for analysis.

Thanks everyone for the help/.
