### ISSUE TITLE
Any roadmap to support WAS monitoring agent?

### ISSUE THREAD

**Issue by mathi201028** [scouter-project/scouter#299]
Question : Scouter have any plan or roadmap to support WAS monitoring agent devlopment?

**Comment by gunlee01** [comment]
Scouter is open soruce project and it has been beeng developed and maintained by a few contributors.
So we have basic load map but it's very flexible.
For example we hope to feature web view.
And also want to tightly support famouse libraries like jeddis and many other useful libraries for tracing without any user configurations like scouter's `hook_method_patterns`.
