### ISSUE TITLE
Request/Response 카운트는 수집 안되나요?

### ISSUE THREAD

**Issue by zeroty** [scouter-project/scouter#302]
추후에라도 Request/Response Count에 대해선 지원 예정 사항 없는지요?

**Comment by gaiajeon** [comment]
Service Count가 Response Count와 같은 개념일 것같은데요.

**Comment by zeroty** [comment]
제가 예상하는 바로는 Service Count는 호출 건수(Request)를 의미하는 것 같긴 한데..

이것도 애매한 것이 Service Count 및 ActiveService과 같은 값의 경우 1분 동안 계속 데이터가 누적되기에

실시간 성으로 request count라고 보기에는 애매한 감이 있네요.

1분동안 Service Count값이 유지시키는 이유가 따로 있는 건지요?

**Comment by gaiajeon** [comment]
Request Count는 따로 수집해야 합니다.
제가 말씀드린 부분은 response count = service count를 이야기 한 것이구요.

Service Count 1분 누적 이유는 페이스북 scouter 그룹에서 제가 한번 질문한적이 있습니다.
김성조 이사님이 남기신 글이 있는데 붙여드릴께요..

"ServiceCount는 TPM(분당 건수)를 사용하기 위해 별도로 전송하고 나머지 성능 지표들은 30초 평균을 2초마다 만들어서서 서버로 전송합니다.
2초동안 수집된 데이터가 아니라가 30초 동안의 평균을 2초마다 만드는 것은 데이터를 평탄화 하기위해서입니다. 즉 그냥 액면그대로 데이터를 수집하면 값이 너무 들쑥날쑥하게 됩니다. 그렇게 되면 오히려 데이터로 가치를 상실할 수 있습니다. 그래서 최근 데이터를 쉬프트 시키면서 데이터를 만들어 처리합니다. 이렇게 하는 또다른 이유로는 RDB를 사용하지 않기 때문입니다. 만약 RDB를 사용하면 groupby함수를 통해 SQL문으로 어느정도 평균처리를 할 수 있는데 스카우터는 그것을 로직으로 처리해야함으로 수집단계부터 어느정도 평균처리를 하여 데이터를 수집합니다."

**Comment by zeroty** [comment]
우선 친절한 답변에 감사드립니다.

대충 어느정도 agent소스의 흐름을 파악하면서 위에서 설명해주신 

내용이 머릿 속에 들어오고 있네요. 

그렇다면 request카운트를 추가하기 위해서는

TraceMain.startHttpService() 호출 시 Bucket에 reqCount를 하나 추가 후

MeterService.add() 메소드를 하나 추가하고

	public synchronized void add() {
		Bucket b = meter.getCurrentBucket();
		b.reqCount++;
	}

TraceMain.metering() 호출 시 flag를 두어 add를 호출하면 되겠네요.

제가 생각한 흐름이 맞는지요?

**Comment by gaiajeon** [comment]
넵.. 전체 코드를 보지 못하지만 그림은 맞는 것 같네요

HttpService외에 일반 어플리케이션의 reqCount를 추가하시려면 startService에도 add() 메소드 호출라인을  추가하시는 게 맞을 겁니다.
