### ISSUE TITLE
Host Agent 실행시 sigarException 에러 문의

### ISSUE THREAD

**Issue by hjy87** [scouter-project/scouter#308]
안녕하세요 
Scouter Host Agent 실행시 아래와같이 
SigarException이 발생하고 있어 해결방법 문의드립니다.
현재 Host Agent가 설치되는 장비는 Windows이며
C드라이브와 D드라이브에 HDD를 사용중이며
E드라이브는 ODD입니다.
감사합니다.

20170410 01:30:40 [DISK] disk perf error
org.hyperic.sigar.SigarException: The device is not ready.
: E:\
	org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	com.sun.proxy.$Proxy2.getFileSystemUsage(Unknown Source)
	scouter.agent.counter.task.HostPerf.disk(HostPerf.java:281)
	sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	scouter.agent.counter.CounterExecutingManager$Invocation.process(CounterExecutingManager.java:93)
	scouter.agent.counter.CounterExecutingManager.run(CounterExecutingManager.java:58)

**Comment by gunlee01** [comment]
disk 상태에 따라 sigar exception이 발생하는 경우가 있어 예외 처리 예정입니다.

**Comment by gunlee01** [comment]
resolved
https://github.com/scouter-project/scouter/releases/tag/v0.6.0
