### ISSUE TITLE
콜렉터 서버 수집 데이터 조회 문의

### ISSUE THREAD

**Issue by hjy87** [scouter-project/scouter#309]
안녕하세요
운영중인 WAS에 Java Agent와 Host Agent를 설치하여
콜렉터 서버에 데이터를 쌓고있는데요
콜렉터 서버에 파일DB형태로 저장하고있는 내용을 
클라이언트 CS 프로그램에서 조회하는것처럼 
외부프로그램에서 조회할수있는 방법이 있을까요?
클라이언트 프로그램의 소스중에 특정 파일에 참조할만한 내용이 있다면 가이드 부탁드립니다.
감사합니다.

**Comment by gunlee01** [comment]
plugin을 통해 수집되는 정보를 조회가 가능한 db등으로 옮겨서 사용하시는 것을 추천드립니다.
[influxdb pugin](https://github.com/scouter-project/scouter-plugin-server-influxdb
)
[scouter influx db 연동하기](https://gunleeblog.wordpress.com/2016/04/01/open-source-apm-scouter-influxdb-grafana-%EC%97%B0%EB%8F%99-step-by-step/)
