### ISSUE TITLE
Tomcat 8.5에서 ConnMax값이 수집 안됩니다.

### ISSUE THREAD

**Issue by zeroty** [scouter-project/scouter#310]
Tomcat8.5에서는 maxActive값이 maxTotal로 변경되어서 

TomcatJMXPerf.java 쪽에서 정상 수집이 안되네요.

또 이상한 점이 

```
add(objName, mbean, objType, ValueEnum.DECIMAL, "numActive", CounterConstants.DATASOURCE_CONN_ACTIVE);
add(objName, mbean, objType, ValueEnum.DECIMAL, "numIdle", CounterConstants.DATASOURCE_CONN_IDLE);
add(objName, mbean, objType, ValueEnum.DECIMAL, "maxActive", CounterConstants.DATASOURCE_CONN_MAX);
**add(objName, mbean, objType, ValueEnum.DECIMAL, "maxTotal", CounterConstants.DATASOURCE_CONN_MAX);**
```

와 같이 찍었을 때 처음엔 잘 나오다가 collectCnt가 40번 전에
```
20170410 17:52:48 [A108] jdbc stmt found: oracle/jdbc/driver/OracleStatement
20170410 17:52:48 [A106] jdbc pstmt found: oracle/jdbc/driver/OraclePreparedStatement
20170410 17:52:49 [A107] jdbc rs found: oracle/jdbc/driver/InsensitiveScrollableResultSet
20170410 17:52:49 [A107] jdbc rs found: oracle/jdbc/driver/SensitiveScrollableResultSet
```

DB연결을 시도하게 되면  아래와 같이 
```java
} else if ("DataSource".equals(type)) { // datasource
				String name = mbean.getKeyProperty("name");
```
**WriteAttributes(server, (ObjectName)mbean);**
```java
	private void WriteAttributes(final MBeanServer mBeanServer, final ObjectName http) {
	    MBeanInfo info;
		try {
			info = mBeanServer.getMBeanInfo(http);
			MBeanAttributeInfo[] attrInfo = info.getAttributes();
		    System.out.println("Attributes for object: " + http +":\n");
		    for (MBeanAttributeInfo attr:attrInfo)
		    {
		        System.out.println("  " + attr.getName() + "\n");
		    }
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```
모든 Attribute를 표시하는 코드를 삽입했을 때 데이터 형상이 아래와 같이 변하네요.

Attributes for object: 
```
Catalina:type=DataSource,host=localhost,context=/,class=javax.sql.DataSource,name="jdbc/default":
  connectionProperties
  testOnCreate
  defaultCatalog
  defaultQueryTimeout
  logAbandoned
  password
  maxIdle
  testWhileIdle
  enableAutoCommitOnReturn
  removeAbandonedOnMaintenance
  maxConnLifetimeMillis
  maxWaitMillis
  minIdle
  defaultReadOnly
  removeAbandonedOnBorrow
  connectionInitSqlsAsArray
  lifo
  driverClassName
  evictionPolicyClassName
  cacheState
  validationQueryTimeout
  numActive
  modelerType
  validationQuery
  rollbackOnReturn
  logExpiredConnections
  poolPreparedStatements
  numIdle
  maxOpenPreparedStatements
  jmxName
  removeAbandonedTimeout
  defaultAutoCommit
  abandonedUsageTracking
  loginTimeout
  softMinEvictableIdleTimeMillis
  disconnectionSqlCodesAsArray
  initialSize
  defaultTransactionIsolation
  url
  numTestsPerEvictionRun
  testOnBorrow
  accessToUnderlyingConnectionAllowed
  timeBetweenEvictionRunsMillis
  minEvictableIdleTimeMillis
  maxTotal
  testOnReturn
  closed
  fastFailValidation
  username
```

Attributes for object: 
```
Catalina:type=DataSource,host=localhost,context=/,class=javax.sql.DataSource,name="jdbc/default",connectionpool=connections,connection=1:
  ReadOnly
  Schema
  Closed
  CacheState
  AutoCommit
  Catalog
  Holdability
  TransactionIsolation
  ToString
```

Attributes for object: 
```
Catalina:type=DataSource,host=localhost,context=/,class=javax.sql.DataSource,name="jdbc/default",connectionpool=connections:
  Closed
  BlockWhenExhausted
  AbandonedConfig
  DestroyedCount
  DestroyedByEvictorCount
  MeanActiveTimeMillis
  MeanIdleTimeMillis
  MeanBorrowWaitTimeMillis
  MaxBorrowWaitTimeMillis
  CreationStackTrace
  Lifo
  MaxTotal
  MaxIdle
  MinIdle
  MaxWaitMillis
  TestOnCreate
  TestOnBorrow
  TestOnReturn
  TestWhileIdle
  NumActive
  NumIdle
  LogAbandoned
  DestroyedByBorrowValidationCount
  CreatedCount
  TimeBetweenEvictionRunsMillis
  NumTestsPerEvictionRun
  MinEvictableIdleTimeMillis
  RemoveAbandonedOnBorrow
  RemoveAbandonedOnMaintenance
  RemoveAbandonedTimeout
  BorrowedCount
  Fairness
  NumWaiters
  FactoryType
  ReturnedCount
```

**Comment by zeroty** [comment]
자답 입니다.
	private void getMBeanList() {
		beanList.clear();
		Set<ObjectName> mbeans = server.queryNames(null, null);
		for (ObjectName mbean : mbeans) {
			String type = mbean.getKeyProperty("type");
			**String connectionpool = mbean.getKeyProperty("connectionpool");**
			if (type == null) {
				continue;
			}
			
			if ("GlobalRequestProcessor".equals(type)) {
				String port = mbean.getKeyProperty("name");
				try {
					String objName = conf.getObjName() + "/" + checkObjName(port);
					String objType = getReqProcType();
					AgentHeartBeat.addObject(objType, HashUtil.hash(objName), objName);
					add(objName, mbean, objType, ValueEnum.DECIMAL, "bytesReceived",
							CounterConstants.REQUESTPROCESS_BYTES_RECEIVED);
					add(objName, mbean, objType, ValueEnum.DECIMAL, "bytesSent",
							CounterConstants.REQUESTPROCESS_BYTES_SENT);
					add(objName, mbean, objType, ValueEnum.DECIMAL, "errorCount",
							CounterConstants.REQUESTPROCESS_ERROR_COUNT);
					add(objName, mbean, objType, ValueEnum.DECIMAL, "processingTime",
							CounterConstants.REQUESTPROCESS_PROCESSING_TIME);
					add(objName, mbean, objType, ValueEnum.DECIMAL, "requestCount",
							CounterConstants.REQUESTPROCESS_REQUEST_COUNT);
				} catch (Exception e) {
				}
			} else if ("DataSource".equals(type) && **connectionpool == null**) { // datasource
				String name = mbean.getKeyProperty("name");
				
				WriteAttributes(server, (ObjectName)mbean);
				
				if (StringUtil.isNotEmpty(name)) {
					try {
						String context = mbean.getKeyProperty("context");
						if (context != null && context.length() > 0) {
							context = context.substring(1); 
						}
						if (StringUtil.isNotEmpty(context)) {
							name = context + "_" + name;
						}
						String objName = conf.getObjName() + "/" + checkObjName(name);
						String objType = getDataSourceType();
						AgentHeartBeat.addObject(objType, HashUtil.hash(objName), objName);
						add(objName, mbean, objType, ValueEnum.DECIMAL, "numActive",
								CounterConstants.DATASOURCE_CONN_ACTIVE);
						add(objName, mbean, objType, ValueEnum.DECIMAL, "numIdle",
								CounterConstants.DATASOURCE_CONN_IDLE);
						add(objName, mbean, objType, ValueEnum.DECIMAL, "maxActive",
								CounterConstants.DATASOURCE_CONN_MAX);
						**add(objName, mbean, objType, ValueEnum.DECIMAL, "maxTotal",
								CounterConstants.DATASOURCE_CONN_MAX);**
					} catch (Exception e) {
					}
				}
			}
		}
	}

**Comment by gunlee01** [comment]
제보 감사합니다. 코드 수정하신 부분은 위에 maxTotal을 add 한 부분 한 줄인가요?

**Comment by zeroty** [comment]
String connectionpool= mbean.getKeyProperty("connectionpool"); //추가
} else if ("DataSource".equals(type) && connectionpool == null) { // datasource, 코드 추가
add(objName, mbean, objType, ValueEnum.DECIMAL, "maxTotal",
								CounterConstants.DATASOURCE_CONN_MAX); //코드 추가

3줄 추가했습니다.

**Comment by gunlee01** [comment]
resolved
https://github.com/scouter-project/scouter/releases/tag/v0.6.0
