### ISSUE TITLE
Java 8부터는 Perm gen이 Metaspace로 바꼈다는데요..

### ISSUE THREAD

**Issue by zeroty** [scouter-project/scouter#311]
이상하게도 metaspace값에서

getMax()를 하면 -1을 리턴하는군요.

누군가 OpenJDK 커뮤니티에도 관련 글을 올렸는데

아직까지 오류가 수정이 안된 듯 하네요. 

이 부분 처리는 어떻게 하고들 계시는지요??

**Comment by gunlee01** [comment]
max가 지정되지 않아서 그런것 아닌가요 ? 기본적으로 metaspace는 os의 메모리 제한과 같은것으로 알고있는데
MaxMetaspaceSize를 지정하면 나오지 않을까요?

**Comment by zeroty** [comment]
말씀하신데로 디폴트는 오토리사이징하고,  OS에서 사용 가능한 메모리영역만큼 사용 가능하네요.

추가로 MaxMetaspaceSize를 지정 후에 테스트 해보니 -1이 아닌 정상 값을 호출하네요.

그런데 JVM 8일 경우에는 Perm Gen 수집 값을 metaspace로 대체 해야 되지 않을까요?

**Comment by bill23-kim** [comment]
그래야 할것 같습니다.. 풀리케 해주셔도 좋고요~
