### ISSUE TITLE
Scouter에서 발생한 Exception으로 인해 본 서비스 Exception이 발생

### ISSUE THREAD

**Issue by oing0125** [scouter-project/scouter#312]
안녕하세요, 

Scouter Agent의 EscapeLiteralSQL에서 발생한 ArrayIndexOutOfBoundsException 에러가
본 서비스에서 Exception을 발생시켜 문의드립니다.

서비스는 아래와 같은 환경으로 구성되어 있습니다.

- 프레임워크 : Spring Framework 3.1 + Ibatis 2.3
- WAS : Weblogic
- Java 버전 : 1.7

에러 로그 확인 결과는 아래와 같습니다.

클래스 : EscapeLiteralSQL.java
메소드 : _slash() => getNext(pos) => chars[x+1] 에서 ArrayIndexOutOfBoundsException

사용한 쿼리에 이중 주석( /*  /* */  */)이 포함되어 문제가 된 것으로 보입니다.

문의드리고 싶은 점은 Agent에서 발생한 에러가 본 서비스에 Exception을  끼치고 있어서 해당 내용 문의드립니다.

**Comment by bill23-kim** [comment]
제보해 주신부분 수정되도록 하겠습니다..
에이전트에 profile_sql_escape_enabled=false 옵션으로 해당 로직을 skip 하여 당분간 회피하실수 있을것 같습니다. EscapeLiteralSQL 는 SQL 에 문자열을 추출하여 파라미터로 처리하여 최대한 많은 중복 SQL 을 만들려고 하는 로직입니다.

**Comment by gunlee01** [comment]
resolved : v0.6.0
https://github.com/scouter-project/scouter/tree/v0.6.0
