### ISSUE TITLE
server Built in plugin(XLOG) 사용문의

### ISSUE THREAD

**Issue by hjy87** [scouter-project/scouter#315]
안녕하세요
server builtin plugin 중 PLUGIN_SERVER_XLOG 노테이션을 활용하여
xlog 정보를 influx db에 저장하려고합니다.

그런데 기본 VO(XLogPack)을 통해 받아온 정보중
service, userAgent, error, 등의 정보는
실제로 클라이언트 콘솔에서 확인가능한(사람이 인식할수있는) 문자열 정보가 아닌
int나 long 타입의 코드로 추정되는 데이터만 확인이 되고있는데요

어딘가 클래스의 기능을 통해 데이터를 조회해야할것같은데
해당정보의 원데이터(콘솔에서 보이는 데이터)로 변환하여 조회하는 방법 문의 드립니다.

**Comment by gunlee01** [comment]
```java
String serviceName = TextRD.getString(DateUtil.yyyymmdd(pack.endTime), TextTypes.SERVICE, pack.service);
```
위 코드 참고해 보세요.
아래 링크도 참고하시기 바랍니다.
 * [scouter/server/plugin/IXLog.java](https://github.com/scouter-project/scouter/blob/c08dc244bfd7fdb2f1bb2580f25279af4f8216cb/scouter.server/src/scouter/server/plugin/IXLog.java)
