### ISSUE TITLE
standalone java로부터 수집이 되지 않습니다.

### ISSUE THREAD

**Issue by leetg83** [scouter-project/scouter#316]
안녕하세요 .tomcat과 다른 java standalone 들은 scouter.conf 설정해서 띄우면 sql이나 url이 잘 수집이 되는데 특정 서버에서만 수집이 되지않습니다. 수집이 되지않는 서비스는 netty를 사용하는데요,
혹시 scouter에서 netty는 수집이 되지 않나요?
netty는 netty-3.10.5.Final.jar 이걸 사용하고 있습니다.

**Comment by gunlee01** [comment]
standalone 프로그램은 hook_service_patterns option으로 측정의 시작 지점을 지정해주셔야 합니다.
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Configuration.md

Servlet application의 경우 시작점을
HttpServlet#service 로 정해져 있기때문에 scouter에 기본으로 설정되어 있어 측정이 가능한 것입니다.

Netty를 사용하여 NIO로 요청을 받았더라도, 그 이후 처리에 thread 를 할당하여 비즈니스 로직을 시작하고 끝날때 까지 해당 thread를 사용하는 구조라면 측정이 가능합니다.
만약 vert.x 와 같이 single(또는 수개의) thread가 event loop를 통해 처리하는 방식의 플랫폼이라면 추적이 불가능합니다.

**Comment by leetg83** [comment]
안녕하세요. 해당 서버는 event loop를 통해 처리하는 call back 방식이 아니고 단순히 multi thread 방식입니다. 그리고 다른 Spring boot를 사용하는 서버들은 (임베디드 톰캣을 사용 중) 메소드 시작지점을 hook_service_patterns= 으로 지정하면 잘 나오고 있습니다.
혹시 다른 문제가 있는 경우가 있을까요?

**Comment by gunlee01** [comment]
설정만 잘 되었다면 안나올 이유는 없어 보입니다.
혹시 모르니 object type에 맞는 xlog view를 열었는지  한번 확인해 보시기 바랍니다.
수집서버에서 우클릭하거나 collector 메뉴에서 확인할 수있으며 java,tomcat,jetty 등 여러타입이 나올수 있습니다. 해당 타입에 맞는 xlog view 인지 확인해보세요
