### ISSUE TITLE
scouter 클라이언트 xlog 드래그 max 값 설정

### ISSUE THREAD

**Issue by jyson8388** [scouter-project/scouter#317]
안녕하세요 
스카우터 사용시 하루치 트랜잭션 전체를 드래그로 뽑으려고 합니다.
xlog에서 드래그 하였을 시에 드래그로 잡히는 트랜잭션이 맥스 200으로 잡혀 있어 
200이상 확인이 불가능 합니다. 
또한 xlog에서 우클릭 search 메뉴에서도 max값이 500으로 설정 되어 있는데 
설정을 증가 시켜 더 많은 트랜잭션을 확인 하고 싶습니다. 
예를 들면 하루치 트랜잭션이 2만개면 2만개 다 잡을 수 있도록 설정하고 싶은데
가능한지 여부와 설정을 어떻게 해야하는지에 대해서 질문드립니다. 

감사합니다.

**Comment by gunlee01** [comment]
안녕하세요.
운영중인 scouter 서버에서 대량으로 데이터를 뽑는 작업 자체가 데이터 수집에 문제를 일으킬수 있기 때문에 지양하고 있기는 합니다.
그래서 부가적인 분석이 필요하시다면 server plugin을 제작하여 (RDB같은) 다른 저장소로 데이터를 추가 저장한 후 분석하도록 안내를 드리고 있습니다.
그리고 클라이언트에서도 로딩하는 xlog의 수가 너무 많으면 OOM이 발생할 수가 있습니다.

플러그인 제작을 추천드리나 급하게 필요하시다면
드래그시 200개로 고정된 코드를 변경하여 커스텀 빌드하여 사용해보시기 바랍니다.
소스 위치는 scouter.client.xlog.views.XLogViewMouse#listSelectedXLog() 입니다.

* 개발환경 구성은 아래 개발가이드를 참고해 보세요.

* 클라이언트 빌드만 필요하다면 그냥 소스 clone 받은후에, 적절히 수정하시고 
   ```build_client.sh``` 만  실행하면 됩니다. 
   - prerequisite : maven 3.3+ & java8+

* 개발가이드
https://github.com/scouter-project/scouter/blob/master/scouter.document/tech/Developer-Guide.md

**Comment by gunlee01** [comment]
the option is applied on v1.7.0
