### ISSUE TITLE
일일 트랜잭션 조회 기능 여부 질문

### ISSUE THREAD

**Issue by jyson8388** [scouter-project/scouter#319]
안녕하세요 
아래에도 이슈를 등록했던 사용자 입니다. 
클라이언트에서 보여지는 화면 처럼 동일 하게 트랜잭션을 개수 제한 없이 리스트로 출력 할 방법이 있는지에 대해서 궁금합니다. 
 예를 들면 현재 file system db에 내용을 스카우터 클라이언트에서 가져와서 보기 편하게 제공해주는 것과 같이 file system db를 어떻게 파싱하는지에 대해서 궁금합니다. 또한 이를 자바 프로그램으로 따로 저희쪽에서 개발이 가능한지요?

**Comment by gunlee01** [comment]
안녕하세요.

두가지 방법이 있을 것 같습니다.

첫번째는 XLog 수집시점에 XLog plugin 제작을 통해 다른 database에 동시에 저장하는 방법입니다.
XLog plugin에 대한 샘플은 아래 블로깅을 참고하시면 될 것 같습니다.
 - [배치 모니터링, Scouter로 편하고 효율적으로](http://m.blog.naver.com/tmondev/220870505665)

두번째는 직접 데이터 파일을 파싱하는 방법입니다.
그런데 이렇게 개발하시기는 현재의 파일 DB 로직을 분석해야 하기때문에 쉽지는 않을 듯 합니다.
```scouter.server.db.XLogRD.scala``` 를 참고하시기 바랍니다.
