### ISSUE TITLE
Scouter Batch Agent 에러 - java.lang.UnsupportedClassVersionError : scouter/util/EscapeLiteralSQL

### ISSUE THREAD

**Issue by oing0125** [scouter-project/scouter#320]
안녕하세요, Scouter APM 잘 사용하고 있습니다~

Stand-alone Batch에 scouter를 적용하던 중 에러가 발생하여 문의드립니다.

DB Connection 맺는 부분에서 java.lang.UnsupportedClassVersionError : scouter/util/EscapeLiteralSQL 에러가 발생하면서 배치가 정상 동작하지 않습니다.

배치 실행 환경은 아래와 같습니다.
- java : 1.7.0_51
- db : mysql

감사합니다.

**Comment by gunlee01** [comment]
명확히 말씀드리기 애매하긴한데,
빌드 시점 java 버전에 문제가 있었을 수도 있을 것 같습니다.
최신 버전으로 다시 한번 시도해 보시기 바랍니다.
