### ISSUE TITLE
altibase sql profiling

### ISSUE THREAD

**Issue by todwnl04** [scouter-project/scouter#324]
안녕하세요. 개발 중인 서비스에 scouter를 적용시키다 궁금한 점이 있어 질문 드립니다.
XLog 상세로 봤을 때 CONTENTS에 쿼리에 대한 수행 결과는 보여지지 않는데요. 
DB는 altibase 이고, 드라이버는 JDBC 6.3.1.7.3 버전 사용 중입니다.

**Comment by gunlee01** [comment]
알티베이스 JDBC 드라이버를 구하기가 어려운데
사용하시는 드라이버 파일을 올려주실 수 있으신가요?

**Comment by todwnl04** [comment]
[altibase-jdbc-6.3.1.7.3.zip](https://github.com/scouter-project/scouter/files/1009425/altibase-jdbc-6.3.1.7.3.zip)

zip 파일로 올려드립니다. 현재 사용 중인 altibase JDBC 드라이버입니다.

**Comment by gunlee01** [comment]
altibase support feature release at v1.7.0
