### ISSUE TITLE
Dump data to file/mysql

### ISSUE THREAD

**Issue by giosdas** [scouter-project/scouter#335]
Is it possible to read data of Xlog in server/database directly, without using scouter client?
I'm trying to load data inside a mysql database or file for simple performance analysis 
Thanks

**Comment by gunlee01** [comment]
There is no way to access the scouter repository without a scouter client.
But someone store the data to another storage(eg. RDBMS) for integration with there legacy monitoring systems by building their own scouter server plugins.(a.k.a scouter built-in plugin)

Please refer to below links.
* It's korean contents but you can use a translator.
   * https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Server-Plugin-Scripting_kr.md
* The code may help you.
   * https://github.com/scouter-project/scouter-plugin-server-influxdb

**Comment by gunlee01** [comment]
```java
@ServerPlugin(PluginConstants.PLUGIN_SERVER_XLOG)
public void xlog(XLogPack pack){
	String objName = TextRD.getString(yyyymmdd, TextTypes.OBJECT, pack.objHash);
	String service = TextRD.getString(yyyymmdd, TextTypes.SERVICE, pack.service);
	//.......
	if (pack.error != 0) {
	error = TextRD.getString(DateUtil.datetime(pack.endTime), TextTypes.ERROR, pack.error);
	//...... send this information to another message queue system
	//...... or insert to database table ...
}
```

**Comment by gunlee01** [comment]
Also Web api helps you. (The web api is now on developing and will release for next version)
