### ISSUE TITLE
tomcat 7.0.68 / aix6.1 / 환경에서 scouter 적용시 file descriptor 누수

### ISSUE THREAD

**Issue by lys0046** [scouter-project/scouter#344]
안녕하세요 처음엔 0.4 버젼으로 적용햇는데 디스크립트 갯수가 점점 증가하더니

too many file opens 가 발생하면서 시스템이 다운됩니다.

scouter 1.7.1 버젼으로 업그레이드를 해도 동일하구요 

혹시 버그가 있나요?

**Comment by gaiajeon** [comment]
아직 too many file opens 관련해서 에러를 본 적은 없는데요.
해당 aix 장비에 lsof가 설치되어 있으면 
어떤 파일로 인해 문제가 발생하는지 파악을 할 수 있을 것 같네요.

여건이 되시면 lsof -p 프로세스pid로 확인을 부탁드립니다.

**Comment by lys0046** [comment]
lsof 로 확인해보니 디스크립터가 web application 의 web-inf/lib/ 밑의 jar 파일을 수시로 여는데 디스크립터가 정리가 돼지않는것 같습니다. 특정 파일만을 계속 여는거 같진않구요

**Comment by gaiajeon** [comment]
scouter를 적용하지 않을 때에는 해당 문제가 발생하지 않는 상황인거죠?

**Comment by lys0046** [comment]
네 그렇습니다 빼고나면 저파일을 한번만 열고 마는데 scouter를 걸고나면
계속해서 파일을 여는데 누수가 발생합니다.

**Comment by lys0046** [comment]
추가로 확인해보니 scouter를 뺐을때엔 디스크립터를 소모하여 프러퍼티를 400개 정도까지 열다가
디스크립터가 정리돼는데 적용후엔 정리가 안돼고 계속적으로 여는행위를 반복하여 ..10000개정도까지 쌓이는걸 확인했습니다.

**Comment by gaiajeon** [comment]
scouter 사용 시 특정한 액션을 주지는 않고 있으신거죠.? 예를 들어 클래스 목록 조회라던지, scouter 클라이언트에서 특정 기능을 사용하시거나 하는 건 없으신거죠.?

**Comment by lys0046** [comment]
해당 파일은 웹어플리케이션에서 참조하는 파일이라 딱히 아실필요는 없을것 같지만 알려드리겠습니다.
특정 클래스목록조회나 특정프러퍼티를 넣지는않았습니다.
/li_appl/appl/app/rms/DEV/WEB/RMS.properties 이런식의 프러퍼티고  안에 내용은 웹어플리케이션에서 사용하는 파라미터성 정보와 디비연결정보 등입니다.

scouter 설정엔 별도로 기입한 내용은 없습니다.설정은 아래와 같습니다.

#Scouter Server IP Address (Default:127.0.0.1)
net_collector_ip=10.10.10.159

#Scouter Server Port (Default:6100)
net_collector_udp_port=6100
net_collector_tcp_port=6100

**Comment by gunlee01** [comment]
여러 각도에서 고민을 해봤는데 관련성을 찾기가 어렵네요.
참고 할 만한 추가적인 정보가 생기면, 여기에 남겨주시면 감사하겠습니다.

**Comment by gunlee01** [comment]
long pending close
