### ISSUE TITLE
Host Agent inactive-object관련 문의

### ISSUE THREAD

**Issue by oing0125** [scouter-project/scouter#350]
안녕하세요,

윈도우 서버에 Host Agent를 설치하여 Scouter 사용하고 있습니다.
특정 서버에서 주기적으로 Inactive Object라는 Title의 Warning Alert이 발생하여 문의드립니다.
해당 메세지 발생 후 서버 확인 결과 Host Agent는 정상적으로 떠있고
CPU나 Memory같은 Host 데이터는 잘 들어오고 있습니다.

해당 서버의 문제인지, 아니면 Scouter를 사용 중인 다른 서버에서도 발생하고 있는 문제인지 궁금합니다.
(저희 서버 중 일부 3개 서버만 해당 에러가 발생하네요ㅜ)
아니면 Alert 내용 중 특정 Title을 필터할 수 있는 방법이 있는지 알고 싶습니다.

감사합니다.

**Comment by gunlee01** [comment]
agent에서 주기적으로 heart beat을 보내는데 8초간 들어오지 않으면 inactive로 인식합니다.
해당 agent와 server간 어떤 문제가 있는 것으로 예상됩니다.
8초는 서버 옵션으로 조정가능합니다.
```object_deadtime_ms=8000```

**Comment by oing0125** [comment]
Scouter Server에 object_deadtime_ms 설정 변경해서 사용해야겠네요~
확인해주셔서 감사합니다.
