### ISSUE TITLE
테스트 하다 보니 Statement에 대한 Not Close 체크가 없는 것 같네요.

### ISSUE THREAD

**Issue by gaiajeon** [scouter-project/scouter#362]
PrepareStatement에 대한 체크 로직은 있는 듯 한데요 Statement Not Closed 에 대해서는 체크가 되지 않는 듯합니다. JSP코드를 작성하여 테스트 해보니 체크 되지 않는데  특별한 이유가 있는 지 궁금하네요.

**Comment by HooJung** [comment]
특별한 이유는 없습니다. 확인해 봐야 겠네요.

**Comment by sjokim** [comment]
jdk버전이 낮을 때는 Statement not close 를 체크하는것이 중요 했습니다 근데 요즘은 의미가 크지않다고 보고 있습니다 심지어 db connection에 대한 not close(미반환)도 mybatis 같은것을 사용하면 추적할 필요가 없습니다
사실 다 추적하면 좋지만 불필요한 오버헤드를 줄이기 위해 statement leak을 추적하지 않고 있습니다 혹시 그로 인해 장애가 발생하는 사례가 있으면 공유 부탁합니다

**Comment by gaiajeon** [comment]
코멘트 감사합니다. 충분히 이해가 됩니다. 제가 pull request한 부분은 reject해도 될 듯합니다.

**Comment by gunlee01** [comment]
일단 mege 하였습니다. 오버헤드에 대해서는 옵션 처리로 가면 될 것 같습니다.
