### ISSUE TITLE
web api for getting xlogs by gxid

### ISSUE THREAD

**Issue by gunlee01** [scouter-project/scouter#369]
web api for getting xlogs by gxid

**Comment by gunlee01** [comment]
```RequestCmd.XLOG_READ_BY_GXID```
  => ```scouter.server.netio.service.handle.XLogService#loadByGxId```

**Comment by csk746** [comment]
@gunlee01 
1. loadByGxId -> readByGxId 일까요?
2. txid로 가져오는 api는 SXlog를 반환하고 gxid는 List<SXlog> 반환하는 api인가요~?

**Comment by gunlee01** [comment]
@csk746 
개발하면서 메소드명 패턴이 좀 바뀌어서
 - retrieveByGxid 가 될 것 같습니다.
 - 네. txid로 조회하는 것과 달리 결과가 여러개의 xlog가 됩니다.
   하나의 요청이 여러개의 웹서비스등을 호출할 때 동일한 gxid와 각각의 txid를 가지게 되고 이를 서로 연결할 목적으로 사용됩니다.
