### ISSUE TITLE
web api for retrieving daily and hourly visitor count by objHash and objType

### ISSUE THREAD

**Issue by gunlee01** [scouter-project/scouter#377]
web api for retrieving daily and hourly visitor count by objHash and objType

```RequestCmd.VISITOR_LOADDATE_TOTAL```
```RequestCmd.VISITOR_LOADDATE_GROUP```
```RequestCmd.VISITOR_LOADDATE_GROUP```
```RequestCmd.VISITOR_LOADHOUR_GROUP```

**Comment by csk746** [comment]
@gunlee01 
2,3 번째 커맨드가 같은데 
RequestCmd.VISITOR_LOADDATE
RequestCmd.VISITOR_LOADDATE_TOTAL
RequestCmd.VISITOR_LOADDATE_GROUP
RequestCmd.VISITOR_LOADHOUR_GROUP
이렇게 4개가 맞는걸까요?

**Comment by gunlee01** [comment]
@csk746 예 그렇게 4개 네요 :)
