### ISSUE TITLE
SCOUTER apm tools monitor TIBCO API 

### ISSUE THREAD

**Issue by prashantnitt07** [scouter-project/scouter#378]
hi ,
I want to know that , SCOUTER APM TOOL will be monitor following JAVA TYPE.

1 Tomcat 
2, JBOSS
3. Weblogic 
4. TIBCO API
please reply

**Comment by prashantnitt07** [comment]
please reply SCOUTER support for TIBCO JAVA

**Comment by prashantnitt07** [comment]
TIBCO BW

**Comment by gunlee01** [comment]
Hi,
Scouter can monitor any java application.
But some application (non servlet application) need to be configured in order to know which method is a start point of service to monitor.

https://github.com/scouter-project/scouter/blob/master/scouter.document/use-case/NON-HTTP-Service-Trace.md

**Comment by prashantnitt07** [comment]
what is step for install SCOUTER APM tool on Linux server. please provide step or guide

**Comment by gaiajeon** [comment]
For step for install SCOUTER APM tool on Linux server, please see the link below

https://github.com/scouter-project/scouter/blob/master/scouter.document/index.md
