### ISSUE TITLE
alert plugin의 config 변경사항 반영

### ISSUE THREAD

**Issue by twinsoul** [scouter-project/scouter#390]
alert plugin의 plugin 폴더에 있는 *.conf 파일을 변경하여도 에이전트가 여러 개인 경우 모든 에이전트에 반영되지 않고 일부만 변경사항이 반영됩니다. (10초를 2초로 변경하면 일부 에이전트는 2초 변경되서 수집되고 나머지는 그대로 10초) 그래서 전체 에이전트에 반영되도록 하기 위해서는 서버를 다시 내렸다올려야 합니다. 이것은 버그인지 원래 그러한 것인지요.. 다른 방법이 있나요?

**Comment by gunlee01** [comment]
다음 버전에서 Fix 예정입니다.

**Comment by gunlee01** [comment]
resolved at v1.8.0
