### ISSUE TITLE
soucter client java 9 실행 오류

### ISSUE THREAD

**Issue by boojongmin** [scouter-project/scouter#393]
안녕하세요

스카우터 클라이언트를 우분투 16 환경에서 사용하고 있습니다.
terminal에서 java --version을하면 8로 나오는데
뭔 이유에서인지 client가 로그인하면 뻗길래 로그를 확인해보니
java 9으로 인식하네요(뭔가 특정 폴더의 최신 jvm을 실행하는 모양새인데...정확한 룰은 모르겠네요)

여튼 9으로 인한 이슈로 클라이언트가 실행이 안되서 해결방법을 찾아보니
-vmargs 하단에
"--add-modules=java.se.ee" 이 옵션이 추가되어야 된다고합니다.
적용해보니 되는 것 확인했습니다. 

--add-module 옵션을 찾아보니 [JEP 261](http://openjdk.java.net/jeps/261)
직소때문에 추가된 옵션인것 같은데

클라이언트 배포버전에 9 지원용으로 해당 옵션을 추가하면 좋을 것 같습니다.

```
openFile --launcher.appendVmargs 
-vmargs 
--add-modules=java.se.ee 
-Dosgi.requiredJavaVersion=1.
```

[오류 해결한 블로그](http://pentode.tistory.com/250)

**Comment by gunlee01** [comment]
resolved at v1.8.0
