### ISSUE TITLE
멀티 서버, 한대 수집서버 동작 가능한가요?

### ISSUE THREAD

**Issue by tweety2411** [scouter-project/scouter#396]
찾아보다가 궁금해서 남깁니다.
이제 막 스카우터를 설치해보고 테스트 중인데요.
서버가 여러대이고 수집서버를 한 대로 할 경우 client로그인 시에 서버 한대밖에 안보여서요.
수집서버를 다른 서버로 하고 client에서 서버 추가하니까 보이던데
수집서버가 한 대일 경우 동작이 안되나요..?
또 궁금한 건 여러 서버의 xlog를 한 화면에 볼 수 있나요?
톰캣별로가 아닌 합쳐진 화면으로 볼 수 있는지 궁금합니다 
궁금합니다.

**Comment by bill23-kim** [comment]
수집서버 한대에 여러 서버 모니터링이 가능합니다.
같은 오브젝트 타입별 로만 xlog 를 볼 수 있습니다. 아니면 톰캣이 아닌 다른 서버 에이전트 설정(scouter.conf)에 obj_type=tomcat 을 넣으면 모두 tomcat 으로 나오기 때문에 xlog 한 차트에서 볼수 있습니다.

**Comment by gunlee01** [comment]
질문이 잘 이해가 안되어 추측해서 답변드리자면
각 모니터링 대상 어플리케이션에서 어떤 수집서버로 성능 데이터를 전송할지 설정해 주어야 합니다.
설정명은 net_collector_ip 입니다.

잘 안되시면 scouter 설치에 대한 여러 블로깅들이 있으니 참고해서 설치를 진행해 보시기 바랍니다.
http://gunsdevlog.blogspot.kr/2017/07/scouter-apm-1.html
