### ISSUE TITLE
API중에서 /v1/xlog-data/{yyyymmdd}에 대해 궁금합니다.

### ISSUE THREAD

**Issue by zeroty** [scouter-project/scouter#402]
우선 http://demo.scouterapm.com:6180/scouter/v1/xlog-data/realTime/0/0?objHashes=884536200라는 api로 xlog 데이터를 조회하였을 때 이러한 데이터가 마지막에 조회되었습니다.

{"endTime":"1510736683188","objHash":"884536200","service":"/jpetstore/e2end.jsp","txid":"-308033698868356218","threadName":"http-bio-8080-exec-15","caller":"899917711036901108","gxid":"899917711036901108","elapsed":"445","error":"","cpu":"3","sqlCount":"1","sqlTime":"1","ipAddr":"127.0.0.1","allocatedMemory":"1796","internalId":"0","userAgent":"Java/1.8.0_121","referrer":"","group":"*.jsp","apicallCount":"0","apicallTime":"0","countryCode":"","city":"","login":"","desc":"","hasDump":"0","text1":"","text2":"","text3":"","text4":"","text5":"","queuingHost":"","queuingTime":"0","queuing2ndHost":"","queuing2ndTime":"0","xlogType":"WEB_SERVICE"}],"offset1":"271","offset2":"5709","count":"9997"}}

여기에 있는 endtime 시간을 기준으로 다시  http://demo.scouterapm.com:6180/scouter/v1/xlog-data/20171115?startHms=180300&endHms=180500&objHashes=884536200로 데이터를 조회했을 때

{
  "status": "200",
  "resultCode": "0",
  "message": "",
  "result": {
    "xlogs": [],
    "hasMore": false,
    "lastTxid": "0",
    "lastXLogTime": "0",
    "count": "0"
  }
}

데이터가 아무것도 나오지 않네요. 무엇을 잘못 호출한 것인지요?

**Comment by gunlee01** [comment]
제가 demo를 잘못올려놔서 그런듯 합니다.
조만간 다시 올리도록 하겠습니다. scouter server의 시간을 GMT로 설정해 실행한 것 같아요.
미리 확인해 보시려면 조회하는 시간에서 9시간을 빼서 날리면 되지 싶습니다.

**Comment by gunlee01** [comment]
변경하여 적용되었습니다.
