### ISSUE TITLE
if else문 중첩 사용을 switch문으로 변경하는 작업

### ISSUE THREAD

**Issue by KimHyeockJin** [scouter-project/scouter#410]
현재 if else 문의 중첩 사용되어있는 것이 많습니다.
``` java
if(token.equals("(")) {
    parenthesisCount++;
    inParenthesis = true;
} else if(token.equals(")")) {
    parenthesisCount--;
    if (parenthesisCount == 0) {
        inParenthesis = false;
    }
} else if(token.equals("SELECT")) {
					
...
} else if(token.equals("JOIN")) {
    createOrAppendNode(SQLTypeEnum.SELECT);
    i = applyNode(i, tokens);
}
```
switch문이 비교가 4개 이상일 때부터는 if else 문보다 속도가 빠르다고 알고있습니다.
java 7 부터는 String도 switch문이 사용이 가능합니다. 

이런 경우 고칠 수 있는 경우는 if else 문을 switch문으로 바꿔주는 것이 좋을 것 같습니다.

**Comment by KimHyeockJin** [comment]
if else문을 몇몇 switch case문으로 변경해보았습니다.
**if else문 switch로 변경** [#408](https://github.com/scouter-project/scouter/pull/408/commits/97637b078303d4ba7e1fc481b72cfda6bafdf32b)

**Comment by KimHyeockJin** [comment]
```java
dir.equals(".");
```
와 같은 코드를
```java
".".equals(dir);
```
로 수정해야 할 것 같습니다.
변수의 경우가 null이 올 수 있어 null 이 아닐 문자열 상수를 앞에 두는 것이 좋을 것 같습니다.
이 점을 수정해서 올려도 괜찮을까요?

**Comment by gunlee01** [comment]
document를 보시면 아시겠지만 scouter의 java agent는 java 6 환경을 지원하기 때문에 switch 문은 변경할 수 없습니다. 
equals 부분은 신규로 작성하시는 부분이라면 상수를 앞에 두는 식으로 개발하는 것도 좋습니다만 현재 소스에서 명확히 null 체크가 없어 문제가 될 부분이 아니라면 그냥 두는게 나을 듯 합니다.

**Comment by KimHyeockJin** [comment]
답변 감사합니다. 
코드를 보던 중 char도 if else 로 되어있는 경우가 있어 그 부분은 수정해서 올려도 괜찮을까요?

**Comment by gunlee01** [comment]
@KimHyeockJin 네.
