### ISSUE TITLE
XLog list에서 서비스명에 * 가 포함되어 표시되는 현상

### ISSUE THREAD

**Issue by rtist79** [scouter-project/scouter#413]
안녕하세요.
웹로직으로 서비스하는 시스템을 scouter 를 적용하여 테스트 중입니다.
실제로 호출된 URL은 domain/context/aaaa.esc   형태인데
 XLog list 에서는 service가 /**/*.esc  와 같은 형태로 표시가 되서 상세 내역을 봐야지만 
실제 어떤 건인지 확인이 가능합니다.

혹시 해당 부분을 * 가 아닌 실제 호출된 url에 기반한 이름이 나오게 할수 있는 방법은 없을까요?

**Comment by gunlee01** [comment]
흠.. **이나 *로 치환해 주는 로직은 없는데 이상하네요.
일단 profile_spring_controller_method_parameter_enabled=false 로 한번 적용해보세요.

혹시 해결되시면 어떻게 해결하셨는지 남겨주심 감사하겠습니다.

**Comment by rtist79** [comment]
해당 옵션이  default  가  false 인것 같은데, 명시적으로  false 로도 바꿔보고,
true 로도 바꿔봤는데 결과는 동일하네요.

다만 웹로직 구동시 로그에 보면 아래와 같은 로그들이 보여집니다.
그리고 domain/context/aaaa.esc  로 호출되는 서비스는 /**/*.esc 로 보여지고
domain/context/getKey.sc  로 호출되는 서비스는 /**/getKey.sc  로 나타납니다.

` ...`
`20171211 14:56:05 [SCOUTER] [Apply Spring F/W REST URL] /**/getKey.sc<POST> [:SRM] `
`20171211 14:56:05 [SCOUTER] [Apply Spring F/W REST URL] /**/*.do [:SRM] `
`20171211 14:56:05 [SCOUTER] [Apply Spring F/W REST URL] /**/*.esc<POST> [:SRM] `
`20171211 14:56:05 [SCOUTER] [Apply Spring F/W REST URL] /**/*.esc<GET> [:SRM] `
`...`

혹시 해당 현상을 보고 뭔가 유추해 볼만한게 없을까요?

**Comment by gunlee01** [comment]
@rtist79 
해당 옵션은 웹 어플리케이션의 재기동시에 적용이 됩니다.
현재 최신 버전에는 해당 옵션의 기본값이 true 입니다.
로그를 보니 이 옵션과 관련이 있어보이는데
먼저 java agent의 버전을 올린후에 
_hook_spring_rest_enabled=false로 세팅후 기동해 보세요.

**Comment by rtist79** [comment]
@gunlee01 
현재 사용중인 버젼이 1.8.0으로 최신 버젼입니다.
제가 Default  가 false  인것 같다고 말씀드린건 
Scouter Client  프로그램의 Configure 설정 화면에서 
profile_spring_controller_method_parameter_enabled  의 Def. 값이 false로 나와서 그렇게 추측한건데
제가 설치한 프로그램의 문제인지 뭔지 잘 모르겠네요..
(제 PC에 테스트용으로 이전버젼을 설치했던적이 있는데 그게 원인인지 모르겠네요.)

어쨌든 알려주신 _hook_spring_rest_enabled=false 로 세팅후에 문제가 해결됐습니다.
_ 로 시작하는 설정값은 Client  프로그램에서도 찾을수가 없었는데
도움주셔서 해결 됐습니다. 
감사합니다.
