### ISSUE TITLE
web api NullPointerException 

### ISSUE THREAD

**Issue by twinsoul** [scouter-project/scouter#416]
GET /v1/counter/stat/{counter}/ofType/{objType}

위의 api를 호출하던 중 아래와 같은 500 서버오류가 나서 문의드립니다. 

{
  "status": "500",
  "requestId": "#b0f74",
  "resultCode": "500",
  "message": "java.lang.NullPointerException [caused by] null",
  "result": null
}

날짜를 2주정도 좀 길게 잡았는데 아마도 이전 데이터는 삭제되어 더 이상 없을 경우 발생하는 현상으로 보입니다. 날짜간격을 줄여가며  호출하니 정상데이터를 리턴하는데 해당 날짜에 데이터가 없으면 아예
 500 오류를 내는것 같습니다. 

문제는 호출할 때 스카우터에 언제적까지의 데이터가 있는지 정확히 모른다는거네요.

**Comment by gunlee01** [comment]
재현되는지 확인해보겠습니다. 감사합니다.

**Comment by gunlee01** [comment]
재현 어려운데 로그 제공 부탁드려요.
