### ISSUE TITLE
netty addListener가 event를 catch하지 못 하는 문제

### ISSUE THREAD

**Issue by maenoops** [scouter-project/scouter#417]
netty로 개발된 서버를 scouter로 모니터링하고 있습니다.
그런데 서버 트래픽이 올라가면 netty 서버가 connect event를 catch하지 못해 addListener가 동작하지 않는 경우가 있습니다. 실제 connection 여부를 확인하기 위해 문제 발생 당시에 tcpdump를 떠서 확인해 보면 connection은 성공한 상태입니다.
문제가 발생하는 포인트는 netty 서버가 요청 받은 request를 처리하기 위해 외부 데이터 서버에 접속하는 순간으로 트래픽 수준은 초당 30~40건 수준이고 장비 load는 많이 높지는 않습니다. (대략 0.5 ~ 1.0)
위 문제는 scouter 모니터링을 제거하면 발생하지 않습니다.

혹시 scouter 설정상의 문제일까요? 원인을 알 수 없어 문의 드립니다.

**Comment by gunlee01** [comment]
netty로 개발된 서버라는건 servlet은 아니고 hook_service_patterns로 서비스 추적 유형을 등록해서 사용하신다는 거죠?
일단 몇가지 옵션을 꺼보시기 바랍니다.
_hook_socket_enabled=false   // socket의 connection에 대한 추적을 하지 않습니다.

이렇게 해보시고 동일하다면
_hook_methods_enabled=false // 모든 메소드를 추적하지 않습니다.
도 해보시기 바랍니다.
(현재 버전에 원격 http call 추적만 disable 하는 옵션이 없습니다. 필요하다면 다음 버전에 추가를 검토하겠습니다.)

**Comment by gunlee01** [comment]
long pending closing.
On additional thread, reopen it plz.
