### ISSUE TITLE
xlog 여러개를 하나의 화면에 구성하면 "점"이 나타나지 않음"

### ISSUE THREAD

**Issue by cowboy93** [scouter-project/scouter#423]
하나의 화면에 
여러 수집서버의 xlog 화면을 띄워 놓으면,
점이 나타나지 않습니다. 

하지만 
어떤 다른 탭을 눌렀다가 돌아오면 
모든 xlog 가 나타납니다. 

![image](https://user-images.githubusercontent.com/175918/34700698-b863eba6-f527-11e7-96df-f832233f3e43.png)
이 이미지가 클라이언트 띄운지 3분 후의 화면입니다. 

Gunhee 님께는 메신저로 말씀 드렸어요 ~

**Comment by gunlee01** [comment]
resolved at v1.8.1
