### ISSUE TITLE
SCOUTER Cookie 옵션 추가 요청

### ISSUE THREAD

**Issue by passionlim** [scouter-project/scouter#426]
안녕하세요. Scouter 를 잘 쓰고 있는 유저입니다. 

현재 user_trace_mode=2 에서는 사용자 통계 추적을 위해 SCOUTER COOKIE 를 생성하고 있습니다.
하지만 Set-Cookie 에 Path 값이 없어 Application 에 첫 접속하는 주소에 따라 Cookie 값이 생성되고 있습니다.
이는 아래와 같은 스펙으로 Set-Cookie 가 동작하기 때문입니다.

> For Set-Cookie without path attribute, RFC6265 states that:
>  If the server omits the Path attribute, the user agent will use the "directory" of the request-uri's path component as the default value.
참고: https://stackoverflow.com/questions/43324480/how-does-a-browser-handle-cookie-with-no-path-and-no-domain?answertab=votes

첫 페이지가 상위 Path 페이지라면 괜찮겠지만 그렇지 않은 경우 SCOUTER 쿠키가 많이 생성되는 증상이 있습니다.
(첨부파일)

![scouter_cookie](https://user-images.githubusercontent.com/4545649/35915159-2e262de4-0c49-11e8-8719-9a7ca649f3bd.png)

따라서 다음과 같은 기능이 있으면 합니다.
- SCOUTER 쿠키에 대해 Path 값을 지정 ( 또는 Default 값으로 Path=/ 를 추가 )

일단 리포팅을 먼저하고 PR은 올리도록 하겠습니다.

**Comment by passionlim** [comment]
Pull Request 까지 추가하였습니다. 의견 부탁 드립니다.

**Comment by gunlee01** [comment]
네. 제안 감사드립니다.
PR도 확인해보도록 하겠습니다.

**Comment by passionlim** [comment]
spring-boot 로 간단한 동일 상황을 만드는 웹서버를 만들었습니다. 
패치된 agent 를 각각 붙여 보았고 브라우저로 테스트 해보니 scouter 
53 개 path 로 SCOUTER 쿠키가 생성된 경우 Internet Exploer 11 에서 JSESSIONID 와 같은 쿠키 유실이 발생하는 것을 확인하였습니다.

https://github.com/passionlim/without-cookiepath-browser-test

따라서 Cookie 에 Path 설정을 기본 ROOT(/)로 설정하는 것이 어떨지 제안 드리고 싶습니다.

**Comment by gunlee01** [comment]
기본 설정을 제안해주신데로 root 로 가져가는게 더 효율적으로 보이네요.
Scouter 커미터분들과 함께 의논해서 적용하도록 하겠습니다.
그리고 올려주신 PR에 답글 남겼으니 확인해보시기 바랍니다.

**Comment by passionlim** [comment]
https://github.com/scouter-project/scouter/pull/430
에 PR 추가했고 Default Path 를 / 로 추가하였습니다. 
CLA 는 제출했습니다.
