### ISSUE TITLE
Support object/host wise query

### ISSUE THREAD

**Issue by usdin** [scouter-project/scouter#431]
It would be nice if client/webapp could query counters/xlog/profiles for specific object or host. Right now client queries data for all the servers, it slows down if agent is deployed on many servers.  We might have to index objectname, hostname in database.
Any specific reason why we are not using other database like MySql or Mongo to store data.

**Comment by gunlee01** [comment]
There is no plan to diversify the Backend repository in Scouter in the near future.
It is aimed at a simple structure for developers to install and use in a hurry, and it can be expanded directly by creating user's own plug-in if necessary.
With the Scouter server plugin, you can save this data to another db or transfer it to another server when xlog, profile, text data, etc. are collected on the server.

Or you want these API's ?
https://github.com/scouter-project/scouter/blob/master/scouter.document/tech/Web-API-Guide.md

GET /v1/counter/realTime/{counters}/ofType/{objType}
GET /v1/counter/realTime/{counters}/ofObject/{objHash}
??
