### ISSUE TITLE
obj_type = java 인 경우 text1~text5 가 안 나옵니다.

### ISSUE THREAD

**Issue by nawhwan** [scouter-project/scouter#432]
obj_type = java (hook_service_patterns 이 정의된 경우) agent 에서 collector 로 text1~text5 가 전달이 안 됩니다.

TraceMain 에서 보면 endHttpServiceFinal 에는 pack.text1~text5 가 있는 데 endService 에서 보면 pack.text1~text5가 없어서 전달 안 되는 것으로 보입니다.

감사합니다.

**Comment by gunlee01** [comment]
resolved at v1.8.2
