### ISSUE TITLE
UDP Packet Size 초과 문제

### ISSUE THREAD

**Issue by gaiajeon** [scouter-project/scouter#433]
운영 중 발생한 문제입니다.

conf의 net_udp_packet_max_bytes가 60000로 되어 있지만
커널의 udp send buffer size가 적게 잡혀 있어서(9000정도)
 UDP 전송 클래스에서 Message Too Long  메시지를 남기면서 java.io.Exception이 발생했습니다.

설치 전 커널의 udp 전송 버퍼의 세팅값을 확인하도록 가이드 하거나
agent상에서 buffer size를 확인 후 net_udp_packet_max_bytes를 조정해야 할듯 합니다.

**Comment by gunlee01** [comment]
net_udp_packet_max_bytes 가 옵션으로 빠져있는 이유이기도 합니다.
관련 부분에 대해 가이드를 좀 보강할 필요가 있겠네요.
보통 커널에서의 기본값은 max 값인 64kb로 잡혀있을텐데
경우에 따라선 그게 아닐수도 있습니다.
적은 경우는 커널값을 늘여주는게 더 좋긴합니다.
scouter 설정을 줄이는 경우에는 udp packet을 더 잘게 쪼개서 보내게 되는데 그러며 유실의 확율이 더 높아지게 됩니다.
