### ISSUE TITLE
Unable to see method in profile

### ISSUE THREAD

**Issue by usdin** [scouter-project/scouter#438]
Hi, I am using following config, but I don't see method in x-log profile view. It shows only jdbc, http requests, tcp requests. Am I missing something. Also methods I want to see are autowired using spring annotations.

```
net_collector_ip:xxx
hook_method_access_public_enabled:true
hook_method_access_none_enabled:true
trace_interservice_enabled:true
xlog_patterned_sampling_step1_ms:50
xlog_patterned_sampling_step1_rate_pct:1
xlog_patterned_sampling_step2_ms:100
xlog_patterned_sampling_step2_rate_pct:5
xlog_patterned_sampling_step3_ms:1000
xlog_patterned_sampling_step3_rate_pct:25
xlog_patterned_sampling_over_rate_pct:100
obj_name:xxx
```

**Comment by bill23-kim** [comment]
Refer https://github.com/scouter-project/scouter/blob/master/scouter.document/use-case/Method-Profiling.md ~~

**Comment by usdin** [comment]
I've added
```
hook_method_access_public_enabled:true
hook_method_access_none_enabled:true
```
Shouldn't it profile every public and default methods.

**Comment by gaiajeon** [comment]
Can you write here your configuration file without modification?
(if you need, IP address and obj_name can replace with "xxx")

**Comment by usdin** [comment]
Above one is complete config file.
 Is adding ``hook_method_patterns`` is necessary? Is there any way to profile all public methods without passing them in config?

**Comment by gunlee01** [comment]
You should set the option `hook_method_patterns` for tracing methods.
and property name and value should be connected with a equals symbol(`=`) not a colon(`:`)
```properties
hook_method_patterns=mypkgstep1.mypkgstep2.MyClass.myMethod,mypkgstep1.mypkgstep2.MyClass.*
```

**Comment by gunlee01** [comment]
If you want to trace all public methods in specific package, just add options like below.

```properties
hook_method_patterns=pkg1.*.*
```
means It trace all classes's public methods which have the package name start with **pkg1.**

**Comment by onurmamati** [comment]
Having same problem here. my full scouter.conf file is below. Why I can't see methods execution times? 

scouter.enabled=true
net_collector_udp_port=6100
net_collector_tcp_port=6102
profile_http_querystring_enabled=true
profile_http_header_enabled=true
profile_http_parameter_enabled=true
profile_spring_controller_method_parameter_enabled=true
profile_summary_mode_enabled=true
profile_fullstack_hooked_exception_enabled=true
profile_method_enabled=true
_trace=true
_hook_methods_enabled=true
counter_custom_jmx_enabled=true

hook_method_patterns=com.mkyong.web.controller.*.*
hook_method_access_private_enabled=true
hook_method_access_protected_enabled=true
hook_method_lambda_enable=false
hook_method_access_public_enabled=true

sfa_dump_enabled=false

sql_enabled=true
_profile_fullstack_sql_connection_enabled=true
profile_fullstack_sql_commit_enabled=true

trace_interservice_enabled=true
xlog_patterned_sampling_step1_ms=50
xlog_patterned_sampling_step1_rate_pct=1
xlog_patterned_sampling_step2_ms=100
xlog_patterned_sampling_step2_rate_pct=5
xlog_patterned_sampling_step3_ms=1000
xlog_patterned_sampling_step3_rate_pct=25
xlog_patterned_sampling_over_rate_pct=100

**Comment by gaiajeon** [comment]
I think you should modify 
hook_method_patterns=com.mkyong.web.controller.. ==> hook_method_patterns=com.mkyong.web.controller.*.*

**Comment by onurmamati** [comment]
it is modified as *.* but can not see methods called.

7 Mar 2018 03:33 tarihinde "Hyanghee Jeon" <notifications@github.com> yazdı:

I think you should modify
hook_method_patterns=com.mkyong.web.controller.. ==>
hook_method_patterns=com.mkyong.web.controller.*.*

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/scouter-project/scouter/issues/438#issuecomment-370979628>,
or mute the thread

**Comment by gunlee01** [comment]
long pending closing.
On additional thread, reopen it plz.
