### ISSUE TITLE
client 1.8.3 윈도우 64bit 버전에서 perspective import export 이슈

### ISSUE THREAD

**Issue by sjilee** [scouter-project/scouter#443]
사용자별로 perspective를 꾸며서 제공해주려고 했는데 정작 perspective export해서  
해당 zip 파일을 다른 PC에서 import해보니 load가 안되더라구요. 
물론 import success 라고는 나오고 재기동도 했지만 perspective 목록에도 보이지 않았습니다. 

원인을 찾다가 export된 zip파일의 구조를 보니 사용자별로 아래와 같이 백업되어 있던게 보이던데
결과적으로 다른 PC윈도우에서 계정이 다르면 import 해도 해당 경로문제때문에 적용이 안되는게 아닌가 생각되네요. 
C:\Users\Administrator\scouter\export-working
![image](https://user-images.githubusercontent.com/36728616/37511660-0220ef60-2943-11e8-9892-5f0b61950e45.png)
혹시 이 문제가 아니라면 Fix 된 버전좀 알려주세요.

**Comment by gunlee01** [comment]
음.. 캡쳐된 이미지 처럼 묶이는 것은 문제가 있네요. 좀 확인해 봐야 할 듯 합니다.
일단 수작업으로 하시려면
압축을 푼다음에 export-working 디렉토리안에서 다시 zip 파일로 압축을 한후에 
import를 해보시기 바랍니다.

혹은 scouter 디렉토리내에 들어가 보면 압축파일과 동일한 구조로 구성되어 있습니다. 거기다 압축을 해제한 파일들을 복사하여도 됩니다.

**Comment by sjilee** [comment]
알려주신 방법으로 export된 zip 파일을 다시 풀어서 export-working 경로 안에서 압축 묶은 파일로 import해보니 잘 되었습니다. 이렇게 두번 작업하는게 정상은 아닌듯 한데요. 이 부분 혹시 수정되면 클라이언트 버전 알려주세요.

**Comment by gunlee01** [comment]
이 부분은 테스트후 수정예정입니다.

**Comment by gunlee01** [comment]
resolved at v1.8.4
