### ISSUE TITLE
DB Pool 갯수 현황을 모니터링 하는 기능은 아직 없는거죠? 

### ISSUE THREAD

**Issue by sjilee** [scouter-project/scouter#444]
타 APM 툴 대비해서 DB Pool 갯수 현황을 모니터링하는 기능은 없는거 같던데 맞나요?
Leak 찾아주는 부분은 있는거 같던데 혹시 DB Pool 갯수 모니터링도 도입할 예정이 있을까요?

**Comment by gunlee01** [comment]
tomcat의 DBCP Pool에 대해서만 모니터링이 됩니다.
추가적으로 다른 WAS 제품에 대해 기능을 추가할 계획은 없습니다.
