### ISSUE TITLE
API level elapsed time

### ISSUE THREAD

**Issue by usdin** [scouter-project/scouter#445]
Is there any way to view Elapsed time with respect to which url was hit. Also I believe for xlog-profile sampling we should also consider API.

**Comment by gunlee01** [comment]
There are several summaries on the collector's context menu .
It shows average response time of service, api call and SQL by given time range.

And could I know detailing of xlog-profile sampling ?

**Comment by usdin** [comment]
Thanks, I wasn't aware of that. One question, are data in summary are sampled data or scouter captures response time of every requests.
Also by xlog profile sampling I meant if there is API which is hit rarely, chances are it's profile would never get captured.

**Comment by gunlee01** [comment]
If xlog sampling options are configured, the summary is evaluated with whole transactions.
