### ISSUE TITLE
XLog 기능 추가 제안

### ISSUE THREAD

**Issue by cowboy93** [scouter-project/scouter#446]
장애가 났을 때 원인이 되는 request 를 찾기 위해서,
XLog filter 에 
시작시간 filter 를 추가해 주시면 좋겠습니다. 

![image](https://user-images.githubusercontent.com/175918/37939763-a072a852-319f-11e8-9daf-e816636834f8.png)
이와 같은 상황에서 원인이 되는 것은 장애가 시작될 때 시작된 request 거든요. 
여기서 원인되는 요청을 찾아야 하는데, 시작시간으로 filter 를 걸어주면 보다 빠르게 원인을 찾을 수 있을 것 같아요.

**Comment by gunlee01** [comment]
좋은 아이디어 감사합니다. ^^
있으면 장애 원인 분석에 도움이 될만한 기능이네요.
다음 버전에 반영 검토하겠습니다.

**Comment by gunlee01** [comment]
resolved at v1.8.4
