### ISSUE TITLE
v1/counter/HeapTotUsage/latest  RestAPI 결과 값 미표현

### ISSUE THREAD

**Issue by GeunhoLee** [scouter-project/scouter#461]
버전은 1.8.4.1 입니다

/v1/counter/realTime/{counters} api는 정상적으로 값 표현이 되나

아래 이미지와 같이 HeapTotUsage counter 값이 0으로 표기 됩니다.
(v1/counter/stat/HeapTotUsage api 도 동일하게 표현 안됩니다.)

![image](https://user-images.githubusercontent.com/37397013/38846802-46e55dca-4239-11e8-94e6-aec47d12ef25.png)

**Comment by gunlee01** [comment]
HeapTotalUsage 대신 HeapTotal, HeapUsed를 각각 사용해 보세요.

**Comment by GeunhoLee** [comment]
답변 감사합니다. 해당 API로 두 정보를 가져오고 싶었는데 아쉽네요. ㅠ
