### ISSUE TITLE
issue with scouter APM

### ISSUE THREAD

**Issue by malluvenu** [scouter-project/scouter#462]
Hi Team,

I have downloaded and installed scouter in my machine and trying to server to scouter dashboard and i am unable add it, please provide me the solution like how to add server to the dashboard.

Regards,
Venu

**Comment by gunlee01** [comment]
Hi. malluvenu.
![image](https://user-images.githubusercontent.com/6788732/39091339-2b94867a-462d-11e8-808c-b9927802ab39.png)
I wish it helps you
