### ISSUE TITLE
클라이언트에서 Agent, Server 옵션 수정 시 \ 가 포함되어 있으면  \가 늘어나는 현상

### ISSUE THREAD

**Issue by GeunhoLee** [scouter-project/scouter#464]
[
![default](https://user-images.githubusercontent.com/37397013/39220507-90a992c6-486c-11e8-8726-f9fbae1ca5cf.png)
](url)
해당 이미지는 \가 들어간 옵션을 설정하고 저장한 이미지 입니다.

[
![5](https://user-images.githubusercontent.com/37397013/39220515-99cf773a-486c-11e8-816f-0474891a3007.png)
](url)

summary_enabled 옵션을 true, false 순으로 5번 수정하여 저장한 이미지.

위 이미지와 같이 옵션에 \가 들어가 있을때 클라이언트에서 옵션을 수정하게되면 \가 늘어나는 현상이 있습니다.

클라이언트에서 \ 치환 문제 인거 같습니다.

**Comment by gunlee01** [comment]
fixed. v1.8.6
