### ISSUE TITLE
[의견] 클라이언트에서 add server 시 Xlog 창 자동 추가

### ISSUE THREAD

**Issue by kuil09** [scouter-project/scouter#466]
안녕하세요. 스카우터 클라이언트에서 여러개의 콜렉터 서버를 사용할 때 콜렉터 서버 추가 시 발생하는 사소한 이슈에 대해서 의견 드립니다.

새로 추가된 서버의 수집된 로그가 기존 퍼스펙티브에서는 표시가 안되는 증상이 있는데요.
추가 된 서버가 퍼스펙티브에 바로 반영되면 제일 좋을 거 같고,
그렇지 않을 경우에는 서비스 퍼스펙티브를 닫고 다시 열라고 가이드를 클라이언트 단에서 주면 좋을 거 같습니다.

**Comment by kuil09** [comment]
콜렉터 서버가 추가 될 때 디폴트 서버를 바꿀 것인지 물으면 좋을 거 같네요.

아니면 혹시 별개의 퍼스펙티브를 호스트 서버 별로 추가할 수 있는지요.

**Comment by gunlee01** [comment]
@kuil09 
scouter는 콜렉터서버가 가장 기본이 되는 단위입니다.
클라이언트에서 멀티서버를 이용하는 경우 일반적으로는 퍼스펙티브를 나누어 view를 구성합니다.

새로운 서버를 추가하였다면 보고 싶은 형태로 view들을 배치한 후에 이를 `save as...` 하여 저장하여 여러 퍼스펙티브를 구성하여 사용합니다.

저 같은 경우는 각 시스템명으로 obj_type을 설정하고 obj_type별로 퍼스펙티브를 구성해 사용하는 편입니다.
(scouter의 view가 obj_type 을 기준으로 차트를 보여주므로...)

아래 링크글의 2-2 쪽 두번째 그림(gif)를 보면 퍼스펙티브를 각 시스템별로 구성해 놓은 것을 보실 수 있습니다.
https://gunsdevlog.blogspot.kr/2017/07/scouter-apm-basic-monitoring-2.html
