### ISSUE TITLE
scouter 개발 환경 셋팅 시  pom.xml 오류 건

### ISSUE THREAD

**Issue by kidmam** [scouter-project/scouter#470]
<img width="718" alt="2018-05-15 1 24 11" src="https://user-images.githubusercontent.com/33748988/40036614-7710ca32-5843-11e8-916f-949e8761683e.png">

jdk 1.8.0_20, Maven 3.5.0, Eclipse Oxygen 개발 환경 구축 시 pom.xml에서 아래와 같은 오류가 발생합니다.

Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.3.2:add-source (execution: scala-compile-first, phase: process-resources)

별다르게 이상한 부분은 없는데요.
조언 부탁합니다.

**Comment by gunlee01** [comment]
scala 관련 모듈들이 없어서 그럴것 같기도 합니다.
개발 환경 구성은 아래 링크를 참고해 보시기 바랍니다.
https://gunsdevlog.blogspot.kr/2017/10/scouter-apm-developer-environment.html

**Comment by kidmam** [comment]
<img width="1355" alt="2018-05-16 7 07 22" src="https://user-images.githubusercontent.com/33748988/40086164-2a7b0792-58d8-11e8-8be5-e3270cd8d61f.png">

답변 감사합니다.
설치 가이드대로 했는데, scala-maven-plugin 부분에서 오류가 발생합니다. ㅠㅠ

Eclipse Oxygen, STS 3.9.4 동일하게 발생합니다.
혹시 Maven settings.xml 파일 공유 가능할까요?
Eclipse NEON으로 한 번 설치해겠습니다.
감사합니다.

**Comment by kidmam** [comment]
<img width="1385" alt="2018-05-16 8 03 12" src="https://user-images.githubusercontent.com/33748988/40087927-bde846aa-58df-11e8-9ace-983ef39672fc.png">

Eclipse NEON3에서도 동일한 오류가 발생합니다. ㅠㅠ

**Comment by gunlee01** [comment]
위에 있는 개발환경 구성 문서는 작년에 스카우터 스프린트 세션에서 사용했던 문서인데요
그때 참석자들이 이클립스에 개발환경을 구성하고 기능 개발을 진행했었는데 별 문제된 사람은 없었습니다.

확실하지는 않으나 첫번째 올리신 글과 비슷한 에러가 발생한 사례인데요 한번 참고해보세요.
https://stackoverflow.com/questions/13416264/maven-scala-plugin-giving-pom-file-error

예전에 비슷한 경우가 있었던 것 같은데 그때는 clean하고 eclipse 재시작한 후 된 것 같기도 하고요... ^^

**Comment by kidmam** [comment]
http://scala-ide.org/docs/tutorials/m2eclipse/index.html
일단 m2eclipse-scala를 설치하면 scouter-server/pom.xml에서 오류는 나지 않습니다.
단, <goal>add-source</goal> 에서 오류가 발생해서 주석 처리했습니다.

이상하게 저만 이렇게 어렵게 셋팅이 되었는지 모르겠습니다. ㅠㅠ
scouter-parent/pom.xml에서 maven-javadoc-plugin 부분 주석처리하고,
byte-buddy-nodep-scouter-repack-1.7.1.RC1.jar ./m2/repository/com/github/scouter-project/byte-buddy-nodep-scouter-repack/1.7.1.RC1/ 복사 후 mvn clean package해서 가까스로 성공했습니다.

빠른 답변 덕분에 어려웠지만, 일단 개발 환경 구성 완료했습니다.
기회가 된다면 열심히 활동하도록 하겠습니다.
감사합니다.

**Comment by gunlee01** [comment]
👍
