### ISSUE TITLE
 log list 세부 내용 altisbase sqlmap문제 문의

### ISSUE THREAD

**Issue by leeyongsuk** [scouter-project/scouter#471]
제목수정이 안되네요 ㅠ ㅠ altibase 디비 입니다

안녕하세요 scouter 를 사용해서 모니터링을 해볼려고 합니다.실서버에 설치해서 사용 중에 sql이 나오지 않고 sqlmap이 나오며 메소드 장보만 출력 문제해결방법이 있을까요?
was는 jeus6이고 db는 altibase,scouter는 1.8.5를 사용중입니다  xlog에서 트랜잭션을 클릭해서 세부내용을 보면 실행한 sql문이 보이지 않고 sqlmap이라는 문구와 함께 수행한 소스코드의 메소드 정보가 나옵니다 해결방법이 뭐가 있을까요?agent 설정을 추가하면 되는 걸까요?
altibase의 jdbc드라이버는 첨부가 안되네요 ㅠ ㅠ

**Comment by gunlee01** [comment]
사용중인 altibase jdbc driver를 통해 sql 추적이 안되는 현상일듯 합니다.
현재 알티베이스의 쿼리를 추적하는 class는
Altibase/jdbc/driver/AltibasePreparedStatement
Altibase/jdbc/driver/AltibaseStatement
이 두가지입니다.

**Comment by leeyongsuk** [comment]
![altibase](https://user-images.githubusercontent.com/305611/40096725-165772e8-590d-11e8-9e0d-527fa123db55.jpg)

드라이버 파일 첨부합니다
파일업로드가 안되어서 확장자를 변경해서 올립니다
확장자를 jar로 변경하면 확인 가능합니다

ㄱ

**Comment by leeyongsuk** [comment]
해결했습니다 드라이버의 소스를 보니 다른 방식으로 네이밍 되어있어서 agent 옵션에 추가 하였습니다 내용은 정리해서 올리겠습니다

**Comment by leeyongsuk** [comment]
cubrid xlog sql 프로파일링 문의 · Issue #96 · scouter-project/scouter - https://github.com/scouter-project/scouter/issues/96

위의 이슈 케이스를 참조하여 해결하였습니다

결론 : agent 설정 추가
#JDBC Driver Hook
hook_jdbc_pstmt_classes=Altibase.jdbc..driver.ABPreparedStatement
hook_jdbc_stmt_classes=Altibase.jdbc.driver.ABStatement
hook_jdbc_rs_classes=Altibase.jdbc.driver.ABResultSet


Altibase.jar드라이버의 클래스 파일을 확인 결과 기존 네이밍과 다르게 사용중인 것을 확인하였습니다
첫번째 설정 시에는 대소문자 구분을 하는지 모르고 설정을 추가하였는데 대소문자를 구분해주니 SQL이
출력되는 것을 확인 할 수 있었습니다

**Comment by gunlee01** [comment]
다음 버전에 default로 추가 예정입니다.
