### ISSUE TITLE
Customizable Alert 설정 관련 질문 드립니다.

### ISSUE THREAD

**Issue by youngha0711** [scouter-project/scouter#473]
Customizable Alert에 특정 알림을 설정하여 Scouter Client의 Alert 영역에 알림을 노출시키고자 하는데요.

하기에 기재해드린 URL을 참고하여 설정을 진행하였으나, 알림이 오지 않아 추가적으로 필요한 설정이 있는지 문의 드립니다.

https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Alert-Plugin-Guide.md

**Comment by gunlee01** [comment]
특별히 추가로 설정할 것은 없습니다.
아래 조금 더 쉽게 설명된 글이 있으니 참고해 보세요.

http://gunsdevlog.blogspot.kr/2018/05/scouter-customizable-alert.html

**Comment by youngha0711** [comment]
답변 감사합니다.

덕분에 Alert 영역에 알림 노출되도록 설정 되었습니다. ^^
