### ISSUE TITLE
GlobalExceptionHandler 에서 잡아서 정상처럼 리턴하는 에러에 대해서 에러 표시를 해줄 수 있을까요??

### ISSUE THREAD

**Issue by hahehiho** [scouter-project/scouter#475]
안녕하세요. 
spring 에서 GlobalExceptionHandler 를 잡아서 requestbody 에 에러를 표시해서 http status code를 200으로 해서 리턴을 하는 경우에
xlog 에 정상으로 나오고 있는데요..
이런 경우에도 ExcpetionHandler에서 scouter 에 이 trasaction 은 실패다 라고 코딩할 수 있는 방법이 있을까요??

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
