### ISSUE TITLE
특정 error message 알림 기능

### ISSUE THREAD

**Issue by nawhwan** [scouter-project/scouter#476]
error 에 특정 문자열 (예 xxx 호출 오류) 이 있는 경우 Alert 에 표시하는 기능을 구현하고자 합니다.

xlog.plug 를 이용하여 원하는 오류 문자열을 잡을 수는 있는 데 오류가 발생하는 Tx가 많으면 Alert 가 너무 많이 나오네요.

xlog.plug 에서 $$.alertError 를 호출하는 데, 예를 들면 5분전에 같은 alert 가 있는면 alert  하지 않는 기능이 있으면 좋을 듯 합니다.

**Comment by gunlee01** [comment]
그런 기능은 현재 없습니다 향후 추가에 대해서는 고려해 보도록 하겠습니다.

복잡한 처리를 하기 위해서는 Scripting 방식 plugin 보다는 built-in plugin 방식을 사용해 보시기 바랍니다.
built-in plugin을 통한다면 이전 알림을 체크하여 발송하는 로직은 어렵지 않게 구현하실 수 있을 듯 합니다..
 * Map등의 컬렉션을 전역 변수를 선언하고 거기에 알림 시간과 제목 등(알림 발송을 어떤 기준으로 snooze 할 것인지에 따라 필요한 단위로)을 함께 저장한 다음에 체크하여 발송하는 식으로 구현.
 * Builtin plugin에서는 $$로 사용하던 helper object는 PluginHelper.getInstance() 로 접근할 수 있습니다.
