### ISSUE TITLE
Custom Mbean에서 obj_type 이 이미 있는 경우

### ISSUE THREAD

**Issue by nawhwan** [scouter-project/scouter#477]
https://github.com/scouter-project/scouter/blob/develop/scouter.document/main/Custom-MBean-Counter.md

에서 기존에 obj_type=tomcat 으로 되어 있는 경우  obj_type=cassandra 를 주면 오류나는 데... 어떻게 해야 하나요?

**Comment by bill23-kim** [comment]
predefine(tomcat,java,jboss,jetty) 되어있는 obj_type 외에 새로운 obj_type 을 설정하는 경우 Define Object Type 메뉴를 통해 새로운 obj_type 을 정의 해주고(family : javaee) 차트를 다시 열어 주어야 합니다. 차트를 한번에 바꾸시고 싶으시면 Window -> Preference 에서 default javaee 타입을 새로 정의한 obj_type 으로 설정하면 한번에 화면이 새로운 obj_type 에 맞추어 리셋이 됩니다.
