### ISSUE TITLE
Customizable Alert을 통하여 xLog의 Error로 기록되는 것을 알림 오도록 설정하고 싶습니다.

### ISSUE THREAD

**Issue by youngha0711** [scouter-project/scouter#479]
Customizable Alert을 통하여 xLog의 Error로 기록되는 것을 알림 오도록 설정하고 싶은데요.

javaee : Active Service를 활용하면 될까요?

만약 해당 알림을 설정하여 알림을 받을 수 있다면
어떤 서비스 호출 시 어떤 에러가 발생하였는지 받을 수 있을까요?

Api Help를 참고해보았지만 서비스명 및 에러 내용을
가져오는 Api는 존재하지 않는 것 같습니다.

확인 부탁 드립니다.

감사합니다.

**Comment by gunlee01** [comment]
Customizable alert는 카운터 값을 통해 알림 설정을 할 때 사용하게 됩니다.
특정 xlog error 시에 알림을 발송하려면 scouter server plugin을 제작하여야 하며
아주 간단한 처리가 아니라면 built-in plugin으로 제작하여야 합니다.
plugin을 만드는 것은 그리 어렵지 않으니 아래 링크를 참고해 보시기 바랍니다.

https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Plugin-Guide_kr.md

이 중 xlog plugin을 통해 원하시는 기능 구현이 가능할 것으로 생각됩니다.
파라미터로 전달되는 XLogPack에서 error 여부를 판단하고
PluginHelper 클래스(`scouter.server.plugin.PluginHelper`)를 통해 XLogPack 속성의 각 hash 값들을 문자로 변환할 수 있으니 이를 활용하여 service 명 및 error message를 구하면 됩니다.
```java
scouter.server.plugin.PluginHelper#getErrorString(java.lang.String, int) //error 값은 날짜별로 dictionary가 구성되므로 날짜 조건 필요
//날짜는 아래 유틸로 구할 수 있음. scouter.util.DateUtil#yyyymmdd()
scouter.server.plugin.PluginHelper#getServiceString(int) //등...
```
그리고 pluginHelper의 alert 메소드를 사용하여 알림을 줄 수 있습니다.
```java
scouter.server.plugin.PluginHelper#alertError(int objHash, String objType, String title, String message)
scouter.server.plugin.PluginHelper#alertFatal(int objHash, String objType, String title, String message) //등...
```
https://github.com/scouter-project/scouter/blob/master/scouter.server/src/main/java/scouter/server/plugin/PluginHelper.java

**Comment by wangli777** [comment]
Hello，I have a question about this method： _scouter.server.plugin.PluginHelper#getServiceString(int)_ ，what exactly is the param 'int' is ? Thanks！
