### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [scouter-project/scouter#480]
Can i update the logo and the banner in Read me ?

**Comment by gunlee01** [comment]
That seems very nice. :)
You can make PR then our team will review it.

**Comment by loydjayme25** [comment]
Do you have any comments or suggestions about this one ?

![scouter](https://user-images.githubusercontent.com/37318022/41141857-1fc5663e-6b26-11e8-9db0-2fb0e30d9f91.png)

**Comment by loydjayme25** [comment]
I will submit a PR, i am currently making sizes.

**Comment by loydjayme25** [comment]
or how about this one ?

![scouter-1](https://user-images.githubusercontent.com/37318022/41144227-ca9b0e4e-6b2e-11e8-8662-4777c0535443.png)

**Comment by gunlee01** [comment]
The logo is important to indicate the identity of the product.
scouter is a real-time performance monitoring tool that is a simple, uncomplicated tool, and it emphasizes speedy presentation of key information.
The "S" shape of the logo has the same shape as the line chart when viewed horizontally with the initials of the scouter.
In addition, the lightning-fastened parts on the left and right are parts that emphasize promptness.
We would like you to use these parts well, and would rather have a plain design than a three-dimensional feeling.
I will let you know the opinions of commiters.

**Comment by loydjayme25** [comment]
I can add a lightning on my design

**Comment by gunlee01** [comment]
In our opinion, it would be better to look more modern and sophisticated without big changing the shape of the current logo.

**Comment by gunlee01** [comment]
@loydjayme25 It's very good and simple enough to indicate scouter at a glance.
It feels so good but a logo is important thing in a product, so logo choice is very sensitive thing.
Could you show us some more logo samples to help us to decide it ?

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
