### ISSUE TITLE
custom alert 의 heapTotUsage 문의

### ISSUE THREAD

**Issue by hahehiho** [scouter-project/scouter#481]
안녕하세요.

Heap Used 로 custom alert 을 만들려고 합니다.
전체 heap 설정 중 %로 메시지를 주고 싶은데요.. 아래처럼 작성하니 HeapTotUsage 값이 0으로 나오고 있습니다. 혹시 -Xmx 로 설정한 값을 가져올 수 있는 방법이 있을까요??

// void process(RealCounter $counter, PluginHelper $$) {

String objName = $counter.objName();
int heapTotalUsage = $counter.intValue("HeapTotUsage");
int heapUsage = $counter.intValue();

//$$.log("[debug log][heap]" + ":" +  objName + "," + heapTotalUsage + "," + heapUsage);

if(heapTotalUsage != 0) {

	int pct = (heapUsage*100)/heapTotalUsage;

	String title = objName + " Heap Report";
	String msg = "Current : " + pct + "% (" + heapUsage + "MB/" + heapTotalUsage + "MB)";

	if(pct >= 75 && pct < 80) {
		$counter.warn(title, msg);
	} else if(pct >= 80 && pct < 95) {
		$counter.error(title, msg);
	} else if(pct >= 95) {
		$counter.fatal(title, msg);
	}
}
// }

**Comment by gaiajeon** [comment]
-Xmx 설정은 실제로 할당 되는 heap 량이 아니고 최대로 사용할 수 있는 heap의 용량입니다.
따라서 힙 사용량을 계산하기 위해 -Xmx 설정값을 가져올 필요는 없습니다.

HeapTotUsage값이 0으로 오는 문제를 먼저 분석하시는 것이 좋을 듯합니다.
데이터의 자료형이 int형인지 등등을 확인해보는 것이 좋지 않을까 합니다.

**Comment by gunlee01** [comment]
HeapTotUsage는 숫자만으로 이루어지지 않은 조금 특이한 형태의 메트릭 입니다.
따라서 위와 같은 형태로 사용할 수 없습니다.
대신 현재 Heap의 최대값을 가져오려면 HeapTotal 을 사용하세요.
