### ISSUE TITLE
Slack Plugin 여러 채널 알림 기능을 위한 Group 단위 문의

### ISSUE THREAD

**Issue by passionlim** [scouter-project/scouter#482]
안녕하세요. Scouter 사용 중에 Group 관리 관련하여 문의 드립니다.

현재 Scouter 와 Slack 알림을 잘 사용하고 있고 가이드에 맞춰 custom 알림등을 추가하고 있습니다.
다만 Slack Plugin  (https://github.com/scouter-project/scouter-plugin-server-alert-slack) 의 경우 하나의 채널에 대한 알림이 가능하기 때문에 여러 비지니스 시스템이 하나의 Collector 에 모여 있는 경우 알림을 분할하는데 어려움이 있네요.. 물론 Collector 를 분리하는 방법도 있기 하지만 가능하면 Collector 를 여럿 둬서 관리대상 시스템을 늘리는 것을 지양하고 있습니다.

scouter client 의 group 관리를 사용해 보려 했지만 client 에만 저장되는 내용이므로 server plugin 에서는 그 정보를 활용할 수 없다는 것을 확인하였습니다.

알림의 기준인 AlertPack 내에는 obj_type, obj_name 정도라 대상들을 알림 대상을 그룹 지을 수 있는 정보가 없네요. Collector Server 상에서 관리기준(비지니스 단위)당 group 을 만들 수 있는 방법이 있을까요? 

https://github.com/scouter-project/scouter/issues/466
에서 @gunlee01 님의 답변을 보면 obj_type 을 별도로 group 처럼 활용할 수 있는 것 같은데.. 이것을 group 으로 이용할수도 있나요~?

**Comment by gunlee01** [comment]
Slack Plugin에는 그런 기능은 없으나, 이 Plugin을 기반으로 수정하여 제작하면 가능합니다.
파라미터로 넘어가는 AlertPack에 objHash 와 objType 속성이 있으니,
필요하다면 obj_type으로 시스템을 구분하여 설정하고 제작한 플러그인에서 특정 룰에 따라 분기하여 처리하면 되겠네요.

예를 들어 설정값을 ext_myslack_{objType}_webhook_url 등으로 여러개를 설정하고
이를 Configure#getValue 등의 메소드로 읽어서 분기 처리하는 방식도 좋을 것 같습니다.

**Comment by gunlee01** [comment]
아 아래 추가 질문에 답변드리면 Group별로 나누어진 화면을 보는게 목적이라면 obj_type을 group의 용도로 사용이 가능합니다. (이런 경우 보통 obj_type을 시스템명으로 사용합니다. order_jvm, order_host 같은 식으로.)
https://gunsdevlog.blogspot.com/2017/07/scouter-apm-2-12.html
위 글에서 object family와 object type을 참고해 보시기 바랍니다.

**Comment by passionlim** [comment]
merge 됐네요. 감사합니다.  group 설정은 prefix 방식으로 적용하였습니다. 그게 collector 설정에서 묶어서 보기 좋을 것 같습니다.

**Comment by passionlim** [comment]
해당 요청은 다행시 merge 되었는데요.
하지만 버전이 RELEASE 되지 않아 아쉽습니다. 1.0.1 해주실 수 있을까요~?
( https://github.com/scouter-project/scouter-plugin-server-alert-slack/issues/6 ) 
@gunlee01
