### ISSUE TITLE
필리핀 적용중입니다. daliy  data 조회시 0~9시 까지 모든 data가 안보이네요.

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#486]
안녕하세요~
아래 질문에 이어 두번째 질문 드립니다.

국내와 해외에 적용을 해서 아주 잘 사용하고 있습니다.
이번 이슈는 필리핀에 적용해서 사용하는 scouter 인데요. realtime은 잘 나옵니다.
Load Daily All 조회시 00시~09시 까지 data만 안보이네요.

1 day time 조회하면 아래 화면처럼 00시~09시 조회가 안되네요.
<img width="1010" alt="2018-07-25 3 28 56" src="https://user-images.githubusercontent.com/41562733/43183447-2720aafa-9020-11e8-973a-f284bdd033e6.png">

7days time 조회하면 동일하게 00시~09시 조회가 안되지만 그외에 6일이상은 모두 정상적으로 노출됩니다.
<img width="1006" alt="2018-07-25 3 28 44" src="https://user-images.githubusercontent.com/41562733/43183456-2c824440-9020-11e8-9b7a-7ca3a0e75888.png">

locale 은 KST 이고 Time은 필리핀 agnet 가 Asia/manila인데, 시간차는 1시간 입니다.
Time zone 문제는 아닐듯 한데..
혹.. 이번 이슈 관련되서 추측 가능한 부분이 있으면 조치할 수 있는 방법이 있지 않을까요~?
국내는 모두 잘 나옵니다

**Comment by bill23-kim** [comment]
스카우터 서버가 설치 되어있는 곳에 타임존이 UTC 로 되어있는거 아닌가요? 스카우터 서버와 클라이언트는 타임존을 맞춰야 합니다.

**Comment by wasgosu** [comment]
네.. 확인해보니 서버도  KST로 구성되네요.
다른 의심스러운 부분은 없을까요?

**Comment by bill23-kim** [comment]
음.. 9시간 차이나는거보면 딱 UTC 와 KST 차이인데요, 생각해보니 반대로 서버가 KST 이고 클라이언트가 UTC 일때 딱 저렇게 나올것 같은데 클라이언트 타임존이 KST 가 맞나요?

**Comment by wasgosu** [comment]
네.. 아쉽게도 둘다 KST 가 맞습니다.
둘다 AWS로 서버 구축하면서 KST로 구성했고 리얼타임 잘나와서 신경안썼는데, 과거 조회할때는 일주일이던 하루던 무조건 0~9시 까지 data만 안보이네요.
7일치 보면 data가 있는건 확인되는데, 왜 그러는지 잘 모르겠어여 ;

**Comment by bill23-kim** [comment]
먼가 타임존이 꼬인것 같은데 어느부분인지 모르겠네요. 참고로 서버는 오브젝트뷰에서 서버 우클릭 -> properties 에서 확인 가능하고 클라이언트 제일상단 타이틀에 버전명(타임존) 으로 확인 가능합니다.
