### ISSUE TITLE
Xlog History CSV Export 기능 문의드립니다.

### ISSUE THREAD

**Issue by king1975** [scouter-project/scouter#488]
안녕하세요. 
혹시 다음 기능이 지원되는지, 지원이 안되면 파일 db에서 가져올수 있는 방법이 있는지 문의드립니다.

전일 xlog 데이타를 csv 로  export 하고자 합니다.
그래프상 조회는 되는데 상세 정보를 보려면 마우스 드래그만 가능하고, 그것도 한계가 있어서요.
전체 history 데이타를 csv로 export 할수 있는 방법이 있는지 문의드립니다.

감사합니다.

**Comment by gunlee01** [comment]
화면상에서 전체 데이터 export는 지원하지 않습니다.
WEB API를 사용하여 정보를 받을 수는 있습니다. 단 한번에 조회되는 건수의 최대값이 있으므로 결과에 보여지는 offset을 다음 요청시 파라미터에 포함하여 요청하는 것을 반복적으로 수행하도록 구현을 하여야 합니다.

API는 아래 swagger 주소와 소스를 참고하시기 바랍니다.
* SWAGGER : http://demo.scouterapm.com:6180/swagger/index.html#!/XLog32data/streamPageableXLog

 * API 소스 : https://github.com/scouter-project/scouter/blob/master/scouter.webapp/src/main/java/scouterx/webapp/layer/controller/XLogDataController.java#L158

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
