### ISSUE TITLE
스카우터 서버 혹은 웹 API의 버전을 알 수 있는 API가 있을까요?

### ISSUE THREAD

**Issue by mindplates** [scouter-project/scouter#489]
스카우터 PAPER를 만드는데, 하위 버전의 호환성을 보장하기 위해, 서버들의 버전을 알아야 필요가 종종 있습니다.
특정 기능의 존재 여부로 파악하긴하는데, 이게 종종 기능 존재 여부로만 판단하는 범위보다 세분화되서, 분기 처리할 필요가 있기도해서요.

**Comment by gunlee01** [comment]
develop 브랜치에 반영되었습니다.
기존 server API의 결과에 추가되었습니다.
Demo 페이지에 아래 요청으로 결과 확인이 가능합니다.
http://demo.scouterapm.com:6188/scouter/v1/info/server
