### ISSUE TITLE
한 서버에 collector 2대 기동 가능한가요?

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#491]
안녕하세요.. 
한 서버에서 collector 2대 기동이 안되는데.. 별도 방법이 있을까요?
무조건 6100 으로만 기동되네요.
server/conf/scouter.conf 설정에 6200 추가하고 기동해도 정상적으로 port  기동이 안되서요..
net_collector_ip=10.10.10.10
net_collector_udp_port=6200
net_collector_tcp_port=6200

한 서버당 한대의 collector만 구동 가능한 건지.. 문의드립니다.

**Comment by gunlee01** [comment]
음 다른 디렉토리에 copy하여 한 벌 더 만든 후에 설정에서 포트를 변경하여 기동하면 될 텐데요
어떻게 작업하신 건가요?

**Comment by wasgosu** [comment]
답변이 늦었네요.. 
우선 말씀하신 방법으로 구성해봤습니다.

저는 한 서버에 두 대의 컬렉터 서버를 기동했습니다.
하나는 udp 6100, 또 다른 하나는 udp 6200.. 두 개의 컬럭터서버는 기동은 됐는데, 제가 원한 그림은 아니였어요..

제가 원하는 이미지는 openserver 를 각각 해서 6100은 운영용으로 사용하고, 6200은 dev용으로 쪼개고 싶었던건데..
hostname이 동일해서 그런지 로그인을 둘다 각각 해도 연결되는 agent 는 동일한 장비가 보이네요.
agent 연결port는 6100으로 해놨는데 설정이 안먹는건지.. 한 서버에 두개의 컬랙터 서버로 각각 로그인해서 운영할 수 있는 방법이 있을까요? 
혹..아시게 되면 알려주세요. 전 이래저래 해봤는데 잘 안되네요.

<img width="446" alt="2018-08-27 4 42 25" src="https://user-images.githubusercontent.com/41562733/44648945-8fe93900-aa1d-11e8-8829-26cb44cc2de5.png">
<img width="432" alt="2018-08-27 4 44 01" src="https://user-images.githubusercontent.com/41562733/44648965-97a8dd80-aa1d-11e8-9526-22b25f046587.png">

**Comment by gunlee01** [comment]
말씀하신 방법으로 종종 사용하는데요.. 특별한 설정이 필요한 것은 아닌데 좀 이상하네요. 
제대로 연결이 되었는데 client에서 보여줄때 이름이 동일하여서 잘못 보여주는 경우일 수도 있을 듯 합니다.
아래 처럼 적용해 보세요.

scouter를 다운 받아 압축을 풀면 `scouter/server` 라는 디렉토리가 생깁니다.
여기서 `./server`를 다른 경로로 하나 복사합니다. 예를 들면 `./server2`로 복사합니다.
그리고 `./server/conf/scouter.conf` 에는 다른 부분은 수정하지 말고 `server_id=my-scouter-server1`로 설정합니다.
그리고 `./scouter2/conf/scouter.conf` 에는 다음과 같이 설정합니다.
```properties
server_id=my-scouter-server2
net_udp_listen_port=6200
net_tcp_listen_port=6200
```
그리고 각각 실행후에 client를 다시 실행하여 붙여 보세요.

**Comment by wasgosu** [comment]
조만간 테스트 해보고 결과 올려보겠습니다~
