### ISSUE TITLE
특정 error로 표시되는 "Read timed out" 만 xlog에서 안보게 할 순 없을까요?

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#496]
안녕하세요~

xlog_discard_service_patterns= 옵션으로 /healthcheck 옵션은 무시하게 해서 잘 사용 중 입니다.
그걸 응용해서 xlog 에 Read timed out 에러 발생시 xlog 에 안보이게 하고 싶은데요.. 
해당 기능은 없을까요?

# agent 에 정의된 xlog에 해당 기능은 없는것 같아서요..
<img width="496" alt="2018-09-03 11 15 26" src="https://user-images.githubusercontent.com/41562733/44964318-c1f12280-af6a-11e8-9e55-09b9f7c387da.png">

## xlog 내용
    -    [000000] 11:04:21.583        1      0  call: /gcm/send 5,005 ms [gcm-http.googleapis.com:-1] <x38e85e9ig5f61>
Read timed out
    -    [000001] 11:04:26.588    5,005      0  call: /gcm/send 0 ms [gcm-http.googleapis.com:-1] <x1otf43rqdj3bl>
Read timed out

**Comment by bill23-kim** [comment]
그런조건으로 xlog 를 안보이게 할 수는 없습니다. 외부 API 호출시 발생하는 에러에 대해 xlog 가 에러가 아니라 정상 상태로 보이게 하는 설정은 있습니다.
~~~
xlog_error_on_apicall_exception_enabled=false
~~~

**Comment by wasgosu** [comment]
아 그렇군요!! 많은 도움이 됐습니다
감사합니다~

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
