### ISSUE TITLE
.Lamda$ Xlog 관련 문의 드립니다. 

### ISSUE THREAD

**Issue by nightbobo** [scouter-project/scouter#498]
xLog 모니터링시 Lamda 표현식 작성된 코드 모니터링시 

>>> x.xx.xxx.xxx.Lamda$  내용이 반복적으로 표기 됩니다. 
혹시 Lamda 표현식으로 작성된 내용이 반적적으로 호출되지 않도록 설정할수 있는 방법이 있는지 문의 드립니다.

**Comment by gunlee01** [comment]
hook_method_lambda_enable=false
이렇게 적용해보세요.

**Comment by nightbobo** [comment]
고맙습니다. 덕분에 해결 되었습니다.

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
