### ISSUE TITLE
추출된 쿼리의 "/" (나누기 연산자 표현 누락현상)

### ISSUE THREAD

**Issue by playok** [scouter-project/scouter#499]
DB : Oracle 11
Scouter 버전 : 1.9.0
tomcat 8

증상
프로파일링된 내용중 쿼리에 "/" 연산자가 누락이 되어 화면에 표현됩니다.
예를들어 [ select 10/2 from dual ]쿼리를 수행할 경우  
"/"가 빠진 쿼리인 [ select 10 2 from dual ]만 UI에서 확인이 됩니다.

쿼리수행시
![image](https://user-images.githubusercontent.com/253674/45524040-5b3ff480-b807-11e8-8c96-aeb6e11578ac.png)

Scouter Xlog 데이터 확인한 내용
![image](https://user-images.githubusercontent.com/253674/45524109-b376f680-b807-11e8-88b1-3dfc19de69cb.png)

Scouter-Paper 에서 확인시
![image](https://user-images.githubusercontent.com/253674/45524408-42d0d980-b809-11e8-802c-2f25b49b874c.png)

**Comment by playok** [comment]
v2.0에 수정된 사항을 확인하는 도중에 아래와 같은 경우가 추가로 발생하는게 있어서 제보 드립니다.

#### 증상 (수행쿼리)
```sql
select 2/1 "case1", 2 / 1 "case2", 10/5/2 "case3" from dual
```
나누기 사이에 공백이 있을경우 정상처리되나 공백이 없을경우 이상동작합니다. 

#### 프로파일 결과
![image](https://user-images.githubusercontent.com/253674/46268924-8ef57b00-c578-11e8-8b72-52c5416f2332.png)

**Comment by gunlee01** [comment]
@playok fixed at v2.0.1
