### ISSUE TITLE
J 2068 C2 scouter.server.tagcnt.core.Top100FileCache$.add(Ljava/lang/String;Ljava/lang/String;)V (18 bytes)

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#505]
안녕하세요..  scouter 을 사용중인데, 주말에 scouter serve 프로세스가 java crash  발생 후 hs_err_pid 남 남기고 죽었더라구요..
일단 해당 파일을 좀 보니.. J 2068 C2 scouter.server.tagcnt.core.Top100FileCache$.add(Ljava/lang/String;Ljava/lang/String;)V (18 bytes)
이거때문에 죽었다고는 나오는데.. 원인이 명확하게 나오지 않네요.

저는 scouter server를 두개 두고 사용하는데, 이번에 이슈가 된 서버 java version은 (build 1.8.0_92-b14) 이고, 한번도 java crash가 발생한적이 없는 서버는 (build 1.8.0_112-b15) 라.. 버전 차이인가 의심은 있지만, 확신은 없는 상태입니다.

해서 java 버전 업그레이드는 나중에 좀 더 명확해지면 해볼건데.. core dump 가 생성되지 않아서 해당 서버에 core dump 생성하게 변경 후 한번 더 재현되기를 기다리고 있습니다.

J 2068 C2 scouter.server.tagcnt.core.Top100FileCache$.add(Ljava/lang/String;Ljava/lang/String;)V (18 bytes)
이 부분이 문제가 될 소지가 있을가요..?
core dump가 없어서 추가 분석은 어려운데, 어떤 행위로 인해 java crash가 발생한건지 알고싶어서 문의드립니다.
내용이 많이 없어서 제 실력으론 더이상 분석이 어렵네요 ㅎㅎ;;

1. hs_err_pid 파일 내용 (첨부파일로 올려드립니다)
[hs_err_pid13671.log](https://github.com/scouter-project/scouter/files/2463095/hs_err_pid13671.log)

JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
Problematic frame:
J 2068 C2 scouter.server.tagcnt.core.Top100FileCache$.add(Ljava/lang/String;Ljava/lang/String;)V (18 bytes) @ 0x00007fa4a55b5e72 [0x00007fa4a55b5860+0x612]

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

... (생략)

Stack: [0x00007fa491662000,0x00007fa491763000],  sp=0x00007fa491761600,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 2068 C2 scouter.server.tagcnt.core.Top100FileCache$.add(Ljava/lang/String;Ljava/lang/String;)V (18 bytes) @ 0x00007fa4a55b5e72 [0x00007fa4a55b5860+0x612]
J 4329% C2 scouter.server.tagcnt.first.FirstTagCountDB$$anonfun$1.apply$mcV$sp()V (181 bytes) @ 0x00007fa4a5b2d9ec [0x00007fa4a5b2d800+0x1ec]
j  scouter.server.util.ThreadScala$$anon$1.run()V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68e746]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x68ec51]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x68f0f7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x726060]  thread_entry(JavaThread*, Thread*)+0xa0
V  [libjvm.so+0xa6cc5f]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0xa6cd8c]  JavaThread::run()+0x11c
V  [libjvm.so+0x91fad8]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x7aa1]

분석시 참고 URL
https://www.oracle.com/technetwork/java/jdk50-ts-guide-149808.pdf

**Comment by gunlee01** [comment]
보내주신 로그로는 원인이나 jvm 버그가 검색되지는 않는 것 같습니다.
crash는 어플리케이션에서 조치하기 어려운 경우가 많으니, 일단 jvm을 업데이트 해보시기 바랍니다.

**Comment by wasgosu** [comment]
답글 달아주셔서 감사합니다~
해당 서버가 스펙도 낮고.. java 버전도 낮아서 업그레이드를 하는 방향으로 진행해봐야 겠네요.. 
저도 java version 이슈일 수도 있을 것 같은데.. 이정보로는 더이상 추가 분석이 어렵네요 
감사합니다^^
