### ISSUE TITLE
active object, inactive object 가 수초단위로 계속 발생하는데 원인이 뭘까요..??

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#506]
안녕하세요. 

scouter 잘 사용하고 있는데요, 트래픽이 좀 많은 서버들의 경우 수초단위로 running now, is not running 이 발생하고 있네요..
nginx 로 해당 서버에 부하를 좀 줄여주면 정상적입니다.
agent <===> server 연결 중 해당 증상처럼 증상이 발생할 경우 어떤식으로 조치하면 좋을가요?
agent, server 에 udp나 tcp 등 제한하는 영역이 있나요..??
수집은 잘 되는데 scouter client 화면에서 해당 서버가 꺼진것 처럼 보이고 또 정상으로 보이고..
계속 연결됐다 끊어졌다 하는것이 영.. 맘에 걸려서 원인을 찾고 싶어서요.

조언 구합니다~!!

/pNcmwas4 is running now. OBJECT  objType=linux objHash=x1rbprui objName=/xxxx addr=x.x.x.x 1.9.0 2018-07-21 08:02 GMT 2018-10-12 17:26:06.427 {counter=22.719906,detected=linux}

/pNcmwas4 is not running. OBJECT  objType=linux objHash=x1rbprui objName=/xxxx addr=x.x.x.x 1.9.0 2018-07-21 08:02 GMT 2018-10-12 17:26:17.577 {counter=20.241743,detected=linux}

![image](https://user-images.githubusercontent.com/41562733/46924649-c593c100-d061-11e8-8260-7608d875b595.png)

**Comment by gunlee01** [comment]
scouter collector로 agent의 heartbeat이 8초간 전송되지 않으면 inactive로 판단합니다.
scouter agent는 2초 간격으로 heartbeat을 전송하게 되어있는데요,
이런 현상이 벌어지는 경우는
n/w 대역폭이 모자라서 udp로 전송되는 heartbean이 8초 이상 전송되지 못한경우
agent의 부하가 너무 커서 2초 간격으로 전송하는 작업이 제대로 진행되지 않은 경우
collector의 부하가 너무 커서 받은 heartbeat을 제대로 처리하지 못한 경우 등입니다.
일단 옵션을 통해 8초 alive time을 좀 늘여놓은 후에 하나씩 점검해 보시기 바랍니다.
`object_deadtime_ms=20000`

**Comment by wasgosu** [comment]
object_deadtime_ms=20000
이런 옵션이 있었군요!!.........역시!!
현재 적용해보고 3분간 모니터링 해본 결과 동일 알람은 제거됐습니다..
감사합니다!..^^
![image](https://user-images.githubusercontent.com/41562733/46997967-30c1be00-d15c-11e8-999d-f863b87e862a.png)

**Comment by gunlee01** [comment]
일단 8초내에 health check가 제대로 안되는 것은 근본 원인이 해결되어야 하겠지만,
데이터 수집에 큰 문제가 없으시다면 사용이 가능할 듯 합니다.
데이터 수집에도 유실이 늘어난다면 capa 증설이나 데이터 수집을 최적하해야 합니다.
