### ISSUE TITLE
agent.host.conf와 agent.java.conf 설정 후에도 client에 서버가 나타나지 않는 경우

### ISSUE THREAD

**Issue by kunwp0723** [scouter-project/scouter#507]
안녕하세요

현재 A라는 서버를 host로 해서 A에서 A서버를 모니터링 하고 싶은데요
agent.host와 agent.java 디렉토리의 conf파일의 net_collector_ip를 모두 A로 하고
server 디렉토리의  startup.bat와 host 디렉토리의 host.bat를 모두 실행했는데도
client 프로그램에 A 서버가 나타나지 않습니다.
원인이 뭘까요...?
host 서버와 모니터링 대상 서버가 분리되어야 하나요?

**Comment by bill23-kim** [comment]
분리되야 하는건 아닌데 A 서버의 ip 로 스스로 접근이 안되는거 아닐까요? net_collector_ip 설정을 주지 않으면 디폴트로 127.0.0.1 로 접근합니다.

**Comment by kunwp0723** [comment]
net_collector_ip를 A로 설정을 하고 주석처리를 해제했는데도 접근이 안 되네요... 혹시 또 바꿔야할 설정값이 있을까요?

**Comment by bill23-kim** [comment]
같은 서버에서 서버랑 에이전트랑 다 띄울 경우 디폴트 설정값으로 인해 나타나야 하는데요.. 클라이언트 오브젝트뷰에 아무것도 안나오나요?

**Comment by kunwp0723** [comment]
네.. 기존에 사용하는 호스트만 나타나고
server address에 A서버의 IP 주소를 넣어서 A 서버로 새로 접속하려는 경우 (ID: admin, PW: admin) 
network connection failed라는 메세지만 뜹니다

**Comment by bill23-kim** [comment]
아.. 그건 에이전트가 안붙는다기보다 스카우터 서버가 제대로 안떴거나 클라이언트에서 접근을 못하는거 같은데요, 스카우터 서버 프로세스가 제대로 떠있는지.. 클라이언트 PC 에서 스카우터 서버 IP, 6100 으로 접근 가능한지 체크보셔야 될것 같습니다. 에이전트가 정상적으로 못붙더라도 스카우터 서버가 떠있으면 일단 클라이언트에서 로그인이 되야 합니다.

**Comment by kunwp0723** [comment]
다른 서버 IP는 클라이언트 PC에서 6100port로 붙는거 보면 해당 서버 IP로 접근이 안 되나보네요ㅜㅜ 한 번 알아봐야겠습니다. 답변 감사합니다!

**Comment by kunwp0723** [comment]
스카우터 서버가 뜨면

C:\scouter\server>java -Xmx512m -classpath .\scouter-server-boot.jar scouter.boot.Boot .\lib
스카우터 로고
Open Source S/W Performance Monitoring
Scouter version 1.9.0

System JRE version : 1.8.0_181

이렇게만 뜨는데 제대로 뜬 게 맞나요?

**Comment by gunlee01** [comment]
@kunwp0723 네 맞습니다.
일단 collector 에서 netstat 등으로 6100 포트가 열려있는지 확인해보시고,
열려 있다면 client PC에서 telent 등으로 6100 접근시 접속이 되는지를 확인해보시면 될 것 같습니다.
collector에서 telnet 6100으로 접근이 되는데 로컬 PC에서 접근이 되지 않는다면 n/w 구성을 살펴보셔야 할 것 같습니다.

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.

**Comment by kunwp0723** [comment]
안녕하세요... 문의가 또 생겼는데요.. 지금 collector 서버랑 모니터링할 서버가 연결은 돼서 client에 뜨기는 하는데요... OS만 연결이 된 거 같고 WAS (웹로직)는 연결이 안 된 것 같습니다. Client 상에서 xlog, active service 등의 이름도 unknown으로 뜹니다.. 
collector 서버에 db 파일에도 alert, counter, object, sum, tagcnt 폴더는 생성이됐는데 xlog 폴더는 없네요...
웹로직 실행 파일에 설정이 잘못된 것 같기도 한데...
웹로직 실행 파일에
set SCOUTER_HOME=C:\scouter\agent.java
set JAVA_OPTIONS=%JAVA_OPTIONS% -javaagent:%SCOUTER_HOME%\scouter.agent.jar
set JAVA_OPTIONS=%JAVA_OPTIONS% -Dscouter.config=:%SCOUTER_HOME%\conf\scouter.conf

이렇게 추가했는데 놓친 부분이 있을까요?

**Comment by pulmuone** [comment]
https://blog.naver.com/hanajava/221603332781
톰캣하고 jboss설정 방법이 조금 다른데 참고 해 보세요.
