### ISSUE TITLE
스카우터 콜렉터 서버도 이중화가 가능한가요?

### ISSUE THREAD

**Issue by jinsamkim** [scouter-project/scouter#508]
스카우터 콜렉터 서버에 플러그인 형태로 알람을 걸어 놓을 수가 있잖아요?

혹시 스카우터 콜렉터 서버가 깔린 물리 서버가 문제가 생긴다면 알람을 받을 수 없는 상황이 될 것 같은데, 콜렉터 서버도 이중화가 가능할까요?

**Comment by jinsamkim** [comment]
답변 감사합니다. 
HA는 정확하게 무엇을 의미하는 것 인가요?

**Comment by gunlee01** [comment]
@jinsamkim 
HA는 고가용성을 통칭하여 부르는 용어인데요,
원하시는 고가용성 수준에 따라 구성을 고민하여야 합니다.

예를 들어서 완전한 고가용성을 구축하시려면 
두대의 Collector를 인프라 기술을 활용하여 Active-Standby HA로 구성한 후에 
conf 와 data가 저장되는 저장소를 공용 스토리지로 바라보게 합니다.
이때 어디선가 특정 방법으로 한쪽의 Collector에 문제가 생기는지를 판단하여 Active 측을 차단하고
Standby를 구동시켜 작동하게 하는 방법을 말합니다.

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
