### ISSUE TITLE
server.conf Xlog configuration 및 Xlog filter 문의드립니다.

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#509]
server config 설정 문의드립니다.

Xlog 관련하여 설정해보려고 합니다.
1.   아래 설정을 실시간 Xlog 지정값 이하는 xlog 출력되지 않는 설정으로 이해 했습니다.
	@ConfigDesc("Ignored time(ms) in retrieving XLog in real time")
	public int xlog_realtime_lower_bound_ms = 0;

scouter.conf 에 **xlog_realtime_lower_bound_ms = 1000;** 설정하고 리스타트 했으나
설정하지 않았을때와 동일하게 Xlog 나옵니다.
혹시나 해서 띄워쓰기도 없애거나 설정했으나 동일합니다.
xlog_realtime_lower_bound_ms = 1000
xlog_realtime_lower_bound_ms=1000;

설정값 맞는지 확인 부탁드립니다.

agent에 설정하는 xlog_pasttime_lower_bound_ms=1000 는 적용확인했습니다.

2.  아래 설정을 실시간 Xlog는 나오고 5~10분 지난 과거 Xlog 데이터가 지정값 이하는 출력되지 않는 설정으로 이해 했습니다.
	@ConfigDesc("Ignored time(ms) in retrieving previous XLog")
	public int xlog_pasttime_lower_bound_ms = 0;

scouter.conf 에 **xlog_pasttime_lower_bound_ms = 1000;** 설정하고 리스타트 했으나
설정하지 않았을때와 동일하게 Xlog 나옵니다.
혹시나 해서 띄워쓰기도 없애거나 설정했으나 동일합니다.
xlog_pasttime_lower_bound_ms = 1000
xlog_pasttime_lower_bound_ms=1000;

설정값 맞는지, 다른 설정 방법이 있는지 문의드립니다.

3.  Xlog에 지정값이하는 프로파일 저장은 않하고 점은 출력되는 설정으로 보입니다. (제가 원하는 설정값)
//	@ConfigDesc("Ignored profile time(ms) without saving")
//	public int xlog_profile_save_lower_bound_ms = 0;

configure.java 보니 관련 내용 전부 주석 되어있던데, 혹시 어떤 사유가 있어서 빠졌는지 알수 있나요? history 보고 있는데 아직 github에 익숙치 않아서 찾지를 못하고 있습니다.

4. Xlog filter 항목에 응답시간 관련한 filter가 없어 보입니다. 혹시 있는지 추가 계획이 있는지 문의드립니다.
예) xlog 조회시 2초 미만은 제외하고 조회

5. xlog filter에 desc, TEST1~5는 어떤 항목을 넣고 조회하는건가요?

**Comment by gunlee01** [comment]
Scouter 설정은 프로퍼티파일을 사용하기 때문에 `some_config_key=VALUE` 처럼 띠워쓰지 않고 설정합니다. 세미콜론도 없습니다.
Collector에 적용하는 `xlog_realtime_lower_bound_ms`, `xlog_pasttime_lower_bound_ms`는 재시작 없이 바로 적용됩니다.

Collector에 설정하는 `xlog_realtime_lower_bound_ms` 설정은 해당 Collector의 모든 agent의 xlog를 화면에 보여줄때 적용되는 기능입니다. 

* 수집 시점에 응답시간에 따라서 sampling하는 옵션도 사용해보시기 바랍니다.
   * 이는 각 java agent 별 설정입니다. `xlog_sampling_enabled` 및 관련 설정.

* `xlog_sampling_only_profile=true` 와 같이 적용되면 모든 xlog는 수집되지만, 특정 응답시간 미만(및 특정비율)의 xlog의 profile은 수집되지 않습니다.
   * 아래 파일에서 자세한 내용은 확인해 보세요.
     * https://github.com/scouter-project/scouter/blob/master/scouter.agent.java/src/main/java/scouter/agent/Configure.java

* XLog filter의 최소응답시간 조건은 따로 issue로 올려주시면 검토가 가능합니다.

* TEXT1~5는 사용자 정의 스크립팅으로 사용자가 xlog에 추가한 어떤 값을 기준으로 Filter 하는 기능입니다.

**Comment by gogomasaru** [comment]
친절한 답변 감사합니다. 설정해보겠습니다.

**Comment by gogomasaru** [comment]
빠쁘신데 답변 감사합니다.

제가 원하는 설정은 xlog는 전부 나오고, 1초이하는 프로파일 저장이 안되게 하려고 합니다.
아래 처럼 설정해봤는데, 1초이하 xlog 점도 같이 안나오고 있습니다.

xlog_sampling_only_profile=true -> 이 설정이 있으면 프로파일만 안나오고 xlog는 나와야 되는거 아닌지 문의드립니다.

xlog_sampling_enabled=true
xlog_sampling_only_profile=true
xlog_sampling_step1_ms=1000
xlog_sampling_step1_rate_pct=0
xlog_sampling_step2_ms=5000
xlog_sampling_step2_rate_pct=100
xlog_sampling_step3_ms=10000
xlog_sampling_step3_rate_pct=100
xlog_sampling_over_rate_pct=100

**Comment by gunlee01** [comment]
네. 설정은 그런 의도가 맞습니다. 한번 확인해보겠습니다.

**Comment by gunlee01** [comment]
처리에 문제가 있었습니다. 다음 버전에 fix 예정입니다.
fixed @ 23f57dafce2f1271b529e06c90727630981442d2
 - candidate to next version.
