### ISSUE TITLE
scouter 은 OutOfMemory 발생 감지 알람은 없을까요..?

### ISSUE THREAD

**Issue by wasgosu** [scouter-project/scouter#510]
현재 scouter 알람을 slack 연동해서 수신받고 있는데요..
기본으로 제공되는 알람컨트롤에는 OOM발생시 알람을 받아 볼 수 있는게 없는것 같아서 문의 드립니다.
한 인스턴스 jvm에 scouter agent 를 호출하는 방식이라서 감지가 안되는 거겠조..?

![image](https://user-images.githubusercontent.com/41562733/47137394-65b34980-d2f1-11e8-8545-7aff7395eb12.png)

**Comment by gunlee01** [comment]
OOM 발생은 감지하기가 애매합니다. 
OOM 상황에서는 탑재된 javaagent도 제 기능을 할수 가 없게됩니다.
그러한 상황인 경우에는 alive 체크도 실패하므로 inactive object로 빠지게 되는데,
active, inactive object인 경우 알림이 오게 되어있습니다.
기본 수준이 INFO로 되어 있어서 메시지로 받지는 못할텐데요 이 레벨을 collector 설정에서 올려줄 수 있습니다.
`object_inactive_alert_level`

**Comment by wasgosu** [comment]
아무래도 감지하기 애매하긴 하겠네요..
현재 collect server 부하가 좀 높아서 기본 8초를 60초로 변경해두고 사용중이라 해당 옵션은 저에겐 의미가 없겠네요.
Waiting time(ms) until stopped heartbeat of object is determined to be inactive
object_deadtime_ms=60000

흠.. 우선 OOM감지를 자동으로 할만한게 모가 있을까 하다 기동 스크립트에 OOM 발생하면 wsrestart.sh 실행하게 해서 
slack에 알람 뿌리고 자동 restart 하게 해뒀습니다.
이글 보시는 다른분 중 저와같은 고민하고 계시는 분이 있을것 같아 정보 공유차원에서 남겨둘께요.
댓글 감사합니다~!

export JAVA_OPTS=" $JAVA_OPTS -XX:+HeapDumpOnOutOfMemoryError "
export JAVA_OPTS=" $JAVA_OPTS -XX:HeapDumpPath=/app/WAS/wildfly-14.0.1.Final/standalone/log/heapDump_$DATE.hprof "
export JAVA_OPTS=" $JAVA_OPTS -XX:OnOutOfMemoryError=/app/WAS/wildfly-14.0.1.Final/bin/slack.sh "
..# slack.sh
[ -z $SCRIPTS_HOME ] && SCRIPTS_HOME=/app/scripts
. $SCRIPTS_HOME/common/slack_utils.sh
send_slack_oom_message --channel="#3_scouter"

..# /app/WAS/wildfly-14.0.1.Final/bin/wsdown.sh
echo "======================================================"
echo "sleep time.. 10 second After wildfly restart....!!!!!"
echo "======================================================"
sleep 10

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
