### ISSUE TITLE
xlog_fully_discard_service_patterns 설정 시 waiting 상태로 됩니다.

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#511]
안녕하세요.
xlog_fully_discard_service_patterns 설정 사용 시 상태가 waiting으로 되어 문의 드립니다.

xlog_discard_service_patterns 설정은 동일한 현상이 없습니다.

agent 설정 : xlog_fully_discard_service_patterns=*/InstanceTest.jsp

아래 Active servrice list 보면 전부 지정응답 시간 초과로 빨간색 표시가 됩니다.
![s-01](https://user-images.githubusercontent.com/26616377/47280456-77f2f780-d611-11e8-873b-97b1a4c4e770.JPG)

아래 thread detail은 아래와 같습니다.
![s-02](https://user-images.githubusercontent.com/26616377/47280547-e1730600-d611-11e8-81b7-c81b12a4f109.JPG)

**Comment by gunlee01** [comment]
duplicated

**Comment by gunlee01** [comment]
최신 버전인가요? 실제로 종료되었으나 종료 flag 처리가 누락되었을때 나오는 현상일 듯 한데,
버그인지 확인해 보겠습니다.

**Comment by gogomasaru** [comment]
빠른 확인 감사드립니다 ^^

**Comment by gunlee01** [comment]
fixed @ fffd00052acf935fbb5c25ac135e81045aa5f895
 - candidate to next version.
