### ISSUE TITLE
xlog_fully_discard_service_patterns 설정 시 waiting 상태로 됩니다. 

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#512]
안녕하세요.
xlog_fully_discard_service_patterns 설정 사용 시 상태가 waiting으로 되어 문의 드립니다.

xlog_discard_service_patterns 설정은 동일한 현상이 없습니다.

agent 설정 : xlog_fully_discard_service_patterns=*/InstanceTest.jsp

아래 Active servrice list 보면 전부 지정응답 시간 초과로 빨간색 표시가 됩니다.
![s-01](https://user-images.githubusercontent.com/26616377/47280793-07e57100-d613-11e8-9404-763858552c37.JPG)

아래 thread detail은 아래와 같습니다.
![s-02](https://user-images.githubusercontent.com/26616377/47280797-0fa51580-d613-11e8-9697-be86426a6605.JPG)

**Comment by gunlee01** [comment]
duplicated
