### ISSUE TITLE
Xlog 필터 항목 추가 요청

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#513]
안녕하세요.
Xlog 조회 필터 항목에 "응답시간" 이 추가 되었으면 좋을 것 같습니다.

1.  최소응답시간을 지정 (예. 3초 미만은 제외하고 조회 3초이상 Xlog만 나옴)
또는
2. 응답시간 구간을 지정 (예. 3~5초만 조회)

원하는 응답시간만 조회해서 본다면 더 사용하기 편해질 것 같습니다.

감사합니다.

**Comment by gunlee01** [comment]
일단 대안으로
원하는 응답시간 구간을 포함하는 영역을 shift 키를 누른 상태로 마우스를 드래그 하면
해당 구간에 대한 xlog 창이 새로 열립니다.
한번 사용해보세요.

**Comment by gogomasaru** [comment]
좋은기능 설명 감사합니다.
해당 기능은 실시간에서 유용해보이는데요.
혹시 load history 과거 Xlog 데이터에서 특정 응답 시간 이상만 보거나 특정 응답시간 사이를 보기위한 방법은 없을까요?

**Comment by gunlee01** [comment]
현재 응답시간을 조회 조건으로 주거나 이를 기준으로 필터링하는 기능은 없습니다.
제안해주신 기능은 ToBe Feature로 관리할 예정입니다.

**Comment by gunlee01** [comment]
done
