### ISSUE TITLE
Netflix feign 지원 여부 문의

### ISSUE THREAD

**Issue by redutan** [scouter-project/scouter#515]
최근 프로젝트를 진행면서 spring-cloud 관련한 라이브러리를 많이 사용 중인데, 혹시 
Netflix Feign 지원 계획은 없는지 문의 드립니다. #

**Comment by gunlee01** [comment]
계획은 누군가 기능 제안을 해주시면 수립됩니다. ^^
Feign은 당연히 지원할 예정입니다. 
진행 중인 다른 feature 가 있어서 일정이 계획되지는 않았는데요 올해 안에는 들어갈 듯 합니다.

boot로 구동되는 샘플 프로젝트를 github 같은데 올려주시면 좀더 원활히 진행가능합니다. ^^

**Comment by redutan** [comment]
@gunlee01 
https://github.com/redutan/feign-reactor
샘플 프로젝트 제공 드립니다.

**Comment by gunlee01** [comment]
@redutan 감사합니다.
기능 추가시에 테스트 환경 만드는게 큰 일 중 하나인데 (특히 평소 사용하던 구성이 아닌 경우는 더욱)
많은 도움이 될 듯 합니다.

다음 버전에 지원하는 방향으로 진행해 보도록 하겠습니다.

**Comment by gunlee01** [comment]
done
https://github.com/scouter-project/scouter/releases/tag/v2.5.0
