### ISSUE TITLE
업데이트는 어떻게해야하나요?

### ISSUE THREAD

**Issue by ganada2** [scouter-project/scouter#517]
Server  - Agent - Client 버전이 모두 다르게 관리되어도 상관이 없는건지.

모두 동일 배포 버전을 사용해야하는건지 궁금하네요~~

**Comment by gunlee01** [comment]
동일 버전을 권장합니다.
다만 Server 버전을 agent 및 client가 따라가지 못해도 하위 버전을 지원하도록 고려하여 개발하므로 사용에 별 문제가 없습니다. 
agent의 버전이 낮은 것은 전혀 문제되지 않습니다.
일반적으로 Server가 agent 및 client 보다 버전이 높다면 별 문제가 없다고 생각하시면 됩니다.
단 상위 버전에 추가된 정보는 수집되지 않거나 추가된 기능은 사용할 수 없습니다.
(간혹 문제가 되는 버전의 client가 있을수는 있습니다. 이 경우에 client를 업데이트 하여야 합니다.)

**Comment by gunlee01** [comment]
Pending answer closed.
Reopen it if needed.
