### ISSUE TITLE
Java 9+ 지원하나요?

### ISSUE THREAD

**Issue by zepinos** [scouter-project/scouter#518]
안녕하십니까, scouter 을 이용하려고 하는데 startup  시 문제가 발생하여 문의 드립니다.

Scouter webapp 의 startup.sh 을 이용해 시작을 하려고 하는데 아래와 같은 오류가 발생합니다.

```
1. java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
2. java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$DefaultValidatorFactoryProvider errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$DefaultValidatorFactoryProvider
5. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider errors were found
6. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider
```

경험 상 위 오류는 Java 9+ 에서 Jigsaw 때문에 발생하는 경우인데, Server(Collector) 실행 시에는 발생하지 않고 webapp 실행시에만 발생하고 있습니다.

혹시 다른 문제로 시동이 안되는 것일까요?

조언 부탁드립니다.

**Comment by gunlee01** [comment]
* java 9+를 대상으로 scouter.server 와 scouter.webapp 은 테스트되지 않았습니다.
 문제가 있으시다면 일단 java 8로 구동해서 사용 부탁드립니다.

* java agent는 java 9, java 10을 지원합니다.

**Comment by gunlee01** [comment]
* collector, webapp 에 대한 java 9 호환성은 다음 버전 이후 12월 경에 진행 될 듯합니다.

**Comment by zepinos** [comment]
> 
> 
>     * collector, webapp 에 대한 java 9 호환성은 다음 버전 이후 12월 경에 진행 될 듯합니다.

OpenJDK 이슈 때문에 기존 JDK 들을 모두 11 로 올린 상태인데, 차차기 버전이 나올 때까진 Java 8 으로 버텨야겠네요. 고맙습니다.
