### ISSUE TITLE
Client can't launch in macos majave

### ISSUE THREAD

**Issue by ixpress** [scouter-project/scouter#519]
I have used the v2.0.1 release, `scouter.client.product-macosx.cocoa.x86_64.tar.gz`, it just don't launch, and don't work

**Comment by gunlee01** [comment]
I don't have any problems to launch scouter client(v2.0.1) on my Mac OSX mojave.
Do you have more details? any stack trace or error messages?

**Comment by gunlee01** [comment]
It's possible there are JVMs incompletable status in your machine, then try to edit scouter.ini like below.
* add your java executable path to your PATH env variable preceding anothers.
```bash
## example
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
```
* Or explicitly enter your java executable in scouter.ini file like below
```properties
# file : ~/somewhere/scouter.client.app/Contents/Eclipse/scouter.ini
# add vm option in this file
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
```

**Comment by ixpress** [comment]
> It's possible there are JVMs incompletable status in your machine, then try to edit scouter.ini like below.
> 
> * add your java executable path to your PATH env variable preceding anothers.
> 
> ```shell
> ## example
> export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
> export PATH=$JAVA_HOME/bin:$PATH
> ```
> 
> * Or explicitly enter your java executable in scouter.ini file like below
> 
> ```ini
> # file : ~/somewhere/scouter.client.app/Contents/Eclipse/scouter.ini
> # add vm option in this file
> -vm
> /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
> ```

Thank you for your help.

PATH env on my machine is fine, this is the result of `echo $JAVA_HOME`: `/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home`

I have tried to add `-vm` in scouter.ini, it still can't work.

Is there any trace log for scouter, so I can submit it in the attachment.

**Comment by gunlee01** [comment]
Scouter client doesn't support Java 11 yet. 
If you'd install java 11 your self or on accident, Mac OSX may use 11 if your Java Home indicates Java 8.
So try to run a scouter client in a command line or explicitly add a VM option in the scouter.ini or uninstall Java 11.

**Comment by ixpress** [comment]
> Did you try it on a command line?
> Or try it.
> `open ./scouter.client.app`

Thx, it works when I open on command line,  while not  work when I click the app.
Thanks.
