### ISSUE TITLE
xlogs description

### ISSUE THREAD

**Issue by danielelic** [scouter-project/scouter#525]
Where do I find a detailed description for each xlog field?
* endTime
* objHash
* service
* txid
* threadName
* caller
* gxid
* elapsed
* error
* cpu
* sqlCount
* sqlTime
* ipAddr
* allocatedMemory
* internalId
* userAgent
* referrer
* group
* apicallCount
* apicallTime
* countryCode
* city
* login
* desc
* hasDump
* text1
* text2
* text3
* text4
* text5
* queuingHost
* queuingTime
* queuing2ndHost
* queuing2ndTime
* xlogType

**Comment by gunlee01** [comment]
Some descriptions are in the source comment. Need you more details?

https://github.com/scouter-project/scouter/blob/master/scouter.common/src/main/java/scouter/lang/pack/XLogPack.java

**Comment by danielelic** [comment]
Thanks, that's fine.
