### ISSUE TITLE
java.lang.ClassCastException 에러 문의

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#529]
scouter 에이전트 2.0.1 -> 2.5.0로 버전 업그레이드 후 아래와 같은 에러 및 Out of Memory가 발생하여 문의 드립니다.

에이전트 jboss 7.1 (jdk1.8)인 WAS에서는 발생하지 않으나, websphere 8.5.5 (jdk1.7)에서 에러 로그가 발생합니다.
scouter 수집서버도 2.5로 업그레이드 되어있고, 위 jboss와 websphere 같이 수집하고 있습니다.

현재 websphere 에이전트를 2.5에서 2.0.1로 원복하니 에러 발생하지 않고 있습니다.

에러 로그 : 20181126 03:51:08 [A905] java.lang.ClassCastException: java.net.URLClassLoader incompatible with scouter.javassist.util.proxy.SecurityActions$3

**Comment by gunlee01** [comment]
Java 11 지원을 위해 Scouter에 repackaging된 javassist가 3.21.0 에서 3.23.1로 변경되었습니다. 
아마 이 영향일 듯 한데 좀 더 알아봐야 겠지만, 당장 해결은 어려울 것 같습니다.
Websphere 또는 Java 7 둘 중 하나의 영향일 듯 한데요,
javassist 3.23.1이 Java 7에서 문제가 있다면 scouter의 java agent를 구 javassist를 탑재한 버전과 Java 11지원을 위한 javassist 를 탑재한 두가지 빌드로 가져가야 할 수도 있윽 것 같습니다.
일단 좀 더 확인이 필요합니다.

**Comment by gogomasaru** [comment]
감사합니다. 위에 임시파일로 적용하니 현상 발생하지 않습니다.

수집서버로그에도 2.5.0.BACKPORT.JAVASSIST 버전 출력 확인했습니다.

server.log
20181127 02:25:15 [S105] Update OBJECT  objType=websphere objHash=xd70vh6 objName=hostname addr=IP **2.5.0.BACKPORT.JAVASSIST** 2018-11-26 15:20 GMT alive 2018-11-27 02:25:15.111 {detected=websphere,ADC=false}

**Comment by gunlee01** [comment]
v2.5.1에 포함된 agent.java_6_7 디렉토리에 있는 agent를 사용해보시기 바랍니다.
이후 버전부터는 계속 java 6/7용과 java8+용 두가지 릴리즈가 같이 포함됩니다.
