### ISSUE TITLE
pid 는 int 보다 큰 값일 수 있습니다.

### ISSUE THREAD

**Issue by kukgini** [scouter-project/scouter#53]
SysJMX.getProcessPID() 는  int 를 반환하게 되어 있습니다. int 의 최대값은 65535 더군요.

38bit 혹은 64bit 머신에서 pid 의 최대값은 2147483647 까지 올라갈 수 있습니다. c 언어에서는 pid_t 라는 자료형을 제공함으로써 os 에 따른 pid 문제에 대한 효율적인 해결안을 제공하고 있지만 java 에서는 아직 마땅한 방법을 제공하지 않습니다. 손쉽게 long 정도로 올려버리면 향후 몇년간 고민할 필요는 없겠습니다만... ^^

현재의 코드는 잠재적인 문제를 안고 있어 이슈로 등록합니다.

**Comment by bill23-kim** [comment]
int 의 최대값이 2147483647 이지 않나요?

**Comment by gunlee01** [comment]
int=4byte
short=2byte

**Comment by kukgini** [comment]
정정합니다.

64bit 머신에서 가능한 pid 최대값은 2^62 입니다. 하지만~ 
다음 글타래를 참고해 보면... 
http://unix.stackexchange.com/questions/231719/why-is-the-maximum-pid-in-a-64-bit-linux-system-222

비록 Linux 에 한정된 이야기이긴 하지만 32bit 이상의 머신에서 pid 최대값은 
아직까지 2^29 = 536870912 에 머물러 있네요.
java int 의 최대값(2147483647)으로 충분히 허용이 되므로 이 이슈는 닫겠습니다.
