### ISSUE TITLE
mgr_purge_profile_keep_days 옵션 문의

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#530]
mgr_purge_profile_keep_days=30 와 같이 설정하여 사용중인데 서버로그를 확인하니
10일만 보관되고 있습니다. (디폴트값 10)

mgr_purge_profile_keep_days=9로 해도 10일치 보관 되는데 
제 설정 중 특이사항 있는지 문의드립니다. (다른 purge 옵션은 잘 동작했습니다.)

수집서버 scouter.conf
mgr_purge_enabled=true
mgr_purge_disk_usage_pct=90
**mgr_purge_profile_keep_days=30**
mgr_purge_xlog_keep_days=30
mgr_purge_counter_keep_days=30

서버 로그
20181126 00:00:43 [S206] * Auto deletion... 20181116 mode : PROFILE
20181126 00:00:43 [S206-4] [purge profile by][day limit]20181116
**20181126 00:00:43 [S206-4] * option : conf.mgr_purge_profile_keep_days : 10**
20181126 00:00:43 [S206] * Auto deletion... 20181027 mode : XLOG
20181126 00:00:43 [S206-5] [purge xlog by][day limit]20181027
20181126 00:00:43 [S206-5] * option : conf.mgr_purge_xlog_keep_days : 30
20181126 00:00:43 [S206] * Auto deletion... 20181027 mode : ALL
20181126 00:00:43 [S206-6] [purge counters by][day limit]20181027
20181126 00:00:43 [S206-6] * option : conf.mgr_purge_counter_keep_days : 30

**Comment by gunlee01** [comment]
로그로 볼때 버그가 있어보이는데요.
일단 `mgr_purge_keep_days` 옵션을 대신 사용할 수 있습니다.
mgr_purge_keep_days=30으로 한번 적용해 보시기 바랍니다.

**Comment by gunlee01** [comment]
확인해보니 이 기능이 처음 들어간 시점(2017년)부터 버그가 있었네요.
버그 제보 감사합니다.
위에서 말씀드린 옵션으로 일단 사용해 주시고 
다음 버전에 Fix 추가하겠습니다.

**Comment by gunlee01** [comment]
v2.5.1 에서 버그 Fix 되었습니다.
