### ISSUE TITLE
Profile View 에서 쿼리에 바인딩된 파라미터의 길이제한을 설정으로 조정할 수 있나요?

### ISSUE THREAD

**Issue by themuser** [scouter-project/scouter#532]
Profile View를 보면 트레이스되는 메소드들과 SQL Prepared Statement, 쿼리에 바인딩 된 파라미터 등의 정보가 나오는데요,
쿼리 파라미터의 경우 기본적으로 20글자 기준으로 substring 해서 보여주는 것 같습니다.   

혹시 쿼리 파라미터 부분을 substring 없이 전체가 나오도록 조정할 수 있는 설정이 있는지 궁금합니다.

**Comment by gunlee01** [comment]
바인드변수 20자는 상수로 고정되어 있습니다.

**Comment by themuser** [comment]
확인 감사드립니다! 
한 가지 더 질문드리고 싶은데요, 혹시 20으로 고정되어있는 설계/성능상의 이유가 있을까요?

소스코드 상에서 20으로 설정된 부분 확인은 했는데 Conf 통해서 조절 가능하게 하는 방식으로 수정해서 PR 하면 Merge 가능할까요?

**Comment by gunlee01** [comment]
@themuser 
20자로 제한한 것은 성능 영향때문이 맞습니다.
기본 사상이 로그 시스템이 아닌 성능 모니터링 시스템이라, 파라미터 전체를 남기는 것은 과도한 기능이고 이로 인해 발생할 수 있는 성능적인 영향이 크기 때문에 20자로 제한되었습니다. 
또한 APM agent의 문제로 실 운영 시스템의 자원을 과도하게 사용하거나 문제를 발생시키지 않도록 보수적으로 접근하는 부분도 있습니다. 예를 들어 LOB 컬럼을 사용하거나 혹은 LOB 컬럼이 아닐지라도 사용자 실수 혹은 버그등으로 아주 큰 길이의 문자열이 전송될때 비록 DB에서는 에러를 뱉을수 있지만, 이미 Scouter는 파라미터를 수집하기 위해 메모리를 할당하게 됩니다.

하지만 20자 제한에 대해서 늘여달라는 요청이 몇번 있었고, 옵션으로 잘 사용한다면 발생하는 문제보다 오히려 모니터링에 도움을 줄 요소가 많을 듯 합니다.
아래 기본적인 요건을 맞추어 PR 주시면 검토하여 머지하도록 하겠습니다.
 - 기본값 : 20byte
 - 최대 : 500byte, 500byte 이상으로 설정시는 500byte로 고정. 
    - 이 부분은 더 큰 값이 필요하다면 의견 주세요.
    - 매 쿼리의 파라미터가 scouter db에 저장되므로 디스크 사용량이 상당히 올라갈 수 있습니다.
    - 보통 10개의 step에 두개의 쿼리 정도가 있는 프로파일 당 400~500 byte 정도 사용됩니다. 파라미터 하나가 500byte를 사용하는 위와 같은 쿼리가 하나만 추가되어도 디스크 사용량이 2배 가량 될 수 있습니다.

**Comment by themuser** [comment]
develop 브랜치쪽으로 Pull Request 올렸습니다. 리뷰 부탁드릴게요 :-)

agent.java 쪽에 설정이 하나 추가되었고, 별도로 유효성 체크를 위한 검증로직은 넣지 않았습니다. 대신 500글자 이상의 값이 입력 되어도 자동으로 500글자 까지만 출력되도록 하였으며, 상세한 설명은 속성값에 대한 description 영역에 기술하였습니다.
