### ISSUE TITLE
how to see the parameter/header of a request in xLog?

### ISSUE THREAD

**Issue by aswzen** [scouter-project/scouter#534]
Hello,

I just installed everything and success without any problem, but i wonder how to get parameter/header of each request in Tomvat > xLog 

for example:
![image](https://user-images.githubusercontent.com/1474916/49777408-f24b1880-fd32-11e8-8f8c-1e9169437b82.png)
![image](https://user-images.githubusercontent.com/1474916/49777550-8c12c580-fd33-11e8-88fd-d6a37ecd19ee.png)

The request is going to /api/v1/profile/profile
but i am unable to see the header or the request parameter, actually there are some parameter that has been sent like this one

Header		:	{Accept=application/json, Cache-Control=no-store, must-revalidate, no-cache, User-Agent=Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J105F Build/LMY47V), Connection=Keep-Alive, X-Forwarded-For=xx, Host=xx, Accept-Encoding=identity, Pragma=no-cache, Content-Length=159, Content-Type=application/json}
Accessing	:	http://xxxx/api/v1/current-version
Param		:	-
Request		:	{"imei":"XXX","deviceModel":"SM-J105F","deviceManufactur":"samsung","deviceOs":"5.1.1","os":"android","language":0,"msisdn":null,"version":"3.2.8"}

Need help,

Thanks

**Comment by gaiajeon** [comment]
I recommend you use "plug-in"  function. Scouter agent-java has "plug-in" directory.
There are some plugin files. 
I have used  capture.plug file to collect Java Class Method Argument's value

Maybe, you should use  "httpservice.plug" to collect Http Request Parameter.

For reference, I wrote my captue.plug file to Java Class Method's Argument  

[args]
        Object[] args = $hook.getArgs();
        String className = $hook.getClassName();
        if (className != null && className.length() > 0 ){
            className =  className.replace("/",".");
        }        
        String methodName = $hook.getMethodName();
        String argStr = "";
        for(int i=0;i<args.length;i++){
           if (i == args.length - 1)
               argStr += args[i].toString();
           else 
               argStr += args[i].toString()+"/";
        }
        String sName = className + "." + methodName + argStr;
        $ctx.service(sName);

[return]

[this]
