### ISSUE TITLE
jeus6, ibm jdk 1.6 기동시 에러

### ISSUE THREAD

**Issue by jinseo-jang** [scouter-project/scouter#536]
안녕하세요.
jeus는 공식 테스트 되지 않은 was라는 점 알지만..tomcat으로 속여 설정하고 기동시도했는데
로그상에

 / ___|  ___ ___  _   _| |_ ___ _ __
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |
 |____/ \___\___/ \__,_|\__\___|_|
 Open Source S/W Performance Monitoring
 Scouter version 2.5.0

20181214 10:48:06 [SCOUTER] Version 2.5.0 2018-11-18 02:34 GMT
20181214 10:48:06 [SCOUTER] loaded by system classloader
20181214 10:48:06 [SCOUTER] jar:file:[비밀처리]/agent.java/scouter.agent.jar
20181214 10:48:07 [SCOUTER] objType:tomcat
20181214 10:48:07 [SCOUTER] objName:[비밀처리]
20181214 10:48:07 [A113] Counter Collector Started (#19)
20181214 10:48:07 [A113] InteractionCounter Collector Started (#19)
20181214 10:48:07 [SCOUTER] Configure -Dscouter.config=/gscmdev/util/APM-Scouter/agent.java/conf/scouter.engine1.conf
20181214 10:48:07 [A100] agent boot seed=x5o02ml6cg74
20181214 10:48:07 [A160] java.lang.ExceptionInInitializerError

마지막줄에 exception 이 발생합니다.
정상 로그와 비교해면 plugin 기동 과정에서 나는것 같은데.
이유를 알 수 있을까요??

**Comment by gaiajeon** [comment]
혹시 plug-in 디렉토리 내의 plugin 파일을 편집하여 사용하신게 있는지요.?

**Comment by jinseo-jang** [comment]
@gaiajeon 관심갖어주셔서 감사합니다. 특별히 plug-in 디렉토리 내 plugin 파일을 편집하지 않았습니다.
linux+openjdk1.8 환경에서는 잘 구동되는걸로 보아
aix+ibmjdk1.6 환경문제인지 추측만 하고 있네요.

**Comment by gaiajeon** [comment]
scouter로  jeus + ibm jdk1.6으로 운영하는 고객이 있습니다.
IBM jdk가 조금 특이하긴 합니다만 해당 문제는 발생된적이 없어서 혹시나 해서 질문드렸습니다.

**Comment by jinseo-jang** [comment]
로그를 좀더 보니 다음과 같은 로그가 확인되었어요.

```
20181214 10:26:24 [A161] java.lang.NoClassDefFoundError: scouter.javassist.util.proxy.DefineClassHelper (initialization failure)
20181214 10:26:24 [A160] java.lang.NoClassDefFoundError: scouter.javassist.util.proxy.DefineClassHelper (initialization failure)
```

**Comment by gunlee01** [comment]
근래 리포팅된 현상을 종합해보면
scouter 2.5.0에 탑재된 버전의 javassist가 java 8 미만에서 문제가 있는 것으로 추정됩니다.
javassist에서 지원하는 java version에 대해서 아직 공식 document를 찾지는 못했는데 관련이 있을 듯 합니다.
정확한 해결책이 나올때까지 java agent를 java 8 미만 버전과 java 8 이상 버전 두가지로 릴리즈 할 계획입니다.
일단 2.1로 사용해 주시고 다음 릴리즈에 java 8 미만을 지원하는 2.5+ 버전으로 사용하시는게 좋을 것 같습니다.

**Comment by jinseo-jang** [comment]
감사합니다!
그럼 agent만 2.1로 교체체 설치하면 될까요요!?

**Comment by gunlee01** [comment]
v2.5.1에 포함된 agent.java_6_7 에 있는 agent.jar로 사용해보시기 바랍니다.

**Comment by jinseo-jang** [comment]
@gunlee01 감사합니다! 교체했더니 해당 에러 나타나지 않습니다 :)
