### ISSUE TITLE
Request Header에 추가되는 내용을 컨트롤 할 수 있나요?

### ISSUE THREAD

**Issue by kapentaz** [scouter-project/scouter#558]
안녕하세요!

서버에서 다른 서버로 요청을 보낼 때 설정하지 않은 request header 정보가 전달이 되어서 확인을 해보니
소스코드 상에서는 Cache-Control, Pragma 값을 설정하지 않았는데 대상 서버로 전달이 되고 있습니다.

tcpdump로 확인해 보면 아래와 같은 형태로 나오는데 X-Scouter로 시작하는 헤더들이 있는 것으로 보아 scouter에서 헤더에 내용을 추가 하면서 Cache-Control, Pragma 값을 설정하는 것으로 추정됩니다. 혹시 관련된 내용이나 전달하지 않도록 설정할 수 있는 방법이 있을까요?

감사합니다.

```
..).*.P3.O....%P.9..g..GET /..... HTTP/1.1
X-Scouter-Gxid: ....
X-Scouter-Caller: ....
X-Scouter-Callee: ....
X-Scouter-Caller-Obj: ....
Accept: text/plain, text/plain, application/json, application/json, application/json, application/*+json, application/*+json, text/plain, application/*+json, */*, */*, */*
Cache-Control: no-cache
Pragma: no-cache
User-Agent: Java/1.8.0_192
Host: ....
Connection: keep-alive
```

**Comment by gaiajeon** [comment]
WAS간 서비스콜을 추적하기 위해 설정된 헤더 값입니다

conf 파일에 
trace_interservice_enabled=false
를 추가하시면 됩니다.
당연히 false로 설정하시면 was 간 서비스콜 추적은 불가능하겠죠?

**Comment by kapentaz** [comment]
@gaiajeon 
캐시된 값은 추적할 필요가 없기 때문에 해당 header를 추가 하는거군요
스카우터를 사용하기위해서는 필수라고 이해하면 될까요?

**Comment by gaiajeon** [comment]
코드를 보니요. 따로 Cache-Control,Pragma 값을 코드 상에서는 설정하지 않네요.
아마도 키 값이 새롭게 할당되니 캐시된 값이 아닌 새로운 값을 보내기 설정이 되는 것도 같네요.

그리고 trace_interservice_enabled 옵션을 false로 설정하면 was간 서비스 콜만 수집이 되지 않으니
여러 서비스 간 추적이 주 목적이 아니라면 사용하시는 데 큰 문제는 없을 거라고 생각됩니다.

**Comment by gunlee01** [comment]
@kapentaz 
java application에서 http를 통하여 api를 호출하는 경우 scouter에서 http 요청 헤더를 추가합니다.
이는 application간 cross tracing을 위한 헤더들로 헤더는 X-SCOUTER로 시작합니다.
Pragma 혹은 Cache-Control과 같은 헤더는 scouter에서 추가하는 헤더는 아닙니다.
