### ISSUE TITLE
request.getInputStream() 사용시 이슈

### ISSUE THREAD

**Issue by dukeredfox** [scouter-project/scouter#564]
아래와 같이 구성된 소스에서 request에 빼올 data가 사라지는 이슈가 있네요.

 public Document getRequest(HttpServletRequest request) throws SAXException, BizException {
String xmlContents = null;
            StringBuffer bufResponseXml = new StringBuffer();
            requestInputStream = request.getInputStream();
            BufferedReader dataIn = new BufferedReader(new InputStreamReader(requestInputStream, "UTF-8"));
           
/**********************************************************
strTempXml  null값이 되어 버립니다. 
**********************************************************/
            while ((strTempXml = dataIn.readLine()) != null) {
               bufResponseXml.append(strTempXml).append("\n\r"); 
            
            }

상기와 같은 경우 소스 수정 없이 어떤 해결책이 있을까요?

**Comment by gunlee01** [comment]
java agent는 어떤 버전을 사용하시나요?

**Comment by dukeredfox** [comment]
0.4.22 버전 사용 중입니다.
최근 버전을 사용한다면 해당 이슈가 해결될까요?

**Comment by gunlee01** [comment]
@dukeredfox 
최신 버전 코드로 볼때 위 코드의 strTempXml 값이 null이 될만한 요인을 찾지 못해서 버전을 여쭤본거에요.
일단 해당 버전을 확인해 봐야 알겠지만 너무 예전 버전이라 다른 기능 추가나 버그 패치도 많이 되었으니
다른 이유에서라도 업그레이드 하시면 좋을 듯 합니다.

일단 0.4.22 에서 코드를 작성해 테스트를 해볼텐데요.
소스에서 getRequest() 메소드는 어느 시점에 호출되는 건가요?
당연히 servlet의 doGet, doPost 이후일 듯 한데
특별한 Framework을 사용하는 것인지요? 
동작하는 샘플 코드 제공이 가능하시다면 제공해 주시면 좋을 듯 합니다.

**Comment by dukeredfox** [comment]
아래와 같이 처리흐름을 가진 소스입니다.

	/***************************************************
	 * Spring Controller Method
	 * 외부에서 XML contents를 POST방식으로 호출
	 ***************************************************/
	public void receiveResponseXYZ(HttpServletRequest request, HttpServletResponse response) throws Exception {
        ParameterMap param = new ParameterMap();

        request.setCharacterEncoding("UTF-8");
        // XML 생성
        StringBuffer rsltXml = new StringBuffer();      // 전송 xml

        Document document = null;
        try{
            //1. 전송XML 수신
            try{
                document = getRequest(request);
            }catch (SAXException se){
                log.error(getClass(), se);
            }
	}

	/**
     * XML 데이터 수신
     * @param connection
     * @param HttpServletRequest
     * @throws Exception
     */
    public Document getRequest(HttpServletRequest request) throws SAXException, BizException {
        InputStream requestInputStream = null;
        Document document = null;

        try{
            String xmlContents = null;
            String strTempXml  = null;
            StringBuffer bufResponseXml = new StringBuffer();
            requestInputStream = request.getInputStream();
            BufferedReader dataIn = new BufferedReader(new InputStreamReader(requestInputStream, "UTF-8"));

            while ((strTempXml = dataIn.readLine()) != null) {
               bufResponseXml.append(strTempXml).append("\n\r");
            }

            xmlContents = bufResponseXml.toString();
            //log.info("xmlContents:\n"+xmlContents);
            //log.info("==================================");

            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            try{
                document = builder.parse(new InputSource(new StringReader(xmlContents)));
            }catch(Exception e){
                if(strTempXml == null || "".equals(strTempXml)){
                    log.error("===============방어코드 작동===시작====================");
                    Enumeration enums = request.getParameterNames();
                    StringBuffer sb = new StringBuffer();
                    while (enums.hasMoreElements()) {
                        String param = (String)enums.nextElement();
                        sb.append(param).append("=").append(request.getParameter(param));
                    }
                    log.error("==> "+sb.toString());
                    document = builder.parse(new InputSource(new StringReader(sb.toString())));
                    log.error("===============방어코드 작동===끝====================");
                }
            }

            if(document == null){
                throw new SAXException("Document is null!!");
            }

            log.debug( "\n"+XmlUtil.DocumentToString(document));
        } catch(SAXException se){
            log.error(getClass(), se);
            throw new SAXException(se);
        } catch(Exception e) {
            log.error(getClass(), e);
            throw new BizException(Message.getMsg("common.error"), e);
        } finally {
            try {
                if (requestInputStream != null) requestInputStream.close();
            } catch (IOException e) {
                throw new BizException(Message.getMsg("common.error"), e);
            }
        }
        return document;
    }

**Comment by gunlee01** [comment]
이미 request body를 앞에서 읽어서 그럴 듯 한데 아마 최신 버전으로 업그레이드 하시면 문제가 없을 듯 합니다. 
문제가 다시 발생하시면 이슈를 다시 오픈해 주세요.
