### ISSUE TITLE
특정 인터셉터에서 반복적으로 수행하는 SQL 설정에서 제외 가능할까요?

### ISSUE THREAD

**Issue by moonkoo88** [scouter-project/scouter#567]
WAS(SAP NetWeaver) 특성 상 세션 클러스터를 위해 인터셉터에서 SQL을 여러번 실행하는데요.
반복되는 SQL이 여러번 찍히다보니 이를 그냥 예외처리 하고 싶은데
설정에서 컨트롤 가능한 부분일까요?

**Comment by gunlee01** [comment]
특정 SQL 프로파일링을 선택적으로 제공하는 기능은 없습니다.
