### ISSUE TITLE
xlog가 랜덤으로 수집되지 않는 현상

### ISSUE THREAD

**Issue by naka018** [scouter-project/scouter#568]
안녕하세요.
scouter 2.6버전을 사용중입니다.

하나의 스카우터 서버에 20개정도의 에이전트 호스트를 연결해서 사용하다가
같은리전에서 pod가 새롭게 추가되어 20개정도의 에이전트 호스트를 더 연결했습니다.

그런데 신규로 연결된 호스트들의 xlog가 보이거나 보이지 않거나 합니다.
패턴이 없이 랜덤으로 보이거나 보이지 않아서 많이 당황스러운 상황입니다.
특정 호스트만 xlog가 보이지 않는 현상이 아니고,
특정 서비스에서만 그런것도 아니고,
특정 시간대에만 그런것도 아닙니다.
같은시간의 같은서비스도 어떤것은 xlog가 보이고 어떤 것은 xlog가 제대로 보이지 않습니다. ('No xlog profile collected')
타임존도 모두 동일하고, 
기존의 호스트에서의 설정과 달라진 부분이 하나도 없는데, 정상수집되지 않습니다.

혹시 의심가는 상황이나 비슷한 경험 있으시면 공유 부탁드립니다.
* 필요하신 설정정보 있으시면 내용 보강하겠습니다.

**Comment by gunlee01** [comment]
혹시 클라이언트의 Console 등에서 찍히는 로그는 없나요?
만약 프로파일이 존재하는데 보여주지 못하는 거라면 특정 프로파일 STEP이 추가되었지만 클라이언트 구버전을 사용하는 경우 STEP 인식이 되지 않아 그럴수 있습니다.

프로파일이 존재하지 않는다면
일단 동일 시간대에 일부의 프로파일이 존재하지 않는다면
UDP 패킷이 손실되어 그럴수도 있을 듯 합니다. 
이경우 OS상의 UDP 사이즈를 키워주거나
net_udp_packet_max_bytes=60000
을 좀 적게 조절해 보면 해결이 됩니다. 
net_udp_packet_max_bytes=30000 정도로 세팅해보세요.
단 net_udp_packet_max_bytes이 작을수록 패킷을 더 나누어 보내므로 가능하면 OS값을 키우는 것을 권장드립니다.

**Comment by naka018** [comment]
net_udp_packet_max_bytes=30000 세팅으로 해결된 것 같습니다.
감사합니다!
