### ISSUE TITLE
특정 Exception의 경우 xlog에서 error로 나오지 않게 할수 있는 기능추가 요청

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#572]
특정 Exception의 경우 xlog에서 제외할수 있는 기능을 넣어주심 유용하게 사용될것 같습니다 ^^

Ex) error = ClientAbortException: java.net.SocketException: Broken pipe (Write failed)

**Comment by gunlee01** [comment]
의견 감사합니다.
검토해 보도록 하겠습니다.
