### ISSUE TITLE
특정 시간대 Alert 무시 방법 문의

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#574]
Alert Script와 slack을 이용하여 기능을 사용중입니다.
특정 시간대에는 slack을 무시하고 싶은데 혹시 가능한지 문의 드립니다.

**Comment by gunlee01** [comment]
Alert scripting을 통해서 특정 시간대만 알림을 보내도록 하시면 어떨까요?
https://gunsdevlog.blogspot.com/2018/05/scouter-customizable-alert.html

**Comment by lu8300test** [comment]
> Alert scripting을 통해서 특정 시간대만 알림을 보내도록 하시면 어떨까요?
> https://gunsdevlog.blogspot.com/2018/05/scouter-customizable-alert.html

도움 주신 방법으로 잘 해결하였습니다. 감사합니다.
