### ISSUE TITLE
[문의] xlog 삭제 주기 

### ISSUE THREAD

**Issue by jinseo-jang** [scouter-project/scouter#575]
안녕하세요.

수집 서버의 purge 관련 설정의 아래처럼 default 로 사용중인데요,
profile이든 xlog 든 삭제되는 기준이 해당 값(일자) 안에 드는 모든 파일을 지우는것인지
해당 값 이후 것 부터 지우는 것인지 궁금합니다.

현재 날짜 기준으로(3/21)으로 databases 폴더에
2/21까지 있는데 xlog 데이타는 현재 날짜를 제외한 모든 폴더에서
지워져 있어 여쭈어 봅니다.

```
#Retaining date for automatic deletion.
mgr_purge_xlog_keep_days=30

#Deprecated : use mgr_purge_xlog_keep_days
mgr_purge_xlog_without_profile_keep_days=30

#Retaining date for automatic deletion. delete profile data first.
mgr_purge_profile_keep_days=10

#Deprecated : use mgr_purge_profile_keep_days
mgr_purge_keep_days=10

#Activating automatic deletion function in the database
mgr_purge_enabled=true
```

**Comment by gunlee01** [comment]
디스크의 80%이상이 사용되면 이전 일자까지의 profile -> xlog -> 전체 데이터 순으로 삭제합니다.

**Comment by spc1jh** [comment]
> 
> 
> 디스크의 80%이상이 사용되면 이전 일자까지의 profile -> xlog -> 전체 데이터 순으로 삭제합니다.

전체 데이터가 아닌 오래된 날짜 순(profile & xlog 또는 Profile 우선)으로 지워지게 변경 안될까요?
오래된 항목만 지워질걸로 예상하고 있는데 최근 항목이 지워져버려서 분석시 애로사항이 있습니다. 
그래서 이전 항목의 전체 profile데이터가 삭제가 되지 않게 하기 위해서는 사람이 수동으로 Disk 임계치가 다가올 경우 오래된 것부터 지워줘야 최근 항목을 남겨 둘수가 있는 상황입니다.

**Comment by gunlee01** [comment]
@spc1jh  `profile -> xlog -> 전체 데이터 순`을
좀 더 자세히 말씀드리면

디스크 용량을 확보하기 위해 profile을 과거부터 현재일 -1일까지 순차적으로 삭제를 합니다.
삭제중에 용량이 확보된다면 더 이상 삭제를 하지 않습니다.

마찬가지로 xlog도 동일하게 삭제하며 용량을 확보합니다.
마지막으로 전체 데이터를 과거일부터 현재일까지 하루치씩 순차적으로 삭제하면서 디스크 용량을 확보합니다.

Disk 임계치가 도달하지 않도록
counter 파일의 삭제 주기, xlog 삭제 주기, profile 삭제 주기를 설정을 통해 여유있게 지정하시는게 좋습니다.

제가 본 사이트들을 대략 
counter는 30일 ~ 1년이상
xlog는 7일 ~ 1개월 가량
profile은 3일 ~ 15일 가량 정도를
보관하는 곳이 많았습니다.
물론 디스크 용량과 매일 생성되는 데이터량을 보고 적적히 설정해야겠죠.
