### ISSUE TITLE
[문의] error rate 수치 문의

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#576]
안녕하세요.
제공되는 기능중 Error Rate를 커스텀 마이징해서 오류율이 높을때 알림을 해주는 서비스를
구현하여 사용을 준비하고 있습니다. 사용에 앞서 몇가지 궁금한점이 있어 문의 드립니다.

1. $counter.floatValue(); 을 하여 오류율을 받게 되는데 각 alert별로 해당 코드의 값들이 다른가요??
1-1 해당 오류율은 어떻게 산출되는 것인가요?? 

2. 10초에 한번 체크하고 그 안에 오류가 3회 이상일때 알림을 받고 싶은데 그렇게 할려면 어떻게 해야지 할까요??

지난번처럼 참고할수 있는 코드나 레퍼런스가 있으면 링크라도 주시면 도움 될것같습니다
감사합니다.

**Comment by gunlee01** [comment]
알림 스크립팅은 각 성능 카운터의 값을 기준으로 사용자 정의 알람을 구성하는 부분입니다.
Error Rate는 말 그대로 Error Rate 차트에 나타나는 에러율 값입니다.($counter.floatValue()는 현재 시점의 에러율을 값을 float 형태로 반환합니다.)
즉 (XLog에서 Error로 마킹된 요청 건수) / (전체 요청 건수) 입니다.

따라서 두 번째 질문인 10초에 오류 3회라는 조건은 성립하지 않습니다.

만약 XLOG에 에러가 10초에 3회 발생한 경우 알림을 주려면
XLog Server Plugin(Built in plugin) 을 개발하여야 합니다. 
Server Plugin 개발은 다음 링크를 참고해 보세요.

https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Plugin-Guide_kr.md
