### ISSUE TITLE
무료 사용 문의

### ISSUE THREAD

**Issue by usuall** [scouter-project/scouter#577]
사용상의 문의드립니다.
혹시 공공기관 또는 상용으로 서비스 시에 사용해도 라이선스에 문제가 없는지요?

**Comment by gunlee01** [comment]
Scouter는 Apache 2 라이선스로 배포가 됩니다.
공공, 상용 서비스에서 사용이 가능합니다.

**Comment by usuall** [comment]
답변 감사드립니다. ^^
