### ISSUE TITLE
특정 파일시스템 사용량 제외 설정

### ISSUE THREAD

**Issue by usuall** [scouter-project/scouter#578]
문의드립니다. 

/proc 와 같은 파일시스템이 100% 사용중입니다.
해당 부분으로 alert에 빈번히 메시지가 들어오는데요.
해당 파일시스템만 제외하고자 하는 경우 어떻게 해야 하는지요?

또는 다수의 파일시스템을 개별로 파일시스템 용량을 체크할수 있도록 제어 할수 있는지 궁금합니다. 

감사합니다.

**Comment by gunlee01** [comment]
`disk_alert_enabled=false`로 전체 비활성화가 가능합니다.
`disk_ignore_names` 옵션이 있는데 한번 사용해 보시기 바랍니다.
`disk_ignore_names=/proc` 처럼 사용하면 될 것 같네요.

**Comment by usuall** [comment]
답변 감사드립니다.
혹시 복수의 파일시스템에 대해 '무시 옵션' 사용가능한지요?
disk_ignore_names=/proc;/proc2;/proc3

**Comment by wellstyle** [comment]
@usuall 저도 AWS EC2가 /dev/loop0 ~ /dev/loop5 디스크에서 100% 사용 상태라, 관련 내용 찾아보다가 답변 달아봅니다.

1. `disk_alert_enabled`, `disk_ignore_names` 옵션은 `host.agent` 설정입니다.
2. `disk_ignore_names` 옵션은 `,(comma)` 구분해서 입력하면 될 것 같습니다[(소스 참고)](https://github.com/scouter-project/scouter/blob/master/scouter.agent.host/src/main/java/scouter/agent/Configure.java#L252). 예를 들면 `disk_ignore_names=/dev/loop0,/dev/loop1`

아래 문서 보시면 도움이 되실거에요.
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Configuration.md#host-agent-options

**Comment by usuall** [comment]
wellstyle님.
감사드립니다. 테스트 해 보겠습니다. :-)
