### ISSUE TITLE
scouter-server embedded 서버 비활성화

### ISSUE THREAD

**Issue by han507** [scouter-project/scouter#579]
안녕하세요.
scouter-server 2.6.0 사용중입니다.
embedded 서버를 사용하지 않게 하기위해 아래 같이 설정했지만 6180 port를 계속 열고 있습니다.
의도된 동작인지 궁금합니다.
- net_http_server_enabled=false
- net_http_api_enabled=false

잘 사용하고 있습니다. 
정말 감사합니다.

**Comment by gunlee01** [comment]
구버전이라면 input_telegraf_enabled 가 true 인지도 확인해보세요.
최근 버전이라면 클라이언트에서 telegraf config에 들어가서 enabled에 체크를 해제해보세요.
()
telegraf 지원 기능이 true라면 net_http_server_enabled가 자동으로 활성화 됩니다.
