### ISSUE TITLE
XLog의 ip정보

### ISSUE THREAD

**Issue by haha23h** [scouter-project/scouter#580]
XLog에 들어오는 각service의 IP가 모두 127.0.0.1로 들어옵니다.ㅠ.ㅠ

웹서버는 nginx
WAS서버는 톰캣사용중이고
scouter버전 2.5.0입니다..

**Comment by gunlee01** [comment]
reverse proxy에서 localhost로 ip가 변경되고 원본 아이피를 유지할 수 없다면 trace_http_client_ip_header_key 옵션을 통해 처리해보세요.
