### ISSUE TITLE
특정 서비스 Alert 제외 요청

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#582]
현재 서비스에 ElapsedTime을 기준으로 Slack과 연동하여 알림을 받고 있습니다.
하지만 대량 조회서비스등 서비스 지연 시간이 불가피한 서비스 들이 있는데
해당 서비스를 xlog에는 표시 되지만ElapsedTime에서는 제외할수 있는 방법이 있는지 문의 드리며..;
없다면 차후 버전에서 추가가 가능한지 검토 부탁드립니다.

**Comment by gunlee01** [comment]
xlog에 표시되는 특정 서비스를 elapsed time에서 제외하는 기능은 없습니다.
응답시간 평균에서 제외하려면 discard service로 아예 xlog에서 제외해야 합니다.
