### ISSUE TITLE
CPU 사용률 관련 문의 드립니다.

### ISSUE THREAD

**Issue by rindol** [scouter-project/scouter#583]
CPU 사용률 관련 WARNING, FATAL Alert이 감지 기준 관련하여 아래 문의 드립니다.
코어가 다수인 경우, 첫 번째 코어만 감지를 하는 것인지 아니면 전체 코어의 평균치를 감지하는 것인지 문의 드립니다.

현재 적용되어 있는 서비스에 CPU 사용률 관련 WARNING, FATAL Alert이 감지되어, 해당 서버 호스팅 업체 확인 결과 Alert 발생 시각에 첫 번째 코어 사용률이 높긴 했으나 타 코어 유휴율이 높아 문제가 없다고 답변을 받아 확인 요청 드리는 부분입니다.

**Comment by gunlee01** [comment]
전체 코어의 평균값입니다.
