### ISSUE TITLE
[문의] database/00000000 폴더 정리 관련

### ISSUE THREAD

**Issue by jinseo-jang** [scouter-project/scouter#595]
안녕하세요. 
부족한 disk 에서 scouter 를 사용하다 보니 80% 임계 설정에 따라 log가 purge 되고 있습니다.
database 폴더아래 날짜별 폴더 사이즈를 보면 대동소이 합니다만 유독 00000000
이 폴더만 사이즈가 22GB 정도 입니다.  보니가 text_sql.data 가 저 사이즈를 차지하고 있는데
disk 정리차 이 파일 또는 이 폴더를 정리 할수 있는 방법이 있을까요?

다른 날짜의 폴더를 지워보야 disk 확보가 안되서 문의 드립니다.

**Comment by gunlee01** [comment]
서버를 내리고 그냥 text_sql.data를 지우면 됩니다.
다만 과거 프로파일의 SQL들은 딕셔너리가 없으므로 해시코드로만 보이게 됩니다.
(디스크 사이즈로 볼때는 과거 XLog를 오래 저장할 것 같지는 않은데요. 꼭 봐야 한다면 다른 서버에 Copy하여 Server를 구성해 놓으면 될 것 같습니다.)
