### ISSUE TITLE
database backup 관련

### ISSUE THREAD

**Issue by oing0125** [scouter-project/scouter#599]
데이터베이스 백업 관련 문의드립니다.

Scouter 서버 교체를 준비하고 있습니다.
데이터 이관 테스트를 위해
scouter-server 폴더 하위 database를 제외한 모든 파일 및 디렉토리를 신규 서버에 복사 후
database 폴더 내 특정 폴더(20190508~20190512)만 다른 서버에 복사하였습니다.

그리고 새로 만들어진 서버에서 startup.bat 실행 후 클라이언트에서 조회 시도해보았으나
아래와 같은 에러로 인해 조회되지 않습니다.

An internal error occurred during: "XLog Loading...(2019-05-12 14:57~15:02)".
java.lang.NullPointerException

![scouter 문의](https://user-images.githubusercontent.com/16523990/57674287-cfae8a00-7659-11e9-8c97-32c1ec500195.PNG)

위 방법이 안된다면 혹시 데이터 백업을 위한 다른 방법이 존재하나요?

**Comment by gunlee01** [comment]
00000000 폴더도 한번 복사해 보시기 바랍니다.
쓰기가 완벽히 되지 않은 상태에서 파일이 복사될 수도 있으니 구동중인 서버를 중지 후에 복사하시는 게 좋을 듯 합니다.

**Comment by oing0125** [comment]
서버 중지 후 00000000 폴더 추가해서 실행해도
동일한 증상 반복됩니다.

![scouter문의 00000000추가](https://user-images.githubusercontent.com/16523990/57679920-6a619580-7667-11e9-9f34-5a7d34dc17a6.PNG)

**Comment by gunlee01** [comment]
기존 서버로 붙어서 조회하면 이상이 없나요?
SCOUTER 콜렉터에서 사용하는 파일은 scouter/server 내부에 다 포함되어 있습니다.
외부에 따로 저장되는 파일이 없으니 통째로 복사하면 문제가 없어야 합니다.

**Comment by oing0125** [comment]
기존의 문제는 scouter를 완전 종료하지 않고 폴더를 복스해서 발생한 듯 합니다.

scouter 서버 완전 종료 후 database에서 특정 폴더만 복사하여 서버 정상 동작 확인하였습니다.

도움주셔서 감사합니다.
