### ISSUE TITLE
[확인요청] batch agent 버전 확인 요청

### ISSUE THREAD

**Issue by gogomasaru** [scouter-project/scouter#600]
이번에 2.6.2를 설치 후 batch agent 가동 시 아래 처럼 2.0.0으로 출력됩니다.

  ____                  _            
 / ___|  ___ ___  _   _| |_ ___ _ __ 
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |   
 |____/ \___\___/ \__,_|\__\___|_|                                      
 Open Source S/W Performance Monitoring  
 Scouter version 2.0.0
 
Scouter Batch Agent Version 2.0.0 2018-09-28 06:24 GMT
20190514 04:38:36 [SCOUTER] scouter_enabled=true

pom.xml 보니 2.0.0으로 되어있던데 오타 확인 부탁드립니다. 

<groupId>io.github.scouter-project</groupId>
<artifactId>scouter-agent-java</artifactId>
<version>2.0.0</version>

**Comment by gunlee01** [comment]
batch agnent는 더 이상 유지보수가 되지 않아서 버전이 고정되었습니다.
