### ISSUE TITLE
[문의]database 디렉토리 위치 변경

### ISSUE THREAD

**Issue by jinseo-jang** [scouter-project/scouter#604]
안녕하세요.
database 폴더가 위치한 FS용량이 부족하여 넉넉한 FS가 마운트된 폴더로 옮기려고 하는데요,
혹시 database폴더만(scouter 폴더 전체가 아닌) 다른 위치로 설정 할 수 있을까요?

**Comment by gunlee01** [comment]
db_dir 설정을 사용하세요.
