### ISSUE TITLE
[문의] 특정 Exception를 에러처리에서 제외하고자 합니다.

### ISSUE THREAD

**Issue by onevs108** [scouter-project/scouter#605]
안녕하세요.

scouter에 slack plug in를 도입하여 운영중에 있습니다.
에러의 알람이 중에 com.mysql.jdbc.exceptions.jdbc4.CommunicationsException 에 대한부분은
알람을 받고 싶지 않아서 conf에 예외 exception으로 설정을 하였는데도, 계속적으로 알람이 오게 되어서 문의 드립니다.

java agent의 conf 설정은 아래 와 같습니다.

$ cat scouter_boryeong.conf 
### scouter java agent configuration sample

obj_name=localfood_boryeong_live
net_collector_ip=127.0.0.1
net_collector_udp_port=6100
net_collector_tcp_port=6100
hook_exception_hanlder_exclude_class_patterns=CommunicationsException
--------------------------------
hook_exception_hanlder_exclude_class_patterns=com.mysql.jdbc.exceptions.jdbc4.CommunicationsException 도 했는데 동일하게 동작하지 않았습니다.

혹시 제가 잘못판단하거나 다른 방법으로 예외처리하는 방법이 있는지 알려주시면 감사하겠습니다.

감사합니다.

**Comment by bill23-kim** [comment]
hook_exception_hanlder_exclude_class_patterns 오타인것 같습니다.
hanlder -> handler

**Comment by gunlee01** [comment]
`hook_exception_hanlder_exclude_class_patterns` 는 `hook_exception_handler_method_patterns` 옵션에서 error로 표기할 exception handler method 지정시 handler에 전달되는 exception 클래스 중에서 특정 클래스를 제외하는 옵션입니다.  

`hook_exception_exclude_class_patterns` 옵션을 사용하셔야 합니다.
`hook_exception_exclude_class_patterns=com.mysql.jdbc.exceptions.jdbc4.CommunicationsException`

그리고 SQL 처리중 발생하는 에러는 무조건 에러로 프로파일링 합니다.
이를 제외하려면
`xlog_error_on_sqlexception_enabled` 옵션을 false로 세팅하여야 합니다.

**Comment by onevs108** [comment]
네..제가 잘못 이해하고 반영한거네요. ㅜㅜ
말씀주신데로 설정하니 잘 되네요.^^;

도움 주셔서 감사합니다.~
