### ISSUE TITLE
installing the tomcat client 

### ISSUE THREAD

**Issue by Kedesai** [scouter-project/scouter#606]
I am new to scouter project. I installed the latest server 2.62 Server and the viewer but I am not sure how to install the client on the host to be monitored. Per the documentation download the 3.2. Start Tomcat with Scouter agent. I don't see any asset which has the scouter-yyyyMMdd.tar.gz format. Can you help where to get the java client? Below is the documentation but I cannot find it:

3.2. Start Tomcat with Scouter agent
Download scouter-yyyyMMdd.tar.gz
Release Page
Extract the file.(you can see scouter.agent.jar file on the directory ./scouter/agent.java)
Add -javaagent JVM options on your java application. (Refer to java option example below.)
3.2.1 Java Option example
Append below options in ${TOMCAT_DIR}/bin/catalina.sh or startup.sh

JAVA_OPTS=" ${JAVA_OPTS} -javaagent:${SCOUTER_AGENT_DIR}/scouter.agent.jar"
JAVA_OPTS=" ${JAVA_OPTS} -Dscouter.config=${SCOUTER_AGENT_DIR}/conf/scouter1.conf"
JAVA_OPTS=" ${JAVA_OPTS} -Dobj_name=myFirstTomcat1"
${SCOUTER_AGENT_DIR} means the directory that contains scouter.agent.jar file.
If you are using multiple Tomcat instances in one VM, you must define their respective configuration files.
You can specify the conf file through the -Dscouter.config environment variable as in the example above.
Also, in this case, you should specify the name through the obj_name option so that the name of the monitored object is not duplicated in one VM.

**Comment by bill23-kim** [comment]
The English document is not updated. There is no such filename anymore.The attachments in the release page are clients and other modules.
scouter-yyyyMMdd.tar.gz was replaced by scouter-min-xx.xxx.
Client can download what fits your client environment in scouter.client.product-xxx.xxx-type files.

**Comment by gunlee01** [comment]
The client program may be setup on your PC. 
Check this blogging for your work, https://translate.google.co.kr/translate?hl=ko&sl=ko&tl=en&u=https%3A%2F%2Fgunsdevlog.blogspot.kr%2F2017%2F07%2Fscouter-apm-1.html
