### ISSUE TITLE
스카우터 클라이언트에서 로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by darknatas** [scouter-project/scouter#610]
안녕하세요

스카우터 클라이언트에서 로그인을 시도하면 
'Network connection failed : Read Timed out' 문구가 보이면서 로그인이 되지 않습니다.

해결방법 문의 드립니다.

![이미지 1](https://user-images.githubusercontent.com/51356564/58857076-47168d00-86df-11e9-926a-21bf50662bdf.png)

**Comment by gunlee01** [comment]
closed duplication on the facebook post.
