### ISSUE TITLE
webapp - xlog데이터에서 sql 쿼리를 볼 수없나요?

### ISSUE THREAD

**Issue by Neptunium1129** [scouter-project/scouter#611]
클라이언트에서 xlog를 볼때 쿼리가 나오는 기능을 웹에 구현하려고 하 webapp을 사용하려고 하는데요

스웨거UI로 확인을 해보았으나 

xlog데이터에 쿼리는 나오지않고 서머리 sql에서만 기능을 지원하는것 같습니다..

xlog 데이터에도 서머리와 관련된 키가없는것 같네요

해당 기능은 구현이 불가능한건가요??

**Comment by Neptunium1129** [comment]
txid를 이용해서 프로필 데이터로 찾으면 가능은 할 것 같습니다.

**Comment by gunlee01** [comment]
xlog는 요청에대한 메타정보이고 쿼리등의 상세 내용은 프로파일을 txid로 조회하셔야합니다.

**Comment by Neptunium1129** [comment]
감사합니다!
