### ISSUE TITLE
API “v1/object” 500 -null

### ISSUE THREAD

**Issue by dirandau** [scouter-project/scouter#613]
수고 많으십니다. 
Scouter 는 2.6.2를 사용하고 있습니다. API “v1/object”를 사용하면 500 오류가 발생합니다. 

설정과 로그를 공유드립니다. 서버 정보는 XXX나 (aaa)등으로 가렸습니다. 

"/home/XXX/scouter/server/conf/scouter.conf"
net_http_server_enabled=true
net_http_api_enabled=true
net_http_port=6180
net_http_api_allow_ips=localhost,127.0.0.1,XXX.XXX.XXX,XXX,YYY.YYY.YYY.YYY
net_collector_ip_port_id_pws=127.0.0.1:6100:(id):(pw),XXX.XXX.XXX,XXX:(port):(id):(pw)

"http-request-2019_06_21.log"
10.192.13.60 - - [21/6¢Æ¢Æ/2019:11:30:44 +0900] "GET /scouter/v1/object HTTP/1.1" 500 86 "-" "Mozilla/5.0 (Window    s NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

"request-20190621.log"
20190621 11:30:40.662 unknown(register) OBJECT_RESET_CACHE

"server-20190621.log"
 46   ____                  _
 47  / ___|  ___ ___  _   _| |_ ___ _ __
 48  \___ \ / __/   \| | | | __/ _ \ '__|
 49   ___) | (_| (+) | |_| | ||  __/ |
 50  |____/ \___\___/ \__,_|\__\___|_|
 51  Open Source S/W Performance Monitoring
 52  Scouter version 2.6.2
 53
 54 20190621 11:30:10 Load Account Group File
 55 20190621 11:30:10 Load Account File
 56 20190621 11:30:10 Load Account Group File
 57 20190621 11:30:10 udp listen 0.0.0.0:6100
 58 20190621 11:30:10       udp_host=0.0.0.0
 59 20190621 11:30:10       udp_port=6100
 60 20190621 11:30:10 Load Account File
 61 20190621 11:30:10       udp_buffer=65535
 62 20190621 11:30:10       udp_so_rcvbuf=4194304
 63 20190621 11:30:10       tcp_port=6100
 64 20190621 11:30:10       cp_agent_so_timeout=60000
 65 20190621 11:30:10       cp_client_so_timeout=8000
 66 20190621 11:30:10 [S104] New OBJECT  objType=aix objHash=z1saomor objName=/(ccc) addr=(ccc's ip) 1.8.6 2018    -05-13 12:40 GMT alive 2019-06-21 11:30:10.646 {detected=aix}
 67 20190621 11:30:10 [S145] GeoIP db file is not readable : /home/(XXX)/scouter/server/conf/GeoLiteCity.dat
 68 20190621 11:30:11 [S104] New OBJECT  objType=tomcat objHash=z101alqh objName=/(aaa)/(aaa's name) addr=(aaa's IP) 1.8    .6 2018-05-13 12:40 GMT alive 2019-06-21 11:30:11.434 {detected=weblogic,ADC=false}
 69 20190621 11:30:11 [S104] New OBJECT  objType=linux objHash=x1f0mqp7 objName=/(aaa) addr=(aaa's IP) 1.8.6 2018-05    -13 12:40 GMT alive 2019-06-21 11:30:11.569 {detected=linux}
 70 20190621 11:30:11 [S104] New OBJECT  objType=tomcat objHash=x16pbp13 objName=/(bbb)/(bbb's name) addr=(bbb's IP)    1.8.6 2018-05-13 12:40 GMT alive 2019-06-21 11:30:11.569 {detected=weblogic,ADC=false}
 71 20190621 11:30:11 [S104] New OBJECT  objType=tomcat objHash=z9estl4 objName=/(ccc)/(ccc's name) addr=(ccc's IP)   1.8.6 2018-05-13 12:40 GMT alive 2019-06-21 11:30:11.631 {detected=weblogic,ADC=false}
 72 20190621 11:30:12 [S104] New OBJECT  objType=aix objHash=xf5ltav objName=/(bbb) addr=(bbb's IP) 1.8.6 2018-    05-13 12:40 GMT alive 2019-06-21 11:30:12.016 {detected=aix}
 73 20190621 11:30:15 [S215] Alert rule detected : ErrorRate.alert
 74 20190621 11:30:15 PLUG-IN : scouter.server.plugin.IAlert loaded #xk8o1a4
 75 20190621 11:30:15 PLUG-IN : scouter.server.plugin.ICounter loaded #xf07gn5
 76 20190621 11:30:15 PLUG-IN : scouter.server.plugin.IObject loaded #x1smkn0s
 77 20190621 11:30:15 PLUG-IN : scouter.server.plugin.IXLog loaded #x1v5bqcg
 78 20190621 11:30:15 PLUG-IN : scouter.server.plugin.IXLog loaded #x99kjgm
 79 20190621 11:30:15 PLUG-IN : scouter.server.plugin.IXLogProfile loaded #xms972v
 80 20190621 11:30:15 PLUG-IN : scouter.server.plugin.ISummary loaded #x12o1k3s

"webapp-2019_06_21.log"
 11:30:14.148 [scouter.server.http.HttpServer]  INFO  org.eclipse.jetty.server.Server[444] - Started @7054ms
217 #g3p0 11:30:44.488 [qtp9322147-79]  ERROR s.w.f.e.m.GenericExceptionMapper[66] - [WebApplicationException] 500     - null, [uri]v1/object
218 java.lang.NullPointerException: null
219         at scouter.lang.counters.CounterEngine.getFamilyNameFromObjType(CounterEngine.java:497)
220         at scouterx.webapp.model.scouter.SObject.<init>(SObject.java:51)
221         at scouterx.webapp.model.scouter.SObject.of(SObject.java:64)
222         at scouterx.webapp.layer.consumer.ObjectConsumer.lambda$retrieveObjectList$0(ObjectConsumer.java:43)
223         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
224         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
225         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
226         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
227         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
228         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
229         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
230         at scouterx.webapp.layer.consumer.ObjectConsumer.retrieveObjectList(ObjectConsumer.java:44)
231         at scouterx.webapp.layer.service.ObjectService.retrieveObjectList(ObjectService.java:41)
232         at scouterx.webapp.layer.controller.ObjectController.retrieveObjectList(ObjectController.java:64)
233         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
234         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
235         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
236         at java.lang.reflect.Method.invoke(Method.java:498)
237         at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(Re    sourceMethodInvocationHandlerFactory.java:76)
238         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaRe    sourceMethodDispatcher.java:148)
239         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaR    esourceMethodDispatcher.java:191)
240         at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDis    patch(JavaResourceMethodDispatcherProvider.java:243)
241         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJav    aResourceMethodDispatcher.java:103)
242         at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
243         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
244         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
245         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
246         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
247         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
248         at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
249         at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
250         at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
251         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
252         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
253         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
254         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
255         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
256         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
257         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
258         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
259         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
260         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
261         at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
262         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
263         at scouterx.webapp.framework.filter.ReleaseResourceFilter.doFilter(ReleaseResourceFilter.java:44)
264         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
265         at scouterx.webapp.framework.filter.NoCacheFilter.doFilter(NoCacheFilter.java:40)
266         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
267         at scouterx.webapp.framework.filter.CorsFilter.doFilter(CorsFilter.java:65)
268         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
269         at scouterx.webapp.framework.filter.LoggingInitServletFilter.doFilter(LoggingInitServletFilter.java:50)
270         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
271         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
272         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
273         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
274         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
275         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
276         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
277         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
278         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
279         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
280         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
281         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
282         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521)
283         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
284         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
285         at org.eclipse.jetty.server.Server.handle(Server.java:564)
286         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
287         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
288         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
289         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
290         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
291         at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
292         at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
293         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
294         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
295         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
296         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
297         at java.lang.Thread.run(Thread.java:748)

**Comment by gunlee01** [comment]
재기동해도 계속 발생하는지 궁금합니다.
그리고 collector에 생성된 counters.site.xml 내용을 공유해주실수 있나요? 

원인은 명확하지 않으나 일단 NPE 에러나는 부분은 값이 없으면 UNKNOWN으로 세팅하고 넘어가도록 패치 중입니다.

**Comment by dirandau** [comment]
안녕하세요. 이번 2.7.0 버전으로 업데이트 하고 문제가 해결되었습니다. 
현재는 /v1/object 시 정상 출력됩니다. 설정은 이전 버전에서 설정한 내용을 그대로 가져왔습니다. 
항상 감사드립니다.
