### ISSUE TITLE
 @RequestMapping의 파라메터를  javaBean 객체로 받을때, 객체에 전달된 파라메터를 스카우터가 분석할때, toString()을 호출하는것 같습니다.

### ISSUE THREAD

**Issue by Neptunium1129** [scouter-project/scouter#624]
해당 객체의 Class 에 overriding 된 toString()에서 NullPointException을 발생시켜 시스템에서 오류가 발생합니다.
java.lang.NullPointerException
   vo.FrmFormletVO.toString(FrmFormletVO.java:256)
   at scouter.agent.trace.TraceMain.startSpringControllerMethod(TraceMain.java:984)

![이미지 2](https://user-images.githubusercontent.com/32185134/62258987-b8f12580-b447-11e9-8936-579388ab022b.png)

![이미지 1](https://user-images.githubusercontent.com/32185134/62259112-3026b980-b448-11e9-9bf1-aad5abe9ca7f.png)

- scouter-agent-java-1.7.3.1.jar 사용중에는 정상이었으나
2.6.2에서는 오류가 발생하고 있습니다.

**Comment by gunlee01** [comment]
Spring 콘트롤러의 파라미터를 프로파일링 하기위해 파라미터가 존재하면 toString()이 호출됩니다.

일단 아래 옵션을 끄는 걸로 조치가 가능하실 듯 합니다.
`profile_spring_controller_method_parameter_enabled=false`
대신 메소드 파라미터값이 프로파일에 나오지는 않습니다.

컨트롤러 메소드의 파라미터를 보시려면 toString()에서 NullPointerException이 발생하지 않도록 조치하신 후에 위 옵션을 다시 활성화 시키셔야 할 것 같습니다.

**Comment by Neptunium1129** [comment]
감사합니다!
