### ISSUE TITLE
**unlabeled**:method

### ISSUE THREAD

**Issue by zepinos** [scouter-project/scouter#625]
안녕하세요.

Scouter 을 구축중입니다. 그런데, 로컬에서 Docker 로 돌릴 때와 다른 결과가 나와서 문의를 드립니다.

![주석 2019-08-02 192808](https://user-images.githubusercontent.com/6926839/62364239-f3e47d80-b55b-11e9-8d7c-578321eed058.png)

위의 이미지와 같이 **unlabeled**:method 로 표시되는 항목들이 많이 나오고 있습니다.

로컬과의 차이점은
- 로컬 OS 는 윈도우즈, 새롭게 구축한 서버는 CentOS 7.3
- 로컬은 AWS Corretto 11, 서버는 CentOS OpenJDK 11
- 로컬은 Tomcat 8.5.43, 서버는 Tomcat 8.5.* (좀 더 구버전)

소스는 동일합니다.

어떠한 경우에 이렇게 되는건지 궁금합니다. 해결 방법도 있을까요?

**Comment by gunlee01** [comment]
신규 설치시 어플리케이션 인스턴스를 띠우고 스카우터서버를 띠워서 그럴수도 있습니다. 메소드는 딕셔너리 인코당이 되는데 메소드를 등록하는 것은 클래스가 최초 로드될때 한번입니다. 아마도 어플리케이션을 재구동하면 나올것 같습니다.

**Comment by zepinos** [comment]
애플리케이션 재구동...이라면 scouter server 의 재시작인가요? 에이젼트 쪽은 재시작을 많이 했습니다.

서버를 띄우고 애플리케이션을 띄운 뒤 방화벽 문제로 한동안 통신에 제대로 안되긴 했습니다만...한 번 서버를 재시작 해보겠습니다.

**Comment by zepinos** [comment]
> 신규 설치시 어플리케이션 인스턴스를 띠우고 스카우터서버를 띠워서 그럴수도 있습니다. 메소드는 딕셔너리 인코당이 되는데 메소드를 등록하는 것은 클래스가 최초 로드될때 한번입니다. 아마도 어플리케이션을 재구동하면 나올것 같습니다.

서버 소스를 다시 압축해제하여 scouter.conf 만 옮겨서 실행 해보았고, agent 쪽 설정의 obj_name 도 변경해보았지만 동일한 현상이 발생하고 있습니다.

**Comment by zepinos** [comment]
왜 이렇게 나오는지 궁금합니다.

먼저 로컬에서 돌렸을 때 나오는 것입니다. DataDoingService 관련해서 3개가 연달아 나옵니다.

![주석 2019-08-05 142516](https://user-images.githubusercontent.com/6926839/62441264-5fae2c80-b78e-11e9-9017-648a38f4bb1c.png)

그런데, NCP 에 만든 VM 에 올린 서버에 넣으면...다음과 같이 1, 3번째 항목이 unlabeled 로 나옵니다.

![주석 2019-08-05 142414](https://user-images.githubusercontent.com/6926839/62441326-92f0bb80-b78e-11e9-9475-ab91797fa5d0.png)

상세 내용을 보면 3 개가 아래와 같이 나오는 항목입니다. (로컬 캡쳐입니다)

![주석 2019-08-05 142616](https://user-images.githubusercontent.com/6926839/62441345-ac920300-b78e-11e9-9f5b-eb0865ecf4d1.png)
![주석 2019-08-05 142804](https://user-images.githubusercontent.com/6926839/62441349-ae5bc680-b78e-11e9-9125-480e6d241a06.png)
![주석 2019-08-05 142738](https://user-images.githubusercontent.com/6926839/62441350-af8cf380-b78e-11e9-88c3-42f2181606e0.png)

scouter.conf 에는 아래와 같이 hook 이 설정되어 있습니다.

hook_method_patterns=*Service*.*

조언 부탁드립니다.

**Comment by gunlee01** [comment]
어플리케이션(WAS, SpringBoot 등등) 기동시 클래스 로딩 시점에 딕셔너리에 등록이 실패하였다고 밖에 생각되지 않는데요.
일단 Scouter Server(Collector) 재기동 -> 어플리케이션 재기동 -> Scouter WebApp 재기동
순으로 한번 해보시기 바랍니다.

**Comment by zepinos** [comment]
> 
> 
> 어플리케이션(WAS, SpringBoot 등등 agent가 설치된 java 어플리케이션) 기동시 클래스 로딩 시점에 딕셔너리에 등록이 실패하였다고 밖에 생각되지 않는데요... 지금까지 메소드명이 딕셔너리에 등록되는 부분에 대해 특별히 버그 리포팅이 된 내용은 없었습니다.

테스트 앱을 만들어서 확인을 해보니...Scouter Collector 가 있는 서버에서 연결하면 문제가 없고, 타 서버에서 방화벽을 거쳐서 연결을 하니 문제가 발생하네요. 혹시 Public Cloud 을 쓰는데, 패킷 등을 버리거나 하는 문제로 발생할 수 있는지, 이 경우 서버 측에서 패킷이 정상적으로 다 수신이 되고 있는지 확인할 방법이 있을까요?

> 
>     * Collector와 통신이 안되는 상황에서 어플리케이션(agent)를 기동한 상황에서는 메소드명이 딕셔너리에 등록되지 않는건 제약사항입니다.
>       일단 Scouter Server(Collector) 재기동 -> 어플리케이션 재기동 -> Scouter WebApp 재기동
>       순으로 한번 해보시기 바랍니다.

Collector 의 extweb 에 paper 을 넣은 상태이고, Collector 와 Agent 가 연결된 서버는 수차례 재시작을 해보았습니다.

**Comment by gunlee01** [comment]
일부는 나오고 일부는 나오지 않는 것으로 봐서는 통신쪽 문제가 아닐수도 있을 것 같긴한데요.
UDP 통신이 원활히 되는지는 아래 명령어로 테스트는 가능합니다.

`scouter.agent.jar`에 포함된 아래 유틸을 실행해보세요.
`java -cp ./scouter.agent.jar scouter.agent.netio.data.net.DataUdpAgent -h 127.0.0.1 -p 6100 -l 63000`

정상적으로 UDP 통신이 되면 scouter server의 SysOut 으로 출력됩니다.
`Receive unknown data, length=63000 from /127.0.0.1`

만약 수신 데이터에 대한 내용이 나오지 않는다면
-l 63000을 줄여보세요 32000 -> 16000 -> 8000 등으로.

**Comment by zepinos** [comment]
명령은 실행해보진 않았지만, tcpdump 로 데이터가 오고 있는 것은 확인했습니다. 다만 의심스러운게, Collector 서버에 테스트 프로그램을 만들고 실행했을 때 잘 되는데, 동일 프로그램을 별도의 VM 을 만들어서 네트워크를 통해 연결할 경우 저렇게 일부가 나오지 않는 문제가 재현되었습니다. OS 에 Java 만 설치하고 한거라 다른 변인은 없을 것으로 생각됩니다.
클라우드는 네이버 클라우드 플랫폼입니다.

**Comment by zepinos** [comment]
일단 AWS 에 인스턴스 생성해서 테스트 했을 때 (당연하지만) 문제가 없음을 확인했습니다. 그냥 NCP 문제인 것 같습니다. 물론 NCP 에서는 자기들 문제는 없고 패킷 Loss 문제가 아니냐고 하고, 그 외에 다른 변인은 없는 것 같아서...저도 그냥 여기서 포기해야 할 것 같습니다.

혹시나 tcpdump 의 패킷 정보를 분석할 수 있는 분이 계시다면, 서버와 에이젼트 쪽의 tcpdump 정보를 올려두겠습니다. diff 툴로 보면 사소한 차이가 있긴 한데, udp 쪽 패킷만 캡쳐한거라...어떠한 차이점인지 알 수가 없어서 저는 여기까지만 하는 것으로 하겠습니다. T.T



[tcpdump.zip](https://github.com/scouter-project/scouter/files/3470835/tcpdump.zip)

**Comment by zepinos** [comment]
해결했습니다. NCP 에서 확인해주셨는데, MTU 1500 이고, 1500 이 넘는 패킷은 잘라서 drop 한다고 하네요.

net_udp_packet_max_bytes=1400

이 옵션을 넣어서 해결했습니다. T.T
