### ISSUE TITLE
Akka, RestTemplate 연동

### ISSUE THREAD

**Issue by zepinos** [scouter-project/scouter#628]
Spring RestTemplate 을 이용해서 cURL 호출을 할 경우 Topology 에서는 보내는 쪽, 받는 쪽 모두 Scouter Java Agent 가 동작하고 있으나 보내는 쪽에서는 External 로 보이고 두 서버 자체는 연결이 안되는 형태가 되는데, 혹시 두 서버 간의 연결이 되도록 표시할 수 있는 방법이 있을까요?

그리고, Akka 을 테스트 중인데, Actor 로 질의를 보낼 때 결국 cURL 처럼 hook_service_patterns 으로 선언해야 보이는게 당연하다면 당연한건데, Profiler 에서는 결국 따로 보이기 때문에 추적이 좀 어려운 점이 있습니다. 이 역시 어쩔 수 없는 부분일까요?

조언 부탁드립니다.

**Comment by gunlee01** [comment]
Akka의 actor간 연결 추적은 지원되지 않습니다.

대부분 http 서비스간 연결 추적이 가능한데요
대응되지 않은 http client library를 사용하는 경우는 추적이 안될 수 있습니다.
클라이언트 화면의 xlog 상세 profile에서 확인 하였을 때에도 연결된 step이 안나온다면 연결 추적이 되지 않는 상태입니다. 이 경우는 topology에 연결되지 않은 상태로 보여지게 됩니다.
복합적인 조합으로 발생할 수 있는 부분이라 예측하기는 어렵고 연결이 되지 않는 간단한 샘플 프로그램이 있으면 원인을 추적해 볼 수 있을 듯 합니다.

**Comment by zepinos** [comment]
cURL 은 Spring 의 RestTemplate 로 했는데, 받는 서버가 Spring WebFlux (Netty) 라서 hook_service_patterns 으로 요청을 잡아내고 있었습니다. 아마 이런 문제 때문에 그런 것 같네요.
