### ISSUE TITLE
안녕하세요 스카우터 환경설정..질문드립니다 .

### ISSUE THREAD

**Issue by hwi94** [scouter-project/scouter#639]
다름이아니구요 .. 
1.	server ( scouter.conf )
2.	agent.java ( scouter.conf )
3.	agent.host ( scouter.conf )
4.	tomact ( catalina.sh ) 
크게 4가지라고 했을때, 
이렇게 많은 설성파일들이 있지않습니까.. ?
설정은 한곳에 몰아서 해도 상관없는것일까요 

예를들면 " NON-HTTP 서비스 추적하기 " 라는 글을보고왔는데요
옵션설정을 어디어디다하세요 라는말이 없는것같아서요.. 

####################
## 현재 저희는 수집서버와 agent 서버는 같은곳에 위치하므로 따로 기입하실 필요가 없습니다. 
#  net_collector_ip=XXXXXXXX
####################

####################
## Port Setting(default:6100)
#  net_collector_udp_port=6100
#  net_collector_tcp_port=6100
####################

####################
####################
## cpu waring 레벨 알림의 퍼센트입니다.(정수로 설정) (미설정시, 아래값이 default 입니다.)
#  cpu_warnig_pct= 80
####################

####################
## cpu fatal 레벨 알림의 퍼센트입니다.(정수로 설정)(미설정시, 아래값이 default 입니다.)
#  cpu_fatal_pct = 85
####################

####################
## 어느 기간동안 cpu를 체크할지를 지정합니다. (ms)(미설정시, 아래값이 default 입니다.)
#  cpu_check_period_ms = 600000
####################

####################
## 3이라면 CPU가 최근 5분간 90%를 3회 넘는 경우 알림을 발송하게 됩니다. (미설정시, 아래값이 default 입니다.)
#  cpu_waring_history = 3
#  cpu_fatal_history = 3
####################

####################
## 설정 시간동안 동일한 알림을 발송하지 않습니다. (미설정시, 아래값이 default 입니다.)
#  cpu_alert_interval_ms = 300000 
####################

####################
## Memory 알림 설정 옵션  (미설정시, 아래값이 default 입니다.)
#  mem_alert_enabled=false
#  mem_alert_interval_ms=30000
#  mem_warning_pct=80
#  mem_fatal_pct=90
####################

####################
## Disk 사용량 알림 설정 옵션 (미설정시, 아래값이 default 입니다.)
#  disk_alert_enabled=true
#  disk_warning_pct=70
#  disk_fatal_pct=90
####################

####################
####################

####################
####################

####################
## 그런데 서비스 추적이 시작되지 않으면, 프로파일을 추적하지 않습니다 이때, 자동 서비스 추적을 enable 한다.
#  _trace_auto_service_enabled=true
####################

#_trace_auto_service_backstack_enabled=true

####################
## 메소드가 너무많을 경우에, 아래 hook_method_xxx옵션들을 이용해 필터링할 수 있습니다. 
#  hook_method_access_public_enabled=true
#  hook_method_access_private_enabled=false
#  hook_method_access_protected_enabled=false
#  hook_method_access_none_enabled=false
#  hook_method_ignore_prefixes=get,set
####################

블로그마다도 다 다르고..  ( 톰캣설정하는구간도 catalina.sh 에 -dscouter 옵션에 어떤분은 
tomcat/ conf / scouter.conf 를 넣으시고 어떤분은 agent.java / conf / scouter.conf 를 넣으셔요
아무런 값을 설정하지않아도, default로 들어가는 값들이 너무많아서 헷갈리네요.. 

이러한 옵션들이 다 한곳에 정의되진 않을것같아서 질문드립니다. 
도와주십쇼 .. 감사합니다 .

**Comment by kranian** [comment]
설정 적용 방식이 두가지 다 적용 되어서 그런거에요. 따라서 자기가 편한것을 기준으로 설정하면 됩니다. 

첫번째 Java의 시스템 프로퍼티스에 적용하는 방법 (config apply order : 2) 
-D_trace_auto_service_backstack_enabled=true 

두번째 scouter.conf 설정 파일에다 적용하는 방법 (config apply order : 1)
_trace_auto_service_backstack_enabled=true

만약 저렇게 두개다 적용 되어 있을 경우에는 파일에 설정된 내용이 최종 적용 됩니다. 
따라서 파일에 설정한 내용이 가장 우선 순위 설정 으로 따지면 가장 높습니다.

**Comment by gunlee01** [comment]
non http 추적하기에 나온 설정은 java agent에 해야합니다.
