### ISSUE TITLE
JDBC Connection Leak Trace 관련 문의입니다.

### ISSUE THREAD

**Issue by ParkYoungBae** [scouter-project/scouter#671]
안녕하세요!!

JDBC Connection Leak Trace 관련 문의입니다.

관련 부문 설정으로 Connection Open이후 Close하지 않는 서비스가 있다면 어떻게 확인을 해야하는지 문의드립니다.

**Comment by gunlee01** [comment]
_summary_connection_leak_fullstack_enabled=true 로 설정해보시기 바랍니다.
leak 추정되는 부분이 Alert 및 log에 남게됩니다.
