### ISSUE TITLE
소스 수정하여 배포 문의

### ISSUE THREAD

**Issue by usuall** [scouter-project/scouter#673]
안녕하세요.
문의 드립니다. 

Scouter(Apache 2.0 라이선스)를 업무에 사용하기 위해
일부 부족한 부분을 커스터마이징하여 내부 시스템에 배포시 문제가 없는지요.
예를 들면, 특허소송과 같은 법적 문제가 발생할수 있는지요.

스카우터를 매우 만족해서 사용하고 있고, 
수집되는 정보 중 일부를 log(텍스트) 파일 형태로 저장하여 재사용하려고 합니다. 

감사합니다.

**Comment by gunlee01** [comment]
Apache 2에 준해서 사용하시면 문제되지는 않습니다.

**Comment by usuall** [comment]
답변 감사합니다.
