### ISSUE TITLE
java agent 실행 시 cpu 상승 이슈 문의드립니다.

### ISSUE THREAD

**Issue by yangmyunggil** [scouter-project/scouter#694]
안녕하세요
자바에이젼트 실행시 Java 프로세스 CPU 점유율을 많이 먹고 있는 현상이 있습니다.
2~3시간 뒤면 정상적으로 수준으로 CPU 상태가 돌아옵니다.

해당 스레드 번호 확인하여 스레드덤프 실행해 보았습니다.
내용은 아래와 같으며 pid번호 파일 생성관련 문제가 아닐까 추측됩니다.
/tmp/scouter 하위에 초기 기동시 pid 파일만 생성되며 그이후 갱신되지 않습니다.

------------스레드 덤프 내용-------------------------------------

Thread 23252: (state = IN_JAVA)
java.io.cc.list(java.io.File) @bci=0 (Compiled frame; information may be imprecise)
java.io.File.list() @bci=29, line=1116 (Interpreted frame)
java.io.File.listFiles(java.io.FileFilter) @bci=1, line=1280 (Compiled frame)
org.jboss.as.logging.LoggingResource.findFiles(java.lang.String, org.jboss.dmr.ModelNode) @bci=20, line=217 (Compiled frame)
org.jboss.as.logging.LoggingResource.getChildrenNames(java.lang.String) @bci=42, line=147 (Compiled frame)
org.jboss.as.logging.LoggingResource.hasReadableFile(java.lang.String) @bci=3, line=203 (Compiled frame)
org.jboss.as.logging.LoggingResource.getChild(org.jboss.as.controller.PathElement) @bci=17, line=98 (Compiled frame)
org.jboss.as.controller.OperationContextImpl.getAuthorizationResource(org.jboss.as.controller.PathAddress) @bci=110, line=1405 (Compiled frame)
org.jboss.as.controller.OperationContextImpl.getBasicAuthorizationResponse(org.jboss.as.controller.AbstractOperationContext$OperationId, org.jboss.dmr.ModelNode) @bci=55, line=1362 (Compiled frame)
org.jboss.as.controller.OperationContextImpl.authorize(org.jboss.as.controller.AbstractOperationContext$OperationId, org.jboss.dmr.ModelNode, boolean, java.util.Set) @bci=34, line=1281 (Compiled frame)
org.jboss.as.controller.OperationContextImpl.readResourceFromRoot(org.jboss.as.controller.PathAddress, boolean) @bci=103, line=646 (Compiled frame)
org.jboss.as.controller.OperationContextImpl.readResourceFromRoot(org.jboss.as.controller.PathAddress) @bci=3, line=632 (Compiled frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.addParentResource(org.jboss.as.controller.OperationContext, java.util.List, org.jboss.as.controller.PathAddress) @bci=2, line=786 (Compiled frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.getAllActualResourceAddresses(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode, java.util.List, org.jboss.as.controller.PathAddress, org.jboss.as.controller.PathAddress) @bci=315, line=774 (Compiled frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.getAllActualResourceAddresses(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode, java.util.List, org.jboss.as.controller.PathAddress, org.jboss.as.controller.PathAddress) @bci=354, line=778 (Compiled frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.getLocalResourceAddresses(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode) @bci=52, line=713 (Interpreted frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.initLocalResourceAddresses(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode) @bci=4, line=702 (Interpreted frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext.access$200(org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext, org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode) @bci=3, line=689 (Interpreted frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.doExecuteInternal(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode, org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext) @bci=283, line=204 (Compiled frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.doExecute(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode, org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler$ReadResourceDescriptionAccessControlContext) @bci=11, line=162 (Interpreted frame)
org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.execute(org.jboss.as.controller.OperationContext, org.jboss.dmr.ModelNode) @bci=65, line=155 (Interpreted frame)
org.jboss.as.controller.AbstractOperationContext.executeStep(org.jboss.as.controller.AbstractOperationContext$Step) @bci=33, line=710 (Compiled frame)
org.jboss.as.controller.AbstractOperationContext.doCompleteStep() @bci=171, line=545 (Compiled frame)
org.jboss.as.controller.AbstractOperationContext.completeStepInternal() @bci=1, line=338 (Interpreted frame)
org.jboss.as.controller.AbstractOperationContext.executeOperation() @bci=1, line=314 (Interpreted frame)
org.jboss.as.controller.OperationContextImpl.executeOperation() @bci=20, line=1152 (Interpreted frame)
org.jboss.as.controller.ModelControllerImpl.internalExecute(org.jboss.dmr.ModelNode, org.jboss.as.controller.client.OperationMessageHandler, org.jboss.as.controller.ModelController$OperationTransactionControl, org.jboss.as.controller.client.OperationAttachments, org.jboss.as.controller.OperationStepHandler) @bci=463, line=335 (Interpreted frame)
org.jboss.as.controller.ModelControllerImpl.execute(org.jboss.dmr.ModelNode, org.jboss.as.controller.client.OperationMessageHandler, org.jboss.as.controller.ModelController$OperationTransactionControl, org.jboss.as.controller.client.OperationAttachments) @bci=10, line=191 (Interpreted frame)
org.jboss.as.jmx.model.ResourceAccessControlUtil.getResourceAccess(org.jboss.as.controller.PathAddress, boolean) @bci=59, line=85 (Compiled frame)
org.jboss.as.jmx.model.RootResourceIterator.doIterate(org.jboss.as.controller.registry.Resource, org.jboss.as.controller.PathAddress) @bci=25, line=51 (Compiled frame)
org.jboss.as.jmx.model.RootResourceIterator.doIterate(org.jboss.as.controller.registry.Resource, org.jboss.as.controller.PathAddress) @bci=162, line=61 (Compiled frame)
org.jboss.as.jmx.model.RootResourceIterator.doIterate(org.jboss.as.controller.registry.Resource, org.jboss.as.controller.PathAddress) @bci=162, line=61 (Compiled frame)
org.jboss.as.jmx.model.RootResourceIterator.iterate() @bci=8, line=43 (Interpreted frame)
org.jboss.as.jmx.model.ModelControllerMBeanHelper.queryNames(javax.management.MBeanServer, javax.management.ObjectName, javax.management.QueryExp) @bci=28, line=175 (Interpreted frame)
org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.queryNames(javax.management.ObjectName, javax.management.QueryExp) @bci=52, line=213 (Interpreted frame)
org.jboss.as.jmx.PluggableMBeanServerImpl.queryNames(javax.management.ObjectName, javax.management.QueryExp) @bci=107, line=806 (Interpreted frame)
scouter.agent.counter.task.JBossJMXPerf.getMbeanList() @bci=41, line=181 (Interpreted frame)
scouter.agent.counter.task.JBossJMXPerf.process(scouter.agent.counter.CounterBasket) @bci=81, line=116 (Interpreted frame)
sun.reflect.GeneratedMethodAccessor25.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Interpreted frame)
sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Interpreted frame)
java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=57, line=606 (Interpreted frame)
scouter.agent.counter.CounterExecutingManager$Invocation.process(scouter.agent.counter.CounterBasket) @bci=16, line=164 (Interpreted frame)
scouter.agent.counter.CounterExecutingManager.gatherAndSendCounter(long) @bci=72, line=74 (Interpreted frame)
scouter.agent.counter.CounterExecutingManager.run() @bci=25, line=62 (Interpreted frame)
환경은 아래와 같습니다.
OS : Amazon Linux AMI release 2017.09
WAS : jboss 6.4
JAVA : java1.7

해당 문제 해결을 위해 도움 부탁드리겠습니다.
감사합니다.

**Comment by kranian** [comment]
위 로그 기준으로만 분석 했을시 예상 시나리오 입니다.
Java 에이전트에서 메트릭 카우터 수집이  1초에 한번씩 실행이 됩니다. 해당 시점에 JBossJMXPerf 객체로 MbeanList 수집시  CPU 점유율이 올라 가는것 같습니다. 

관련  로그 근거 순서 
```
1. CounterExecutingManager (1초에 한번씩 수행)
2. Method.invoke (실행)
3. scouter.agent.counter.task.JBossJMXPerf.process 
4.JBossJMXPerf.getMbeanList ( 실행 조건. 5초에 한번씩 100번이하 수집 되었을때 )
```
1차로 java 에이전트 설정에 jmx_counter_enabled = false로 설정 변경 하시고  CPU가 내려가는지  확인
해보세요

**Comment by yangmyunggil** [comment]
kraninan님 답변 감사합니다. ^^
jmx_counter_enabled = false 로 기동하면 정상적으로 잘 기동되네요.
jmx_counter_enabled false로 하여 스카우터 apm 모니터링 항목 중에 확인되지 않는 부분이 있을 것 같은데요.
혹시 어떤 부분 알 수 있을까요?

**Comment by kranian** [comment]
JBOSS로 JMX을  성능 수집을 해본 경험이 없어 잘 모르겠는네요. 다만 유추 할수 있는 확인 작업은 JBOSS EAP 관리자 콘솔에서 JMX 목록을 하시면 될겁니다.

**Comment by yangmyunggil** [comment]
스카우터 클라이언트 perfermance counter 항목들 잘 모니터링 되고 있네요.
스카우터 클라이언트에는 영향 없는것으로 보이네요
답변 정말 감사드립니다

**Comment by kranian** [comment]
네네 도움 돼서 기쁘네요. 그럼  수고 하세요

**Comment by gunlee01** [comment]
특정 환경에서 문제가 발생할 소지가 있어 jmx counter 옵션은 2.8.1 부터 default false로 처리됩니다.
