### ISSUE TITLE
Conn Active - DataSource 수집주기 및 기준에 대한 문의 드립니다.

### ISSUE THREAD

**Issue by seanlee1986** [scouter-project/scouter#695]
JBoss 6.4.20 EAP
Java 1.7.80

환경으로 애플리케이션에 대한 Conn Active - DataSource 모니터링을 걸어둔 상태입니다.
Q) 문의드리고싶은 내용은 해당 값에대한 수집 주기 및 기준입니다.
항목을 육안으로 확인시엔 매 5초마다 값을 갱신하고 있는 것 같은데요. 수집되는 값이 어떤 값인지, 정확한 수집 주기는 어떻게 되는지 (5초 평균값인지) 등등을 알고싶습니다.

그럼 답변 부탁드리겠습니다.
감사합니다.

**Comment by gunlee01** [comment]
jboss가 jmx로 제공하는 값입니다. 정확한 수치의 산정 방법은 사용중인 jboss의 매뉴얼 등을 참고해 보세요.
https://github.com/scouter-project/scouter/blob/master/scouter.agent.java/src/main/java/scouter/agent/counter/task/JBossJMXPerf.java

https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform/6.2/html/administration_and_configuration_guide/datasource_statistics
