### ISSUE TITLE
RequestProc 관련 문의

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#701]
![ajp](https://user-images.githubusercontent.com/14970310/82522499-9b22b780-9b64-11ea-8357-db719771e456.PNG)

agent.java 버전 2.7.1 사용할때는 ajp가 잡혔었는데. 
2.8.1 올리고 나서 ajp가 사라지면서

RequestProc 데이타를 수집할수 없게 되었는데.
해당 기능은 더이상 지원하지 않는건지 궁금합니다.

**Comment by gunlee01** [comment]
기본옵션이 변경되었습니다.
jmx_counter_enabled=true
로 옵션 지정하면 됩니다

**Comment by lu8300test** [comment]
> 기본옵션이 변경되었습니다.
> jmx_counter_enabled=true
> 로 옵션 지정하면 됩니다

감사합니다. 확인하였습니다.
혹시 저런 변화 사항은 어디서 확인할수 있을까요???

**Comment by gunlee01** [comment]
릴리즈 노트를 확인하시면 됩니다.
![image](https://user-images.githubusercontent.com/6788732/83640556-3f860e80-a5e7-11ea-8092-3e89da078b69.png)
