### ISSUE TITLE
database의 날짜별폴더 자동 삭제 기능이 있는지요?

### ISSUE THREAD

**Issue by hohosyk** [scouter-project/scouter#722]
안녕하세요! 스카우터 항상 잘 쓰고있습니다. 
미리 감사드립니다. 

database의 하위 날짜 폴더가 날짜별로 1GB 정도 되다보니, 
날짜별 폴더가 계속 쌓이면 꽤 용량을 많이 차지하더라구요. 
종종 서버 들어가서, 수작업으로 날짜별 폴더들을 삭제를 시켜주고있었는데요

혹시 스카우터에 Config Server 에 날짜별 폴더도 삭제하는 기능이 있나요?

예) 하위같은 날짜별 폴더를 수작업으로 삭제하고있음
~/database:> ll
7▒▒  6 18:28 00000000
7▒▒ 10 00:00 20200705
7▒▒ 11 00:00 20200706
7▒▒ 12 00:00 20200707
7▒▒ 13 00:00 20200708
7▒▒ 14 00:00 20200709
7▒▒ 15 00:00 20200710
7▒▒ 16 00:00 20200711
7▒▒ 17 00:00 20200712
7▒▒ 18 00:00 20200713
7▒▒ 19 00:00 20200714
7▒▒ 20 00:00 20200715
7▒▒ 21 00:00 20200716
7▒▒ 22 00:00 20200717
7▒▒ 23 00:00 20200718
7▒▒ 24 00:00 20200719
7▒▒ 25 00:00 20200720
7▒▒ 26 00:00 20200721
7▒▒ 27 00:00 20200722
7▒▒ 28 00:00 20200723
7▒▒ 24 00:14 20200724
7▒▒ 25 00:14 20200725
7▒▒ 26 00:13 20200726
7▒▒ 27 00:11 20200727
7▒▒ 28 00:14 20200728

**Comment by gunlee01** [comment]
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Configuration.md

Server 설정에서 mgr_purge로 시작하는 옵션들 참고해보세요.
