### ISSUE TITLE
rxJava 를 monitoring 할수 있는 방법이 있을까요??

### ISSUE THREAD

**Issue by ByoungGeol-Cho** [scouter-project/scouter#732]
안녕하세요. scouter 잘 사용중입니다.

관리하는 소스에서 rxJava2로 구현이 되어 있는데 xlog로 보았을 때 트레이스가 제대로 되지 않더라고요.
열심히 구글링해봐도 자료가 없던데 
트레이스 잘 되게 할 수 있는 방법이 있을까요?

**Comment by gunlee01** [comment]
pending close.
Please open any time if you needed.
