### ISSUE TITLE
[S107] queue exceeded!!

### ISSUE THREAD

**Issue by changho-hur** [scouter-project/scouter#733]
scouter.server.core.app.XLogGroupPerf.scala 파일에
S107 메세지 찍는 부분을 봤는데 아무래도 큐가 꽉찰일이 없어서

이것저것 보다가
scouter.util.RequestQueue.java 에 queue 가 LinkedList 로 되어있더라고요.
removeFirst() 메서드 호출할때
modCount++ 를 하게 되어있는데. 이게 무한히 증가하진 않을거 같고. 이것때문에 queue 가 제대로 동작 안하나 싶어서
queue 를 LinkedBlockingQueue 로 바꿔 놓고 removeFirst() 메서드 대신 poll()를 써서 빌드 다시한다음
사용해 보고 있습니다.
검토 부탁드려요.

지금 시스템에서 보통 보름정도면 저 오류가 뜨면서 
scouter-client 에서 Service[Throughput] - (그룹명) 요 항목이 아예 안나오더라고요.

8월 중순 이후로 동일한 현상 발생하는지 한번 지켜봐야겠어요.

**Comment by changho-hur** [comment]
저거 적용한 서버는 한달이 넘었는데. 이상없이 잘 됩니다.

스카우터 서버 두대 쓰고 있는데, 저거 적용 안한 한대가 같은 오류 나더라고요.
그래서 그 한대도 마저 적용 했습니다.

두번째 적용한 서버는 감시대상이 적어서 두달 정도 지켜보면 될거 같네요.

**Comment by gunlee01** [comment]
pending close.
Please open any time if you needed.
