### ISSUE TITLE
PlayFrarmework 지원 문의

### ISSUE THREAD

**Issue by siro012** [scouter-project/scouter#736]
안녕하세요. scouter를 공부하고 있는데 문의가 있습니다.
현재 WAS 를 Playframework 기준으로 개발하여 운영하는 사이트에 적용해보고자 하는데 scouter와 연동가능한 방법이 있는지요?

hook_service_patterns=play.core.j.HttpExecutionContext.execute

를 설정하면 XLOG 등 그래프는 보이긴 하지만 세부 데이터를 볼수가 없어 문의 드립니다.

**Comment by gunlee01** [comment]
play fw은 지원하지 않습니다

**Comment by gunlee01** [comment]
pending close.
Please open any time if you needed.
