### ISSUE TITLE
Windows - Java8 환경에서 Process CPU 수집이 안 되어 질문 드립니다.

### ISSUE THREAD

**Issue by rornfdlek** [scouter-project/scouter#737]
안녕하세요.

2.7.0 버전으로 모니터링을 하는 중
Windows 서버에 올라온 Jdk8의 java process들에서 Process CPU가 집계되지 않는 이슈가 있어 문의 드립니다.

다른 데이터들은 다 잘 보이고 다른 환경들에서는 대부분 다 잘 보이는데
OS: Windows / Process JDK version: 8
특히 위 경우에만 Process CPU 정보가 서버로 전달되지 않습니다..

* OS: Windows / Process JDK version: 7인 경우도 종종 이런 경우가 발생하는데, 빈도는 적은 편입니다.
이슈가 발생하는 OS는 Windows Server 2016 Standard, Windows Server 2012 R2 등입니다.

확인해주시면 감사하겠습니다.
감사합니다.

**Comment by gunlee01** [comment]
pending close.
Please open any time if you needed.
