### ISSUE TITLE
[S188] XLogTagCount queue exceeded!!

### ISSUE THREAD

**Issue by yuna-seo** [scouter-project/scouter#743]
안녕하세요,
금일 queue exceeded!! 에러가 지속적으로 발생하다 oom 발생하였습니다.
지난 issue 참고하여 재기동하여 조치하였는데, 혹시 어떤 부분 때문에 발생하는건지, 어떻게 조치할지 알수있을까요?
해당 시간 cpu가 상당히 높았고, server process kill 하자 급격히 떨어졌습니다.

20200826 10:41:44 [S188] XLogTagCount queue exceeded!!
20200826 10:41:57 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:13 [S188] XLogTagCount queue exceeded!!
20200826 10:42:08 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:19 [S188] XLogTagCount queue exceeded!!
20200826 10:42:17 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:31 [S188] XLogTagCount queue exceeded!!
20200826 10:42:28 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:38 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:48 [S183] FirstTagCountDB queue is exceeded
20200826 10:42:59 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:09 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:15 [S188] XLogTagCount queue exceeded!!
20200826 10:43:19 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:26 [S188] XLogTagCount queue exceeded!!
20200826 10:43:32 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:36 [S123] queue exceeded!!
20200826 10:43:42 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:48 [S188] XLogTagCount queue exceeded!!
20200826 10:43:49 [S183] FirstTagCountDB queue is exceeded
20200826 10:43:59 [S188] XLogTagCount queue exceeded!!
20200826 10:43:59 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:09 [S123] queue exceeded!!
20200826 10:44:09 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:13 [S188] XLogTagCount queue exceeded!!
20200826 10:44:24 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:36 [S123] queue exceeded!!
20200826 10:44:40 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:30 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:46 [S123] queue exceeded!!
20200826 10:44:50 [S183] FirstTagCountDB queue is exceeded
20200826 10:44:56 [S151] java.lang.OutOfMemoryError: Java heap space
20200826 10:45:01 [S183] FirstTagCountDB queue is exceeded

**Comment by yuna-seo** [comment]
추가로 oom jvm dump 옵션을 추가하였으나 덤프 파일이 떨어지지 않았습니다.

**Comment by gunlee01** [comment]
위에 언급된 queue 가 비워지는 경우는 대부분 유입량 대비 디스크 처리 속도가 늦은 경우에 발생합니다.
그런데 OOM 관련 메시지도 있으니 일단 기동시점의 Heap memory를 증가시켜 놓고 좀 더 모니터링 해보시기 바랍니다. 
디스크가 밀려 메모리에 적재되어 OOM이 발생한건지, 아니면 메모리가 부족하여 queue 해소가 빠르게 안되었던건지 선후관계가 명확치는 않은 것 같은데 디스크 IO 지연 문제일 가능성이 더 높을 것 같긴합니다.
