### ISSUE TITLE
JBoss 설정하고자 합니다.

### ISSUE THREAD

**Issue by kmw7117** [scouter-project/scouter#745]
안녕하세요. JBOSS 6.x  사용자 입니다. 
Tomcat 모니터링은 좋은 툴 덕분에 잘되고 있습니다.

이번에는 JBOSS에 Scouter 설치를 해서 APM 모니터링을 진행하려고 합니다.

/bin/sh /opt/jboss-6.1/bin/run.sh

Scouter 설정 부분이 JBoss의 어느 스크립트 인지,  설정 옵션과 함께
알려주시면 감사 하겠습니다.

**Comment by gunlee01** [comment]
pending close.
Please open any time if you needed.
