### ISSUE TITLE
Big Sur 11.0.1 클라이언트 실행 불가

### ISSUE THREAD

**Issue by aeiou8668** [scouter-project/scouter#764]
동일한 환경에서 Big Sur 업데이트 이전에는 잘 사용하고 있었기에 문의드립니다.

macOS Big Sur 11.0.1 버전 업데이트 이후 v2.10.0 최신버전의 클라이언트 실행시 에러가 발생합니다.

에러 메시지 : Failed to create the Java Virtual Machine.

# java -version
wanghyosang@wanghyosang-ui-MacBookPro ~ % java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment Corretto-8.275.01.1 (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM Corretto-8.275.01.1 (build 25.275-b01, mixed mode)

# scouter.client => Contents =>  MacOS => scouter 실행 결과
wanghyosang@wanghyosang-ui-MacBookPro ~ % /Users/wanghyosang/Documents/scouter.client.app/Contents/MacOS/scouter ; exit;
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/lib/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[프로세스 완료됨]

**Comment by applepie1130** [comment]
안녕하세요, Bigsur 업데이트 이후 저도 동일증상을 확인하여 아래와 같이 조치했습니다.

Bigsur로 업데이트를 할 경우 기본적으로 java가 설치됨을 확인 할 수 있었습니다.

$ /usr/libexec/java_home -V

Matching Java Virtual Machines
1.8.271.09 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

아마 Bigsur 시스템에 설정된 java와 scouter에서 바라보는 java버전가의 상이함으로 인한 문제일 것 같아요.

# 조치사항
사전에 설치한 jdk의 경로를 scouter.ini 파일에 명시해주었습니다.

-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin/java

**Comment by chloe-codes1** [comment]
@applepie1130 님 정말 감사합니다! 덕분에 해결 했네요!

**Comment by Jinhyy** [comment]
@applepie1130 감사합니다!!

**Comment by jayyhkwon** [comment]
안녕하세요. Bigsur 11.1 사용자 입니다.

같은 현상 발생 하였지만, 위 해결 방법으로 안되어 다르게 해결하였습니다.

내가 설치한 java path와 scouter가 바라보는 java path의 차이로 발생하는 문제 같습니다.

scouter가 바라보는 java path를 확인하기 위해 scouter를 직접 실행해보면 경로를 확인하실 수 있습니다.

```
./scouter.client.app/Contents/MacOS/scouter

JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
```

저같은 경우 libserver.dylib 파일이 다른 경로에 위치하여 심볼릭 링크 생성하여 해결하였습니다.

sudo ln -s /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/server/libjvm.dylib  /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/libserver.dylib

**Comment by devDayul** [comment]
안녕하세요. 저도 Bigsur 업데이트 이후 해당 증상이 나타나
scouter.client -> 패키지 내용 보기 -> Contents -> Info.plist 파일에서
```
<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/bin/java</string>
```
추가 해주니 해결되었습니다.


Info.plist 파일을 보니 이미 가이드가 있었습니다.
```
<!-- to use a specific Java version (instead of the platform's default) uncomment one of the following options,
        or add a VM found via $/usr/libexec/java_home -V
    <string>-vm</string><string>/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Commands/java</string>
    <string>-vm</string><string>/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/bin/java</string>
-->
```

**Comment by gunlee01** [comment]
Scouter will support Big Sur on the version 2.15.0
