### ISSUE TITLE
Macos Big Sur에서  scouter client 오류 

### ISSUE THREAD

**Issue by dsChoi** [scouter-project/scouter#766]
오전 까지 잘 쓰고 있었으나 오전에 Big sur 11.0.1 로 업데이트 이후 오류가 발생하고 있어 문의드립니다. 

macOS Big Sur 11.0.1 버전 업데이트 이후 v2.10.0 최신버전의 클라이언트 실행시 아래와 같은 문제가 발생합니다. 

아래 분이 써주신 부분과 비슷한것 같지만 조금 다른 오류라서 새 이슈로 등록합니다. 

저는 client 실행은 되나 아래 화면처럼 각 창의 타이틀이 생성이 안되는 현상이 있습니다. 

## java version 
```
~ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```

## 오류 1
**처음 화면 켰을때 문제점**
![image](https://user-images.githubusercontent.com/4524328/100201753-c2a77200-2f43-11eb-87c3-583f17cc3a42.png)

## 오류 2
기본 창 외에 xlog 를 보면 하얀 화면만 나오며 반응이 없습니다. 
**xlog 점 클릭하는 경우**
![image](https://user-images.githubusercontent.com/4524328/100201976-0b5f2b00-2f44-11eb-8b87-9e71bc029020.png)

## 오류 3 
신규 로 gc count/ gc time 등 기존에 존재하지 않은 다른 지표들을 추가할 경우 추가가 되지 않습니다. 

----

한번 위와 같은 하얀 화면이 나오면.. reset perspective 후 scouter clinet 를 종료후 다시 보고 있습니다.

**Comment by gunlee01** [comment]
빅서에서 발생하는 이슈입니다.

**Comment by microflower** [comment]
위의 현상. 패치 예정일까요?

**Comment by gunlee01** [comment]
패치 진행 예정이지만 리소스 문제로 단기간내 진행은 어려울듯 합니다. 불편하시겠지만 빅서 사용중이라면 패치전까지는 가상머신을 통해 리눅스 버전 사용등을 권고 드립니다.

**Comment by gunlee01** [comment]
Scouter will support Big Sur on the version 2.15.0
