### ISSUE TITLE
@Scheduled 로 실행되는 서비스 메서드를 추적

### ISSUE THREAD

**Issue by horious** [scouter-project/scouter#767]
spring 에서 
@Scheduled 로 실행되는 서비스 메서드를 추적할 수 있는 방법이 있을까요.
동일 컨테이너에서 http 호출도 일어나고 있으면 일정시간마다 배치를 돌리는 곳에서 사용됩니다.

hook_service_patterns 을 config 파일에 추가하면 되는건가요?
조언 부탁 드립니다.

**Comment by bill23-kim** [comment]
@Scheduled 가 abc.cde.MyClass.execute 메소드에 달려있다면

hook_service_patterns=abc.cde.MyClass.execute 를 config 파일에 추가하시면 됩니다.

**Comment by horious** [comment]
@bill23-kim 
hook_service_patterns 패턴 표현식에 내부에 있는 static class 의 매서드를 추적하려면 어떻게 써야 할까요?

**Comment by horious** [comment]
> @scheduled 가 abc.cde.MyClass.execute 메소드에 달려있다면
> 
> hook_service_patterns=abc.cde.MyClass.execute 를 config 파일에 추가하시면 됩니다.

**Comment by bill23-kim** [comment]
@horious 
inner static class 경우 hook_service_patterns=abc.cde.MyClass$InnerClass.execute 로 하면 될것 같아요. 그게 잘 안되시면 hook_service_patterns=abc.cde.*InnerClass.execute 이렇게 러프하게 잡을수도 있습니다.

**Comment by horious** [comment]
@bill23-kim 
감사합니다. 잘 동작하는 것 확인했습니다.
