### ISSUE TITLE
Java agent로 어플리케이션 인한 장애, 성능 이슈 가능성

### ISSUE THREAD

**Issue by ifo1999** [scouter-project/scouter#769]
안녕하세요 좋은 소프트웨어 오픈소스로 공개해주심 감사드립니다
스카우터를 사내 시스템에 도입 검토중인데 장애나 문제 가능성을 사전에 점검하려 합니다
스카우터 Java agent가 역으로 어플리케이션에 영향을 주는 케이스가 알려진 것이 있는지요? 예를 들면 어플리케이션 장애나 속도문제 같은 것들이 있는지 궁금합니다
참고로 jdk6, jeus6 시스템과 jdk8, tomcat8에 적용 계획중입니다

**Comment by gunlee01** [comment]
pending close
