### ISSUE TITLE
xlog list 가 보여지지 않는 현상

### ISSUE THREAD

**Issue by cdkim1226** [scouter-project/scouter#772]
매번 하는 로그 트래킹 중 갑자기 Xlog List가 보여지지 않네요;
콘솔에 따로 뜨는 내용은 없구요
우측 상단에 복사하는 버튼을 누르면 복사는 되네요
보여지지만 않습니다.
![image](https://user-images.githubusercontent.com/66354217/103141093-a65d4780-4732-11eb-920c-6cc4d10f8649.png)

**Comment by gunlee01** [comment]
클라이언트 버전이 서버와 맞지 않는 경우 그럴수 있을 것 같습니다.
혹은 빅서에서 발생된 환경이라면 빅서에서 해당 컴포넌트를 지원하지 않아서 발생하는 현상일 수도 있습니다.
(빅서는 아직 지원하지 않습니다.)

**Comment by gunlee01** [comment]
Scouter will support Big Sur on the version 2.15.0
