### ISSUE TITLE
특정기간 TPS 를 csv 파일로 저장하는 방법

### ISSUE THREAD

**Issue by u4rang** [scouter-project/scouter#774]
특정기간의 TPS에 대해 csv 파일로 저장할 수 있는지 문의드립니다.

**Comment by passionlim** [comment]
https://github.com/scouter-project/scouter/blob/master/scouter.document/tech/Web-API-Guide_kr.md
API 를 이용해 별도로 프로그램을 작성해야 하지 않을까 싶습니다.
