### ISSUE TITLE
Active Service  EQ 큐가 빠지지 않는 현상

### ISSUE THREAD

**Issue by kmw7117** [scouter-project/scouter#775]
안녕하세요. 스카우터 사용자 입니다.
실시간 큐상태를 보고 판단하는 지표 중 하나가 Active Service EQ 라고 
생각되는데..
이상하게, 한번 정체되어 빨갛게 쌓이고 나면...재기동 하기 전까지는
원래 상태로 회복되지 않아 서비스 이상 유무 판단이 힘들어 집니다.

현재 정상인데도 여전히 이상이 있는 것처럼 Active Service EQ에 빨갛게 쌓여있는데 있는데
저만 그런 것인지 문의 드립니다.

**Comment by gunlee01** [comment]
어떤 환경에서 사용중인가요?(java version과 사용하는 f/w 및 기술, scouter agent 및 서버 버전 등)
빠지지 않는 서비스가 보인다면 먼저 Thread dump로 한번 확인해보시기 바랍니다.
