### ISSUE TITLE
scouter 프로파일러의 서비스 URL 관련하여 질문 드립니다

### ISSUE THREAD

**Issue by rornfdlek** [scouter-project/scouter#776]
안녕하세요, 
프로파일러에서 수집되는 SERVICE 항목 관련하여 질문 드립니다.
현재 화면에서 확인해본 바로는 .do, .jsp 형식의 URL만 SERVICE로 수집이 되는 것으로 보이는데, 
다른 형태의 URL(ex. .html)은 수집이 불가능한가요?
혹시 수집할 수 있는 방법이 있다면 어느 부분을 보고 수정하면 될 지 알려주시면 감사하겠습니다ㅜㅜ
감사합니다!

**Comment by gunlee01** [comment]
agent에서 mgr_static_content_extensions 옵션을 조정해보세요.
