### ISSUE TITLE
JDK11 사용 시 RequestProc 관련 문의

### ISSUE THREAD

**Issue by HyunGyu-Lee** [scouter-project/scouter#778]
> JDK : adoptopenjdk11
> 버전 : 2.12.0.SNAPSHOT

안녕하세요 스카우터 잘 사용하고 있습니다. (_ _)

기존에 스카우터 `Objects` 항목에 보여지는 톰캣 오브젝트 하위에 http, jdbc 등 추가 항목이 잡혔었는데요.
버전업 영향인지, 위 항목들이 잡히지 않습니다.

관련해서 이슈 찾아보니 [비슷한 이슈](https://github.com/scouter-project/scouter/issues/701)가 있는거같던데 
agent.java에 `jmx_counter_enabled`를 true로 지정해도 여전히 노출되지 않고 있습니다.

클라이언트에서 `Collector` 메뉴에 Linux, Tomcat만 잡히고 RequestProc는 잡히지 않는거로 보아 collector server 설정 문제인 것 같기도 합니다.

JDK8 버전 사용 시엔 문제가 없는데 확인되었습니다

어느 부분을 추가로 확인해봐야할까요?

**Comment by gunlee01** [comment]
Scouter 버전만 올라갔다면 `jmx_counter_enabled`를 true로 지정하면 됩니다.
default 옵션 처리외에 변경된 부분은 없습니다. 
다만 Tomcat 버전이 올라가면서 jmx의 항목(항목의 이름 혹은 구조)이 변경되어서 그럴 것 같습니다. 
현재 해당 부분은 Tomcat 버전업에 대해서 추가적으로 지원할 계획은 없습니다. 

해당 부분의 값들에 대해 모니터링이 필요하다면 Scouter에서 제공하는 기능중 JMX Mbean 모니터링 확장 기능으로 사용하시기 바랍니다.
https://github.com/scouter-project/scouter/blob/5a5fef9ebf4fbf463d7a49eeaa864abe6ec6d28e/scouter.document/main/Custom-MBean-Counter.md

**Comment by HyunGyu-Lee** [comment]
저희 프로젝트 부트 버전업과 관련된 이슈였네요. 
답변 감사합니다.

Spring Boot 2.2.0 이상을 쓰시는 분들중 비슷한 이슈를 경험하실수도 있을 것 같아 아래 해결되었던 방법 남깁니다.

Spring Boot 2.2.0 버전 부터는 최적화 및 내장톰캣 성능과 관련하여 JMX 설정이 아래와 같이 바뀌었습니다.
![image](https://user-images.githubusercontent.com/19619055/107339905-8aeea600-6b00-11eb-807a-decf31a6ba45.png)
![image](https://user-images.githubusercontent.com/19619055/107340107-b6719080-6b00-11eb-9d05-e7ef7ec142e4.png)

프로젝트 설정파일에 아래 옵션으로 JMX 관련 기능 활성화 해주니 정상적으로 동작했습니다~

```
spring.jmx.enabled=true
server.tomcat.mbeanregistry.enabled=true
```
