### ISSUE TITLE
HttpURLConnection getResponseCode() 404시 xlog error표시 문의

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#779]
HttpURLConnection getResponseCode()를 사용하여 이미지 url검증을 사용하고 있습니다.
404리턴이 되는경우 xlog상에 error로 표시되고 있는데 해당 현상을 막을수 있는 방법이 있는지 문의 드립니다.

**Comment by bill23-kim** [comment]
scouter.conf 파일이나 -D 옵션에
~~~
xlog_error_on_apicall_exception_enabled=false
~~~
를 추가해 보시기 바랍니다. API CALL 에러 발생시 XLOG 에러로 처리할 것인지에 대한 설정입니다.

**Comment by lu8300test** [comment]
> scouter.conf 파일이나 -D 옵션에
> 
> ```
> xlog_error_on_apicall_exception_enabled=false
> ```
> 
> 를 추가해 보시기 바랍니다. API CALL 에러 발생시 XLOG 에러로 처리할 것인지에 대한 설정입니다.

말씀하신 부분 적용하니 오류로 캐치되지 않습니다. 
한가지 더 궁금한점은 위 옵션을 적용하게 되면 다른API CALL에서 정상적으로 발생되는 오류도 다 잡히지 않게 되는건지 궁금합니다.

**Comment by bill23-kim** [comment]
네 맞습니다. 정상적인 에러와 비즈니스적인 에러를 에이전트가 판단하지 못하기 때문에 API CALL 에서 발생하는 에러를 전부 트랜잭션 에러로 보거나/보지않거나 입니다.

**Comment by lu8300test** [comment]
> 정상적인 에러와 비즈니스적인 에러를 에이전트가 판단하지 못하기 때문에 API CALL 에서 발생하는 에러를 전부 트랜잭션 에러로 보거나/보지않거나 입니다.

넵. 확인 감사합니다!
