### ISSUE TITLE
SQL문을 확인하고 싶습니다.

### ISSUE THREAD

**Issue by boojongmin** [scouter-project/scouter#781]
안녕하세요 스카우터와 페이퍼를 설치했습니다.

![image](https://user-images.githubusercontent.com/9567723/108332032-b6654500-7212-11eb-8aad-c156e8d02601.png)

위미지와 같이 SQL에 PRE > memberdb 만 찍히는 이슈가 있어서 문의 드립니다.

제가 설정을 건들어서 그런가 싶어서
에이전트의 scouter.conf를 아래와 같이
```
obj_name=helloworld
net_collector_ip=0.0.0.0
net_collector_udp_port=6100
net_collector_tcp_port=6100
```

최소화했는데도 증상은 동일합니다.

콜렉터쪽은 딱히 설정을 건드린게 없어서
제가 paper 쪽의 view를 잘못 건드린건가해서 localstorage 초기화했는데 증상은 같고

이래저래 진행하다 잘 안풀려서 질문을 드립니다. 

감사합니다.

추가로 

원래 하려던 작업은
NullPointerException이 나올때 스택트레이스를 찍고 싶은데
(에러 핸들러가 있어서 정상 응답이나 404를 주는 케이스)

```
profile_fullstack_hooked_exception_enabled=true
hook_exception_class_patterns=java.lang.Exception
```

위의 설정을 걸어도 보이지 않는 것 같은데요.
혹시 제가 설정을 추가해야하는지도 궁금합니다. 

감사합니다 :)

**Comment by gunlee01** [comment]
쿼리는 그런 경우를 본 적이 없어 잘 모르겠네요.
PreparedStatement 등에 넘어가는 파라미터에서 구해오는 방식인데 driver 버전이 변경되면 구조가 완전히 변경되는 경우도 있어 재현되는 소스에서 디버깅을 해봐야 자세한 상황을 알 수 있을 것 같습니다.

Exception은 상속을 탐색해서 BCI를 동작시키는게 아니라서 java.lang.NullPointerException 이라고 적어야 할 것 같고
`hook_`로 시작하는 옵션은 재기동이 필요한 옵션입니다. 이 부분도 참고하세요.

**Comment by kkojaeh** [comment]
저도 동일한 문제를 확인하여 분석 해봤습니다.
제 경우에는 mysql 8 connector 를 사용하고 있고 아래와 같은 상황으로 발생됩니다.

com.mysql.cj.jdbc.ServerPreparedStatement
com.mysql.cj.jdbc.ClientPreparedStatement

두개의 클래스중 com.mysql.cj.jdbc.ServerPreparedStatement 를 사용하게 되어 발생되는 문제 입니다.

ServerPreparedStatement 는 ClientPreparedStatement 를 상속있습니다.

아래의 생성자로 인해 super(ClientPreparedStatement) 생성자를 호출하게 됩니다.

`
protected ServerPreparedStatement(JdbcConnection conn, String sql, String db, int resultSetType, int resultSetConcurrency) throws SQLException {
        super(conn, db);
...
`

이로 인해 SQL 이 없는 아래의 생성자가 실행 되게 됩니다.

`
protected ClientPreparedStatement(JdbcConnection conn, String db) throws SQLException {
        super(conn, db);
...
`

현재 생성자 2번째 인자를 SQL 로 판단하여 표시하기 때문에 SQL 대신 DB명이 SQL 로 표시되는 문제가 발생되고 있습니다.

제 상황에서는 hikariCP 의 useServerPrepStmts 옵션을 true 로 사용하고 있어 발생 되었고 이를 false(기본값) 로 임시 변경하여 사용중입니다.

**Comment by boraecosystem-dev** [comment]
@gunlee01 
아~ 감사합니다. 예외 클래스는 명시적으로 작성하겠습니다 ^^

@kaifeng-h 
감사합니다. 확인해보니 저도 8버전을 쓰네요 ㅎㅎ
![image](https://user-images.githubusercontent.com/36653198/109354253-df47a300-78c0-11eb-89a0-ed85f3730a4f.png)

**Comment by boojongmin** [comment]
@kaifeng-h 

새로 오픈하는게 있어서 바빠서 미루고 있던 쿼리 확인하는 작업을 적용했습니다.
처음에는 단순하게 mysql connector를 6버전으로 내려봤는데 동일한 증상이여서 확인해보니

말씀해주신 useServerPrepStmts 이 옵션을 살펴봤습니다.
프로젝트에서는 말씀하신 옵션이 적용된 것을 확인했습니다.

false로 바꾸고 원하는대로 쿼리가 나오는 것을 확인했습니다.

감사합니다 :)
