### ISSUE TITLE
제니퍼 처럼 프로세스 킬 시키는 메뉴가 있나요?

### ISSUE THREAD

**Issue by pulmuone** [scouter-project/scouter#782]
제니퍼에서 scouter로 변경 작업을 하고 설치와 설정은 마무리 했습니다. 
자바 트러블슈팅(scouter)책과 구글 검색으로 하긴 했는데 

제니퍼에서는 오래 처리 되는 프로세스를 kill시키는 메뉴가 있는데 scouter에도 이러한 기능이 있는지 궁금합니다. 
scouter클라이언트 이것저것 사용해 보고 있는데 아직 발견을 못했습니다.

**Comment by gunlee01** [comment]
프로세스 kill 기능은 없습니다
