### ISSUE TITLE
summary interval 설정

### ISSUE THREAD

**Issue by raintime3** [scouter-project/scouter#784]
안녕하세요? 

현재 web api를 이용하여 summary 에서 통계값을 얻어오고 있습니다.
summary 기본 단위가 현재 5분으로 알고 있는데  
1분 단위도 선택할 수 있게 구현 가능할까요?

**Comment by gunlee01** [comment]
scouter 내부적으로 1분단위의 summary는 수집하지 않고 있습니다. 
실시간, 5분 두가지만 제공하고 있습니다.

**Comment by raintime3** [comment]
> scouter 내부적으로 1분단위의 summary는 수집하지 않고 있습니다.
> 실시간, 5분 두가지만 제공하고 있습니다.

답변 감사합니다. 
1분단위로 소스 수정하려면 많은 부분을 건드려야 할까요?
