### ISSUE TITLE
req_search_xlog_max_count 옵션 적용 질문

### ISSUE THREAD

**Issue by abcdsds** [scouter-project/scouter#785]
안녕하세요
콜렉터 서버 옵션에 req_search_xlog_max_count를 추가해줬는데 생각하는대로 작동을 안하는것 같습니다.
api 조회시 500개만 나와서 저 옵션으로 갯수를 늘려볼려고 1000으로 설정했는데 그대로 500이 나오네요
req_search_xlog_max_count 옵션이 제가 생각한 옵션이 아닌건지 궁금해서 여쭤봅니다.

**Comment by gunlee01** [comment]
해당 옵션은 클라이언트에서 xlog 검색시에 적용되는 수치입니다.
![Uploading image.png…]()
