### ISSUE TITLE
method profiling 관련

### ISSUE THREAD

**Issue by M4nare** [scouter-project/scouter#788]
method 수준의 profiling 을 사용하면서 궁금한 점이 있어 문의 드립니다.

우선 대상의 앱은 demo에 있는 jpetstore가 아닌, 현재 git에 올라와 있는 최신 버전의 JpetStore를 사용했습니다.
https://github.com/mybatis/jpetstore-6

작업에 대한 tracing 정보를 얻고 싶은데, method 수준에서 profiling 을 하여 얻으면 일부 method가 누락 되는 것 같습니다.
예를 들면 OrderAction이라는 class에 있는 특정 method에서 OrderService의 method를 호출하는데 이 OrderService에서 수행되는 method가 누락이 됩니다.

추측으로는 profiling의 깊이가 깊지 않아서 발생하는 문제로 보이는데, 사용자가 이 깊이를 조절할 수 있는지 궁금합니다.

**Comment by gunlee01** [comment]
private 메소드인가요? accessor에 따라 옵션을 설정할 수 있습니다.
 
![Uploading image.png…]()
