### ISSUE TITLE
Alpine Linux Error 관련

### ISSUE THREAD

**Issue by h2m8n** [scouter-project/scouter#789]
안녕하세요 Scouter를 잘 활용하고 있는데,

Alpine Linux 에서 Host Agent를 실행 시 
아래와 같은 에러가 발생합니다.

혹시 확인이 가능한 부분이 있으시면 도움을 얻고자 올립니다.

<img width="657" alt="스크린샷 2021-03-23 09 33 43" src="https://user-images.githubusercontent.com/48459881/112075076-19078300-8bbb-11eb-88a1-bda76b5e3938.png">

**Comment by gunlee01** [comment]
알파인 리눅스는 지원되지 않습니다.
호스트 메트릭 모니터링 통합이 필요하면 Telegraf 연동을 사용해주셔야 합니다.
