### ISSUE TITLE
[S159] invalid data

### ISSUE THREAD

**Issue by dannySuh** [scouter-project/scouter#791]
scouter version : 2.10.0
WAS : tomcat 8

Collector 서버와 agent 쪽을 분리 시켰습니다.

기본 포트(6100)로  tcp/udp 방화벽도 오픈하여 정상 접속 되는 부분 확인 하였습니다.

Collector 서버가 remote에 있는 경우 데이터 수신 시 아래와 같은 오류가 발생하고 있습니다.

20210412 09:51:32 [S159] invalid data
java.io.EOFException
        java.io.DataInputStream.readInt(DataInputStream.java:392)
        scouter.io.DataInputX.readInt(DataInputX.java:320)
        scouter.server.netio.data.NetDataProcessor$.process(NetDataProcessor.scala:74)
        scouter.server.netio.data.NetDataProcessor$$anonfun$1$$anonfun$apply$1.apply$mcV$sp(NetDataProcessor.scala:46)
        scouter.server.util.ThreadScala$$anon$1.run(ThreadScala.scala:12)

테스트 겸 Collector 서버와 agent 쪽이 같은 서버에 있는 경우는 수집된 데이터가 정상적으로 표시 되고 있습니다.

**Comment by gunlee01** [comment]
agent 버전이 server 버전과 동일한지 한번 체크해보세요.
