### ISSUE TITLE
LivenessProbe, ReadinessPrboe 적용시 에러로그 발생 ([Z101] check propergation: null)

### ISSUE THREAD

**Issue by sbooms** [scouter-project/scouter#795]
Kubernetes의 LivenessProbe, ReadinessPrboe를 적용하면 
 (Springboot에서 actuator를 추가해서 httpGet으로 적용했습니다)

scouter.agent.java/src/main/java/scouter/xtra/http/HttpTrace.java 에서 parentSpanId를 못가져오면서 다음과 같은 log를 print 합니다
 - [Z101] check propergation: null

**Comment by gunlee01** [comment]
에러 메시지가 null로 나와서 바로 원인 파악이 어려운 것 같습니다.
trace_interservice_enabled=false로 사용하면 에러 메시지가 나오지는 않을 것 같습니다.

**Comment by sbooms** [comment]
다음 환경설정으로 일단 ignore 처리 했습니다.
mgr_log_ignore_ids=Z101

**Comment by sbooms** [comment]
네 Kubernetes 에서 livenessProbe 체크하는 API 호출될때 발생하고있네요
