### ISSUE TITLE
Weird GUI behaviour in OSX

### ISSUE THREAD

**Issue by alqa-dash** [scouter-project/scouter#797]
In macOS (Big Sur in my case) Scouter doesn't properly show tabs and its content, hides them, etc. Therefor I have to run virtual machine with windows to run Scrouter client but in windows I cannot save xlog profile because of folder naming rules (many different brackets which windows does not support). I tried to change java but it does not help.

Below you can find screen with Scouter on os x.

![image](https://user-images.githubusercontent.com/26222875/118450189-97d0f600-b6fc-11eb-9e65-548e4f3d5ada.jpeg)

**Comment by gunlee01** [comment]
Big Sur is not supported yet.

**Comment by alqa-dash** [comment]
I found partial solution somewhere in Eclipse forums. Suppose can be useful.

[https://www.genuitec.com/forums/topic/fix-myeclipse-on-big-sur/](url)

**Comment by gunlee01** [comment]
Scouter will support Big Sur on the version 2.15.0
