### ISSUE TITLE
trace_interservice_enabled를 활성화 하면 기존에 세팅된 B3Constant 값이 강제로 변경됨

### ISSUE THREAD

**Issue by sbooms** [scouter-project/scouter#799]
저희 프로젝트 에서는 Istio를 이용한 Service Mesh 환경을 구축한 상황입니다.
하여 이미 envoy proxy에서 Trace 관련된 헤더를 만들어서 jaeger를 통해 Tracing을 하고 있습니다.
 (x-request-id, x-b3-parentspanid, x-b3-sampled=1, x-b3-traceid, x-b3-spanid 등)

헌데 Scouter 의 xlog를 사용하기 위해 trace_interservice_enabled=true 값을 넣으면 scouter에서 강제로 B3Constant 관련 헤더값을 변경하고 있습니다.
 (x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-span-name, x-b3-sampled 등)

하여 jaeger에서 정상적인 추적이 불가능한 상황입니다.

trace_interservice_enabled 을 사용하더라도, 기 세팅된 trace관련 헤더를 그대로 이용할 수 있는 방법이 있을까요?

**Comment by gunlee01** [comment]
둘다 동시에 성립되지는 않습니다.
서비스간 연계 모니터링은 jaeger를 사용하시고, trace_interservice_enabled=false로 사용하여야 합니다.

**Comment by gunlee01** [comment]
다음 릴리즈 버전에서 
trace_propagete_b3_header 옵션으로 조정 가능해집니다.
