### ISSUE TITLE
Customizable Alert 으로 Error Rate Script 작성시 에러

### ISSUE THREAD

**Issue by shin25641** [scouter-project/scouter#803]
안녕하세요

WAS에서 Exception 관련 에러가 있을 경우

 alert 을 생성해주려고 합니다.

현재 클라이언트 프로그램에서 

Customizable Alert 선택하여 Error Rate Script 작성 후 저장을 했을 경우

save failed
server problem or alert editing unsupported version
alert script editor in client ui supported
@since : v1.8.0

이와같이 에러창이 뜨면서 저장이 되지 않습니다.

클라이언트 버전은 현재 2.12.0.1.SNAPSHOT 사용중입니다.

현재 버전에선 지원하지 않는건가요?..  아님 plugin을 사용해야만 하는건가요

확인부탁드립니다 ㅠ

**Comment by gunlee01** [comment]
수집 서버의 버전이 1.8이상이면 적용이 되어야 합니다.
서버에 들어가서 직접 에디팅해서 적용되는지 확인해보시기 바랍니다. 

수집서버 plugin 디렉토리에 {metric이름}.alert {metric이름}.conf 두가지 파일이 생성이 되어야 합니다. 
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Alert-Plugin-Guide_kr.md

**Comment by gunlee01** [comment]
pending close
