### ISSUE TITLE
agent 2.10.2 기동 시 이슈

### ISSUE THREAD

**Issue by Jusstine** [scouter-project/scouter#805]
안녕하세요~!

2.7.0을 사용하다가 최근 2.10.2로 server 및 agent를 업데이트 하였습니다~!

사용하고 있는 was는 tomcat에서 Connector를 두개를 사용하고 있습니다. (8080, 8443)
기존에 2.7.0 버전에서는 agent를 물려서 was를 기동하게 되면 tomcat하위에 http-nio-8090, http-nio-8443이 표시되었는데요

2.10.2로 버전으로 was를 기동하게되면 tomcat하위에 나타나던 두개의 커넥터 정보가 보이지가 않습니다.
혹시 다른 설정이 필요한가요??

바쁘시겠지만 답변부탁드리겠습니다.

**Comment by gunlee01** [comment]
https://github.com/scouter-project/scouter/blob/044029274ec2ffd4ffd9d0e8815be9c1cef0a77d/scouter.agent.java/src/main/java/scouter/agent/Configure.java#L119

`jmx_counter_enabled` 를 true로 설정해보세요. 기본 설정값이 변경되었습니다.
