### ISSUE TITLE
host.bat 실행시 오류가 발생되는데..

### ISSUE THREAD

**Issue by Macky3456** [scouter-project/scouter#806]
버전은 2.8.1사용 중이구요.
윈도우에서 실행 중입니다.
host.bat실행하면 아래와 같은 메시지가 나오는데..
문제가 있을까요??
C:\scouter-all-2.8.1\scouter\agent.host>host.bat

C:\scouter-all-2.8.1\scouter\agent.host>java -classpath ./scouter.host.jar   scouter.boot.Boot ./lib
  ____                  _
 / ___|  ___ ___  _   _| |_ ___ _ __
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |
 |____/ \___\___/ \__,_|\__\___|_|
 Open Source S/W Performance Monitoring
 Scouter version 2.8.1

Configure -Dscouter.config=.\conf\scouter.conf
Scouter Host Agent Version 2.8.1 2020-05-14 23:36 GMT
System JRE version : 1.8.0_281
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000010014ed4, pid=9996, tid=0x000000000000480c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [sigar-amd64-winnt.dll+0x14ed4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\scouter-all-2.8.1\scouter\agent.host\hs_err_pid9996.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

C:\scouter-all-2.8.1\scouter\agent.host>

20210718 13:51:21 Version 2.8.1 2020-05-14 23:36 GMT
20210718 13:51:21 [A113] Counter Collector Started (#5)
20210718 13:51:21 [A10] host agent boot seed=x16eqrv8lhl
20210718 13:51:21 [A01] Scouter Host Agent Version 2.8.1 2020-05-14 23:36 GMT
20210718 13:51:22 [A119] Agent UDP local.port=0

딱 이렇게 나오고 실행이 안되는데... 어디가 문제 인가요?

**Comment by jeonwoosung** [comment]
C:\scouter-all-2.8.1\scouter\agent.host\hs_err_pid9996.log 첨부 해 주시면 좋을 거 같아요. 
sigar-amd64-winnt.dll랑 문제일거 같은데, 혹시 보안 솔루션 설치 돼 있나요? 
Administrator계정으로 관리자모드로 기동하셨죠?

**Comment by gunlee01** [comment]
pending close

**Comment by hoho-yoon** [comment]
What is the solution? Plz~
