### ISSUE TITLE
Tomcat+wrapper 서비스에 scouter 추가방법

### ISSUE THREAD

**Issue by Macky3456** [scouter-project/scouter#807]
안녕하세요, 스카우터 사용자 입니다.

wrapper서비스가 추가된 톰캣 인데.

어디에 스카우터 옵션을 추가해서 기동을 해야되는지 

알수 있을까요? 

감사합니다.

**Comment by jeonwoosung** [comment]
어떤 wrapper가 추가됐는지 명시하면, 좀 파악이 용이할거 같은데, 
wrapper가 tomcat을 같은 VM에서 기동 한다면, wrapper기동 시 scouter를 추가해야 할 것 같구요,
wrapper가 별도로 tomcat JVM을 기동한다면(Wrapper와, tomcat의 JVM PID가 다른 경우) wrapper가 tomcat을 띄울 때 스카우터 옵션을 주심 될거 같아요.

**Comment by gunlee01** [comment]
pending close
