### ISSUE TITLE
Rest API로 1분단위 데이터 조회시 집계치가 예상한 결과와 다르게 나옵니다.

### ISSUE THREAD

**Issue by nubang7** [scouter-project/scouter#808]
안녕하세요, Scouter 잘 사용하고 있는데요,

Rest API로 1분 단위 데이터를 조회시에 Scouter 결과 해석이 잘 안되서 문의드립니다.
아래와 같이 시간대를 다르게 주어도 결과값이 같게 나오는 현상이 있어서 문의드립니다.

2021/08/02 23:54 ~ 2021/08/02 23:55
![image](https://user-images.githubusercontent.com/42139382/128102806-ae7ae377-736e-47bc-817e-1264a5c77cdf.png)

2021/08/02 23:55 ~ 2021/08/02 23:56
![image](https://user-images.githubusercontent.com/42139382/128102717-b9ca8427-0ac3-45d6-8954-cbf30fa90416.png)

**Comment by gunlee01** [comment]
summary data는 5분 단위 집계 데이터입니다.

**Comment by nubang7** [comment]
> summary data는 5분 단위 집계 데이터입니다.
감사합니다, 확인하였습니다.
