### ISSUE TITLE
scouter 에서 node.js 지원하나요? Does Scouter support node.js applications if so where i can download the agent?

### ISSUE THREAD

**Issue by postktb** [scouter-project/scouter#810]
안녕하세요.

scouter 에서 node.js 지원하는지 문의 드립니다.
2016년에는 지원 안한다고 했는데 지금도 지원 안하는지 궁금합니다.
지원하면 설치 매뉴얼 다운 받는 곳도 확인 부탁 드립니다.

감사합니다.

Does Scouter support node.js applications if so where i can download the agent?

Hi team,

We would like to know whether scouter supports profiling node.js applications. If so can you please guide us where i can download and configure the agent for our apps

Thanks
postktb

**Comment by gunlee01** [comment]
nodejs는 지원하지 않습니다
