### ISSUE TITLE
스카우터 Agent를 컨테이너에 적용시 CPU조회가 안되는데 혹시 되는게 맞을까요?

### ISSUE THREAD

**Issue by kubetm** [scouter-project/scouter#811]
현재 컨테이너로 기동되는 was에서 스카우터 agent를 넣어서 모니터링 하고 있습니다.
왠만한 기능들을 잘 작동하는데  cpu 는 조회가 안되고 있어서 질문드려요.
아직 지원이 안되는 부분인지? 아니면 cpu 모니터링이 되는게 맞는데 저의 설정이 부족한 문제인지?
시간 되실때 답변 부탁드립니다^^

**Comment by gunlee01** [comment]
cpu는 host agent에서 제공하는거라 java agent만 있는 경우에는 나오지 않습니다
