### ISSUE TITLE
BigSur client 이슈

### ISSUE THREAD

**Issue by dsChoi** [scouter-project/scouter#823]
안녕하세요 
BigSur 에서 client 사용중인데 이번에 2.15.0 release 되고나서 다른 것들은 동작이 잘 되고 있는데  아래처럼 xloglist 가 모양이 제대로 안나오고 있어 문의드립니다. 

![image](https://user-images.githubusercontent.com/4524328/135944369-56bc232e-fd7a-41f8-b280-715a4e58dda0.png)

클립보드로 데이터 복사하여 보면 아래처럼 데이터가 나오고 있습니다. 

`
/i-.api.prod/ds-test-api	160	/v2/{bbb}/{aaa}<GET>	09:49:36.599	1	0	0	0	0	101	127.0.0.1									z241s	0	09:49:36.439			/v2
`

**Comment by gunlee01** [comment]
재현이 안되고 있어서 좀 더 확인이 필요할 것 같습니다.

**Comment by gunlee01** [comment]
Group 컬럼만 글자가 보여지고 나머지는 보이지 않는 현상인가요?

**Comment by gunlee01** [comment]
컬럼의 위치를 옮겨도 동일한가요?

**Comment by dsChoi** [comment]
네 컬럼 위치 옮겨도 동일합니다. 
캡쳐를 다시 해보아았는데 아래처럼 데이터가 나옵니다. 
xlog column 은 안나와서 아래처럼 추가해주었습니다. 
![image](https://user-images.githubusercontent.com/4524328/135997453-f4e32ef8-220a-446f-8b0c-ce3f3513b1f4.png)


![image](https://user-images.githubusercontent.com/4524328/135997296-47cd62b9-1898-4c66-82d0-c504b17153b9.png)

**Comment by dsChoi** [comment]
xlog colum 을 아래만 선택하면 xlog list 에 아무것도 나오지 않습니다. 

## xlog column setting
![image](https://user-images.githubusercontent.com/4524328/135997724-809c705e-8914-493b-89f5-c2306f50fd0d.png)

## XlogList
![image](https://user-images.githubusercontent.com/4524328/135997789-b9c04257-a99d-4458-8c90-74d7d4eff3a1.png)

**Comment by dsChoi** [comment]
/Users/{유저명}/.scouter
폴더 삭제후 정상 동작 합니다.
