### ISSUE TITLE
xlog_error_jdbc_fetch_max 최대값 문의

### ISSUE THREAD

**Issue by spicyyou** [scouter-project/scouter#825]
안녕하세요. 코드를 보다보니 궁금한 점이 생겨서 문의드립니다.
xlog_error_jdbc_fetch_max = 10000으로 디폴트가 잡혀있던데
이렇게 설정하신 이유가 있는지 궁금합니다

**Comment by gunlee01** [comment]
레거시 시스템에서 대량 데이터 조회로 메모리 효율 저하를 유발하고 전체 시스템 성능 저하 혹은 장애로 연결되는 경우가 많아서 10,000건 이상이면 경고를 줄 필요가 있어서 그렇게 설정이 되어 있습니다. 운영중인 시스템 상황에 따라 조절하면 될 것 같습니다.
