### ISSUE TITLE
Object Type 변경 문의

### ISSUE THREAD

**Issue by hiddentrap** [scouter-project/scouter#832]
안녕하세요. 

이번에 scouter를 사용해보려고 열심히 노력중인데요

모니터링 대상 어플리케이션이 SpringBoot 기반에 Netty를 결합해서 개발했고 여기에 WebMVC가 붙어서 내장 톰캣도 같이 

돌아가는 형태입니다. 실행은 .jar 로 실행시키구요. 

그래서 여기저기 검색해서, 

`
obj_name=이름
net_collector_ip=수집서버ip
net_collector_udp_port=수집서버포트
net_collector_tcp_port=수집서버포트
hook_service_patterns=com.abc.a.MyHandler.chennelRead
`
이런 설정으로 

`
java -javaagent:/scouter/atgent.java/scouter.agent.jar -Dscounter.config=/scouter/agent.java/setting.conf -jar -Dspring.profiles.active=prod bootapp.jar
`
이런식으로 agent를 지정해서 실행시키는데요. 

이렇게 실행시키면

클라이언트에서 확인해보면, 해당 오브젝트가 tomcat으로 인식되서 수집이 됩니다. 

그래서 XLog가 tomcat용으로 열리고, 데이터가 찍히기는 하는데 SQL 관련 데이터가 안찍히고, 프로파일링도 좀 이상한거 같아서, 

어차피 app의 메인이  netty라서, 해당 오브젝트를 tomcat이 아닌 java로 인식시켜서 java용 XLog로 확인해보고 싶은데, 

혹시 방법이 있을까 경험자 분들께 문의 드립니다~ 

감사합니다.

**Comment by gunlee01** [comment]
obj_type에 원하는 이름을 주면 됩니다.
