### ISSUE TITLE
object_deadtime_ms 을 어디다 세팅하는지 문의드립니다.

### ISSUE THREAD

**Issue by maizard** [scouter-project/scouter#833]
반갑습니다.

scouter 때문에 많으 도움을 받고 있습니다.

특정 서버에서 갑자기 inactive, active info를 많이 보내서 찾아보니

object_deadtime_ms 이 시간을 늘려주면 해결이 가능하다고 보았습니다.

질문이 2가지 입니다.

1. 특정 서버만 object_deadtime_ms 를 늘릴 수 있습니까?
2. object_deadtime_ms 를 어떻게 설정하는지 상세히 알려주시면 감사하겠습니다.

언제나 건강하시고, 수고하십시오.

**Comment by gunlee01** [comment]
object_deadtime_ms 은 collector server 설정입니다. 
해당 collector로 접속하는 모든 agent에 적용됩니다.
