### ISSUE TITLE
컨테이너 환경에서도 java agent 사용 할 수 있는지 문의 드립니다.

### ISSUE THREAD

**Issue by yangmyunggil** [scouter-project/scouter#846]
안녕하세요.

이번에 AWS EC2 -> AWS EKS로 변경하게 되어 질문드립니다.

리눅스에서 scouter apm을 잘 사용하고 있었는데요. 
**컨테이너 환경에서도 scouter 사용가능한가요?**
WAS는 톰캣을 사용합니다.

**Comment by gaiajeon** [comment]
현재 릴리즈된 scouter 바이너리를 그대로 사용해서 올려본적은 없습니다만 

제가 수정한 버젼으로는 올려본적은 있으니

가능하지 않을까 생각합니다.

 docker 파일만 잘 만드시면 될것 같습니다.

**Comment by yangmyunggil** [comment]
답변 감사합니다.!!! ^^
