### ISSUE TITLE
안녕하세요 web api 관련해서 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by dayoon97** [scouter-project/scouter#851]
스카우터 api server를 스카우터 수집서버에서 실행하려고 합니다.
`net_collector_ip_port_id_pws ` 이 항목은 어디서 설정해야 할까요??

**Comment by gunlee01** [comment]
scouter webapp의 conf/scouter.conf 파일에 설정할 수 있습니다.
만약 webpp을 embedded 모드로 사용한다면 scouter collector server의 설정 파일에 설정해야 합니다.

**Comment by dayoon97** [comment]
감사합니다!
