### ISSUE TITLE
nexacro와 x-up을 Scouter로 모니터링하고 싶습니다.

### ISSUE THREAD

**Issue by Lee-SeungYeob** [scouter-project/scouter#863]
Spring을 통해 개발된 다른 어플리케이션은 X-LOG에 정상적으로 출력이 되는데
nexacro와 x-up으로 개발된 어플리케이션에서는 X-LOG에 리소스를 불러오는 일부 서비스만 출력됩니다.

![image](https://user-images.githubusercontent.com/80512800/166207408-5dcc7c50-9201-4505-8571-5607dce31cd7.png)

### <--TOMCAT_LOG-->
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/sta_LOGIN_Bg01.jpg HTTP/1.1" 200 89250
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/chk_Login_icdChkbox.png HTTP/1.1" 200 109
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/sta_Login_icdLogo.png HTTP/1.1" 200 2777
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/edt_Login_icdPw.png HTTP/1.1" 200 316
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/cmb_Login_icdLang.png HTTP/1.1" 200 233
222.98.215.253 - - [02/May/2022:17:15:50 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/edt_Login_icdUser.png HTTP/1.1" 200 325
222.98.215.253 - - [02/May/2022:17:16:00 +0900] "GET /DevPack/nui/_resource_/_theme_/nui/images/loading_img.gif HTTP/1.1" 200 3985
222.98.215.253 - - [02/May/2022:17:16:01 +0900] "POST /DevPack/FrontControllerServlet.do?service=xupservice&version=xplatform&domain=xup&model=/LOGIN&format=ssv HTTP/1.1" 200 2846
222.98.215.253 - - [02/May/2022:17:16:02 +0900] "POST /DevPack/FrontControllerServlet.do?service=xupservice&version=xplatform&domain=xup&model=/GET_INIT_DATA&format=ssv HTTP/1.1" 200 1146068
222.98.215.253 - - [02/May/2022:17:16:02 +0900] "POST /DevPack/FrontControllerServlet.do?service=xupservice&version=xplatform&domain=xup&model=/COMNBE004TN_S01&format=ssv HTTP/1.1" 200 1201

### **<--agent.conf-->**
_trace_auto_service_enabled=true
_trace_auto_service_backstack_enabled=true
trace_interservice_enabled=true

hook_method_patterns=
hook_method_access_public_enabled=true
hook_method_access_private_enabled=true
hook_method_access_protected_enabled=true
hook_method_access_none_enabled=true
hook_method_ignore_prefixes=set

#Method set for service hooking
hook_service_patterns=/DevPack/FrontControllerServlet.do

### **<--host.conf-->**
net_collector_ip=127.0.0.1
net_collector_udp_port=6100
net_collector_tcp_port=6100
cpu_warning_pct=80
cpu_fatal_pct=85
cpu_check_period_ms=60000
cpu_fatal_history=3
cpu_alert_interval_ms=300000
disk_warning_pct=88
disk_fatal_pct=92

### **<--server.conf-->**
ext_plugin_influxdb_enabled : true
ext_plugin_influxdb_measurement : counter

ext_plugin_influxdb_udp : true
ext_plugin_influxdb_udp_target_ip : 127.0.0.1
ext_plugin_influxdb_udp_target_port : 8089

ext_plugin_influxdb_http_target_ip : 127.0.0.1
ext_plugin_influxdb_http_target_port : 8086
ext_plugin_influxdb_http_retention_policy : autogen

ext_plugin_influxdb_id : root
ext_plugin_influxdb_password : root
ext_plugin_influxdb_dbName : scouterCounter

**Comment by gunlee01** [comment]
nexacro와 x-up를 사용해보지 않아서 정확한 답변을 드리긴 어려울 것 같습니다. 
서블릿 방식이 아니라면 hook_service_patterns 옵션을 적절히 이용해서 모니터링 대상이 되는 부분을 매뉴얼하게 지정해야 합니다.
