### ISSUE TITLE
exception on java 17

### ISSUE THREAD

**Issue by gunlee01** [scouter-project/scouter#866]
20220511 21:28:39 [A905] java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4cafa2d9

**Comment by bill23-kim** [comment]
요거 작업 시작 안하셨으면 제가 수정할께요

**Comment by bill23-kim** [comment]
assign 해주시면 시작 하겠습니다

**Comment by SamuelPark** [comment]
[A905] java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4eb45cfa

저도 이 에러가 나는데 이 이슈에 해당되는 내용인가요?

**Comment by gunlee01** [comment]
이 부분은 jvm 옵션에 아래 내용을 추가하시면 됩니다.
```
--add-opens=java.base/java.lang=ALL-UNNAMED -Djdk.attach.allowAttachSelf=true
```
