### ISSUE TITLE
hook_service_patterns 설정 및 xLog 에 service 에 잡히는 값 문의

### ISSUE THREAD

**Issue by ttaeyoung** [scouter-project/scouter#873]
안녕하세요.

Spring KafkaListener 를 사용하는 consumer 동작을 프로파일링 하고 싶어서 [NON-HTTP-Service-Trace](https://github.com/scouter-project/scouter/blob/master/scouter.document/use-case/NON-HTTP-Service-Trace_kr.md) 을 참고해서 hook_service_patterns 설정을 추가하였습니다.

궁금한 점은 
1. 여러 패키지에 xxConsumer 로 끝나는 클래스의 함수를 한번에 patterns 로 잡을 수 있나요?
예를 들어 com.kafka.consumer.a.xxConsumer 와 com.kafka.consumer.b.xxConsumer 의 함수를 프로파일링하고 싶은 경우,
아래와 같은 방법으로만 추가가 가능한건가요?
```
hook_service_patterns=com.kafka.consumer.a.*Consumer.*,com.kafka.consumer.b.*Consumer.*
```
2. 페이스북 그룹 페이지에서 보고 클래스나 메소드까지 프로파일링 대상으로 선언했는데,3. 
scouter client 의 service 명이 함수가 아니라 함수의 파라미터로 잡힙니다. 이걸 함수명이나 클래스명으로 잡고 싶다면 어떤식으로 설정해야 할까요?
설정은 아래와 같이 해서 테스트해보았습니다.
```
hook_service_patterns=com.kafka.consumer.b.xxConsumer.*
hook_method_access_public_enabled=false
hook_method_access_private_enabled=false
hook_method_access_protected_enabled=false
hook_method_ignore_prefixes=get,set,is,lambda
```

**Comment by gunlee01** [comment]
1번 : 써주신 방법으로 넣으시면 됩니다. 
2번 : `hook_service_name_use_1st_string_enabled=false` 로 옵션을 설정하면 됩니다.
