### ISSUE TITLE
scouter agent 연동 시 UDP만 오픈

### ISSUE THREAD

**Issue by spc1jh** [scouter-project/scouter#880]
안녕하세요

scouter agent 연동 시 UDP만 연동해서 사용했을때의 데이터 수집의 문제점이 있을까요?

TCP 쪽은 client 연동으로 쓰는걸로 알고 있는데 
기본데이터만 수집한다면 tcp 오픈이 필요할까요??

TCP, UDP 동시 오픈이 안되는 환경이라 문의드립니다. 

감사합니다.

**Comment by gunlee01** [comment]
TCP 오픈이 필요합니다.

**Comment by spc1jh** [comment]
감사합니다.
