### ISSUE TITLE
XLog 상에서 scouter.agent.error.ASYNC_SERVLET_TIMEOUT 에러가 지속적으로 발생합니다.

### ISSUE THREAD

**Issue by pji114** [scouter-project/scouter#882]
현재 Spring Application에서 특정 POST 메소드에 DeferredResult 를 사용하고 있습니다.

그런데 XLog 상에서 위의 저 메소드가 지속적으로 scouter.agent.error.ASYNC_SERVLET_TIMEOUT 이라는 에러가 발생하고 있습니다.

Application 단에서는 DeferredResult 가 타임아웃이 발생하여 onTimeout 이벤트를 호출하고 세션을 정리할텐데
이경우 혹시 oneTimeout 이벤트가 Souter 의 XLog 에서 에러로 판단 하는걸까요?

만약 그렇다면 특정 POST 메소드를 XLog 에서 제외처리 할수 있을까요?

**Comment by gunlee01** [comment]
`hook_exception_handler_exclude_class_patterns` 옵션에 해당 exception class 를 넣으면 에러로 판단하지 않게 됩니다.
