### ISSUE TITLE
특정 url패턴 호출시 xlog 수집이 되지 않는 경우

### ISSUE THREAD

**Issue by ks3333** [scouter-project/scouter#883]
안녕하세요. 스카우터 사용중에 특정한 url패턴을 호출하면 xlog가 수집되지 않는 경우가 있어 문의 드립니다.

Spring boot 2.6.1로 개발된 애플리케이션을 tomcat 9.0.53 버전의 외부 was에 올려 사용중입니다
현재 사용하고 있는 스카우터 버전은 2.5 버전이며,
해당 환경에서 Aws sdk를 통해 aws object storage 파일을 호출해서 내려주는 클래스에서 이런 현상이 타나납니다.

현재 object storage 폴더 구조가 정형화 되어 있지 않아 urlpatten을 {bucket}/{*key} 형태로 매칭시켜 사용중입니다
그래서 해당 패턴에 들어오는 모든 url은 모두 동일한 클래스의 동일한 메소드를 실행하게 되는데
*key에 매칭되는 패턴 중 .jpg, .png로 끝나는 url패턴이 호출될때는 xlog가 수집되지 않는 현상이 발생합니다.

현재 object storage에 mp4, jpg, png 형태의 파일이 올라가 있는데, 혹시나 해서 .mp4로 호출해보면 정상적으로 xlog가 수집되고, jpg와 png의 경우는 마지막에 .jpg/ <- 이런 패턴으로 호출하면 또 xlog에 수집이 되고 있어서 특정 패턴에 대해 수집이 되지 않는것이 맞는지, 혹은 별도 옵션 설정을 통해 변경할 수 있는지 확인드리고자 문의 남깁니다.

**Comment by gunlee01** [comment]
java agent 옵션중에 `mgr_static_content_extensions` 옵션을 조정해 보시면 될 것 같습니다.

**Comment by ks3333** [comment]
해당 옵션 변경하니 정상적으로 수집 되네요. 감사합니다.
