### ISSUE TITLE
JBoss 지원되는 건가요?

### ISSUE THREAD

**Issue by bume1029** [scouter-project/scouter#89]

**Comment by gunlee01** [comment]
JBoss에 적용시 JBoss7 부터는 -Djboss.modules.system.pkgs=~~~~~,scouter 옵션을 추가해 주어야합니다.
https://groups.google.com/forum/#!topic/scouter-project/MOvaQ9X6Qxc

**Comment by iwindfree** [comment]
JBoss 적용시 EAP 버전인 경우 6.x  버전, AS 버전인 경우 7.x 버전부터 -Djboss.modules.system.pkgs =~~~~,scouter 옵션을 추가해 주어야 합니다.
