### ISSUE TITLE
How to profile response content in xLog?

### ISSUE THREAD

**Issue by qeorbn** [scouter-project/scouter#896]
For now , I can see the parameters in xLog.
By using this:
profile_http_parameter_enabled = true

But,how to profile response content in xLog? @gunlee01

**Comment by qeorbn** [comment]
@gunlee01 회신을 기대

**Comment by gunlee01** [comment]
no way to profile response context

**Comment by qeorbn** [comment]
> no way to profile response context

How about the httpservice.plug?
Any chance?

**Comment by qeorbn** [comment]
> no way to profile response context

How about the httpservice.plug?
Any chance?
@gunlee01

**Comment by qeorbn** [comment]
With custom HttpServletResponseWrapper, reponse content can be profiled in xlog using httpservice.plug
