### ISSUE TITLE
Profile Truncated

### ISSUE THREAD

**Issue by w15115** [scouter-project/scouter#914]
Hi all,

Please help me inrcrease the line of profile.

![image](https://user-images.githubusercontent.com/3120419/208048715-6de886fc-2333-48f6-b274-0323dd3ca96d.png)
It's not showing full.

Thanks you.

**Comment by gunlee01** [comment]
use the menu, save full profile.
![image](https://user-images.githubusercontent.com/6788732/216523607-49e30306-931e-4742-be9c-506d7a9bee73.png)

**Comment by w15115** [comment]
I got it! Thank you so much
