### ISSUE TITLE
xlog 문의

### ISSUE THREAD

**Issue by hkjang** [scouter-project/scouter#93]
scouter 설치해서 테스트 한번 해보고 있습니다.
먼저 유용한 오픈 소스 개발 감사해요~~^^

tomcat 이와 다른 web app server 의 java agent 에서 xlog 를 사용 가능한지 질문드려요~
jetty, jboos, jeus, websphere 등등~

**Comment by gunlee01** [comment]
안녕하세요.
tomcat이 집중 테스트 되었으며, jetty, jbose, resin등도 어느 정도 테스트 및 구동 확인 되었습니다.
별 문제는 없을 듯 합니다.
기타 상용 was는 별도로 테스트 되지 않았습니다.

**Comment by hkjang** [comment]
@gunlee01 사실 xlog를 어디서 띄우는지 잘 모르겠습니다. object 에서 마우스 오른 클릭하면  퍼포먼스 카운터랑 오브젝트 리퀘스트가 나오긴 하는데 그곳에서는 xlog를 찾을 수 없고.. 
어디서 띄워야 하는지 문의드리는 것이긴 합니다.

**Comment by gunlee01** [comment]
수집서버에서 우클릭한후에 Tomcat 하위에 있습니다~

**Comment by hkjang** [comment]
아~ 그렇군요! 감사합니다. 드디어 찾았습니다.
