### ISSUE TITLE
 server 와 agent 의 version mismatch 에 대한 이슈가 있을까요?

### ISSUE THREAD

**Issue by Nickkun** [scouter-project/scouter#939]
Server 는 2.7.0 버전이고  최신 릴리즈는 2.17.1 버전인데,
Server <> Agent 간 버전 차이에 대한 이슈가 있을까요?
Client로 확인할때 Server에 agent 리스트가 추가가 되고 있지 않아서, 혹시 Server, Agent의 Version도 맞춰줘야 하나 해서요.

+
AWS 환경에서 구성시, 방화벽은 6100 포트에 대해 TCP/UDP 양방향 오픈을 해야할까요?

**Comment by gunlee01** [comment]
일반적으로 Server가 Agent보다 버전이 같거나 높아야 합니다. 
하지만 Server, Agent, Client 같은 버전을 사용하는걸 권장합니다. 

6100 UDP/TCP 포트는 Agent -> Server 방향으로만 오픈하면 됩니다.
