### ISSUE TITLE
macbook m1, m2에서는 클라이언트 프로그램 실행이 불가한가요??

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#957]
macbook m1, m2에서는 클라이언트 프로그램 실행이 불가한가요??
혹시 실행할수 있는 방법이 있나요?

**Comment by soda-neil** [comment]
arm용으로 빌드된 client를 실행하시면 될 듯 합니다.

**Comment by geuno-gil** [comment]
release에 확인해보시면 `scouter.client.product-macosx.cocoa.aarch64.tar.gz` 이라는 파일 이름있어요
그거 다운받으시면 돼요
