### ISSUE TITLE
cubrid xlog  sql 프로파일링 문의

### ISSUE THREAD

**Issue by ymggt** [scouter-project/scouter#96]
안녕하세요 우연한 기회에 알게되서 한번 설치 해봤습니다.
참 좋네요...ㅎㅎㅎ 이것때문에 고민이 많았는데 말이죠.. 
근데 저희 프로젝트에서 cubrid를 사용하는데 xlog 프로파일링 내용보니까 sql정보는 하나도 안나오더군요.. cubrid 라서 그런가요?? 어짜피 jdbc 사용하면 기본적인건 나오지 않을까 하는데...

**Comment by gunlee01** [comment]
### Scouter에서 빌트인으로 hooking 하지 않는 jdbc 드라이버 사용시 쿼리 프로파일링 하는 방법

현재 cubrid db에 대해 빌트인으로 hooking 하지는 않습니다.
하지만 scouter는 이러한 부분에 대해 확장 포인트를 가지고 있어 agent에 추가적인 설정을 해주시면 가능합니다.

#### Query profiling - 아래 설정으로 가능합니다.(설정 후 WAS 재기동 필요) 
hsql 예시 - hsql은 설정 없이도 profiling을 하고 있으며 이해를 돕기위한 예시입니다. 
jdbc 드라이버에서 구현한 Statement, PreparedStatement 구현체를 지정해야 합니다. 
```properties
  hook_jdbc_pstmt_classes=org.hsqldb.jdbc.JDBCPreparedStatement
  hook_jdbc_stmt_classes=org.hsqldb.jdbc.JDBCStatement
```

**Comment by gunlee01** [comment]
드라이버 까보니
`cubrid.jdbc.driver.CUBRIDPreparedStatement`
`cubrid.jdbc.driver.CUBRIDStatement`
인것 같네요.

**Comment by ymggt** [comment]
위 설정을 하는부분이 \scouter.agent\scouter\agent.host\conf\scouter.conf 이 파일인가요??
톰켓이 로드되면서
20160113 09:47:41 [SCOUTER] loaded by system classloader 
20160113 09:47:41 [SCOUTER] Version 0.4.2 20160104
20160113 09:47:41 [SCOUTER] jar:file:/D:/Download/scouter.agent/scouter/agent.java/scouter.agent.jar
20160113 09:47:41 [SCOUTER] objType:tomcat
20160113 09:47:41 [SCOUTER] objName:/jglee64-PC/uSmartFarm_AUX
20160113 09:47:41 [A115] java version : 1.7.0_65
20160113 09:47:41 [A113] Counter Collector Started (#16)
20160113 09:47:41 [SCOUTER] Configure -Dscouter.config=D:\Download\scouter.agent\scouter\agent.host\conf\scouter.conf
20160113 09:47:41 [A100] agent boot seed=x1738s77lod
이렇게 출력이 되고
scouter.conf 파일에 위와 같이 정의를 했는데 잘 안되네요 ㅜㅜ

**Comment by bill23-kim** [comment]
수정하신 파일은 host agent 의 conf 파일이고 java agent 에 conf 파일은 기동시 설정을 주지 않으면 톰캣 실행 스크립트와 같은 디렉토리에 scouter.conf 파일로 생깁니다. 클라이언트를 통해 수정 하시면 경로 신경쓰지 않고 수정하실수 있습니다. 오브젝트뷰 -> 톰캣 우클릭 -> Configure -> 수정 -> 저장 -> 톰캣 재기동

**Comment by ymggt** [comment]
일단 conf 파일을 host agent 경로에 있는것을 사용하긴 했는데 그것이 문제 인것 같지는 않고 클라이언트의 설정을 보니 해당 conf를 제가 세팅한 값으로 읽어서 보여주고는 있습니다. 아무튼 지적하신대로 conf 를 새로 만들어서 경로를 다시 지정하고 세팅을 완료하고 톰켓을 재시작 했는데 sql 프로파일링은 잘 안되네요... 흠...

참고로 현재 테스트 하느라고 이클립스에서 run configuration에서 vm arguments에 인자를 넣어서 세팅을 했습니다.

추가 인자
-javaagent:"D:\Download\scouter.agent\scouter\agent.java\scouter.agent.jar" 
-Dscouter.config="D:\Download\scouter.agent\scouter\agent.java\scouter.conf"

**Comment by bill23-kim** [comment]
설정은 제대로 넣으신것 같네요. 아직 큐브리드 테스트가 진행되지 않아 현재로선 정확히 말씀드리기가 어렵습니다. 큐브리드 SQL 을 수집하기 위한 새로운 이슈가 등록 됐으니 조만간 디폴트로 추가해서 배포하도록 하겠습니다. 현재 이슈는 클로즈 하겠습니다.

**Comment by gunlee01** [comment]
큐브리드 jdbc driver를 좀 자세히 보니 현재 SCOUTER에서 사용하는 일반적인 JDBC 드라이버와 구조가 좀 다르네요. PreparedSatement의 생성자에 sql 이 아닌 UStatement라는 객체가 들어가는 구조입니다.
드라이버 소스 상세 확인해서 패치 진행할 예정이니
큐브리드 지원 피처 추가를 기다려 보시면 될 것 같습니다. 오래 걸리진 않을 것 같습니다.

**Comment by gunlee01** [comment]
v0.4.4 릴리즈에서 지원합니다.

**Comment by hwi94** [comment]
안녕하세요 !!

좋은 프로그램 만들어주셔서 너무 감사합니다. 
설치한지 얼마안된 사용자인데요 
사내 프로젝트에 적용시키려 공부하고있습니다만, 
Query profiling hook 말고 result hook 은 안될까요 .. ??
이를테면 sql developer 처럼 쿼리를 날렸을때 엑셀형태로 profile 영역에서 보고싶은욕망이있습니다.
이러한 기능도 제공이 되는지 여쭙고싶습니다 !

**Comment by gunlee01** [comment]
@hwi94 응답에 대해선 프로파일링을 지원하지 않습니다.
변수가 많아 앞으로도 어려울 듯 합니다.
